- ramls/schema/README.md
- ramls/schema/loan
> FOLIO-573 symlink schema

- .dockerignore
- Jenkinsfile
> Jenkinsfile

- DeploymentDescriptor.json
- Jenkinsfile
- ModuleDescriptor.json
- NEWS.md
- ramls/examples/loans.json
> FOLIO-351 tidy 2

- build.gradle
- registration/activate.json
- stop-managed-demo.sh
- test-storage.sh
- test-via-okapi.sh
> FOLIO-813 artifact mod- prefix

- ramls/loan.json
- ramls/request.json
Enable upper-case in first segment.
> FOLIO-972 Improve UUID-like regex

- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/test/java/org/folio/circulation/api/APITestSuite.java
- src/test/java/org/folio/circulation/api/requests/RequestsAPICreateMultipleRequestsTests.java
- src/test/java/org/folio/circulation/api/requests/RequestsAPIStatusChangeTests.java
The item status will be the status of the last request created
> Allow multiple requests for same item CIRC-54

- NEWS.md
- build.gradle
- descriptors/ModuleDescriptor-template.json
- registration/activate.json
- src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/test/java/org/folio/circulation/api/APITestSuite.java
- src/test/java/org/folio/circulation/api/fakes/FakeOkapi.java
- src/test/java/org/folio/circulation/api/loans/LoanAPILocationTests.java
- src/test/java/org/folio/circulation/api/loans/LoanAPITests.java
- src/test/java/org/folio/circulation/api/loans/LoanAPITitleTests.java
- src/test/java/org/folio/circulation/api/requests/RequestsAPITitleTests.java
- src/test/java/org/folio/circulation/api/support/builders/InstanceRequestBuilder.java
- src/test/java/org/folio/circulation/api/support/builders/ItemRequestBuilder.java
- src/test/java/org/folio/circulation/api/support/fixtures/InstanceRequestExamples.java
- src/test/java/org/folio/circulation/api/support/fixtures/ItemRequestExamples.java
- src/test/java/org/folio/circulation/api/support/http/InterfaceUrls.java
- src/test/java/org/folio/circulation/api/support/http/ResourceClient.java
- stop-managed-demo.sh
- test-via-okapi.sh
Previous versions could potentially also be supported, if this is needed,
can be investigated in minor implementation version increment
> Require item storage v5.0 and instance storage v4.0 CIRC-57

- pom.xml
- src/main/java/org/folio/circulation/resources/LoanRulesEngineResource.java
- src/test/java/org/folio/circulation/api/APITestSuite.java
- src/test/java/org/folio/circulation/api/LoanRulesEngineAPITests.java
- src/test/java/org/folio/circulation/api/requests/RequestsAPICreationTests.java
- src/test/java/org/folio/circulation/api/support/http/AdditionalHttpStatusCodes.java
- src/test/java/org/folio/circulation/api/support/http/InterfaceUrls.java
- src/test/java/org/folio/circulation/api/support/http/ResourceClient.java
- src/test/java/org/folio/circulation/api/support/matchers/StatusMatcher.java
Unit test requested in https://issues.folio.org/browse/CIRC-59
> CIRC-59: Test loan rules engine cache

- README.md
- doc/guide.md
Adds a guide/description to the module.
> Circ 76 create doc

- ramls/loan.json
- ramls/request.json
Fix regex typo A-Z rather than A-F
Introduced in pull #33
> FOLIO-972 Fix UUID pattern A-Z

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/circulation.raml
- ramls/examples/loan.json
- ramls/loan.json
- src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
- src/main/java/org/folio/circulation/support/JsonArrayHelper.java
- src/test/java/org/folio/circulation/api/APITestSuite.java
- src/test/java/org/folio/circulation/api/fakes/FakeOkapi.java
- src/test/java/org/folio/circulation/api/loans/LoanAPITests.java
- src/test/java/org/folio/circulation/api/support/builders/HoldingRequestBuilder.java
- src/test/java/org/folio/circulation/api/support/builders/InstanceRequestBuilder.java
- src/test/java/org/folio/circulation/api/support/fixtures/ItemsFixture.java
- src/test/java/org/folio/circulation/api/support/http/InterfaceUrls.java
- src/test/java/org/folio/circulation/api/support/http/ResourceClient.java
- test-via-okapi.sh
https://issues.folio.org/browse/CIRC-80
> Circ80 mergemaster

- README.md
- doc/guide.md
- ramls/loan.json
- src/main/java/org/folio/circulation/support/LoanRulesClient.java
- src/test/java/org/folio/circulation/api/support/builders/InstanceRequestBuilder.java
- src/test/java/org/folio/circulation/api/support/builders/LoanRequestBuilder.java
> FOLIO-398 tidy 2

- descriptors/ModuleDescriptor-template.json
> add launch descriptor to md template

- src/test/java/org/folio/circulation/loanrules/Text2DroolsTest.java
> CIRC-73: Loan rule is not processed when no space after colon

- NEWS.md
- README.md
> FOLIO-1253 test generate-api-docs

- README.md
Does not include list of possible errors
> Introduce basic documentation for renewal using barcodes API CIRC-100

- ramls/schema/loan-rules-error.json
> FOLIO-1253 test generate-api-docs 2

- ramls/schema/loan-rules.json
> FOLIO-1253 test generate-api-docs 3

- ramls/schema/loan-rule-match.json
- ramls/schema/loan-rule-matches.json
- ramls/schema/loan-rules-id-error.json
> FOLIO-1253 test generate-api-docs 4

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- okapi-registration/unmanaged-deployment/register.sh
- pom.xml
- ramls/request.json
- src/main/java/org/folio/circulation/domain/LoanValidation.java
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/User.java
- src/test/java/api/APITestSuite.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/requests/RequestsAPIModificationTests.java
- src/test/java/api/requests/scenarios/MultipleHoldShelfRequestsTests.java
- src/test/java/api/requests/scenarios/MultipleMixedFulfilmentRequestsTests.java
- src/test/java/api/requests/scenarios/SingleOpenHoldShelfRequestTests.java
- src/test/java/api/support/builders/RequestBuilder.java
- src/test/java/api/support/builders/UserBuilder.java
- src/test/java/api/support/fakes/FakeOkapi.java
- src/test/java/api/support/http/InterfaceUrls.java
- src/test/java/api/support/http/ResourceClient.java
- src/test/java/org/folio/circulation/domain/UserTests.java
- test-via-okapi.sh
https://issues.folio.org/browse/CIRC-90
https://issues.folio.org/browse/CIRC-114
> CIRC-90, CIRC-114

- ramls/request.json
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/RequestRepository.java
- src/main/java/org/folio/circulation/domain/RequestRepresentation.java
- src/main/java/org/folio/circulation/domain/User.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/main/java/org/folio/circulation/support/JsonPropertyFetcher.java
- src/test/java/api/APITestSuite.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
- src/test/java/api/support/builders/Address.java
- src/test/java/api/support/builders/UserBuilder.java
- src/test/java/api/support/fakes/FakeOkapi.java
- src/test/java/api/support/fixtures/UsersFixture.java
- src/test/java/api/support/http/InterfaceUrls.java
- src/test/java/api/support/http/ResourceClient.java
*Known Limitations*
* Delivery addresses are not mapped to the response JSON for multiple requests (to be resolved following the merge of CIRC-156 pull request)
> Fix null pointer exception when including delivery address for request CIRC-164

- NEWS.md
- pom.xml
* https://issues.folio.org/browse/CIRC-176
> Release 14.1.0

- src/main/java/org/folio/circulation/domain/LoanAndRelatedRecords.java
- src/main/java/org/folio/circulation/domain/validation/ServicePointLoanLocationValidator.java
- src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
- src/test/java/api/loans/CheckInByReplacingLoanTests.java
- src/test/java/api/loans/LoanAPITests.java
- src/test/java/api/loans/RenewByIdTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
- src/test/java/api/requests/scenarios/ClosedRequestTests.java
- src/test/java/api/requests/scenarios/MultipleHoldShelfRequestsTests.java
- src/test/java/api/requests/scenarios/MultipleMixedFulfilmentRequestsTests.java
- src/test/java/api/requests/scenarios/SingleOpenHoldShelfRequestTests.java
- src/test/java/api/support/matchers/ValidationErrorMatchers.java
> Validate existence of service points for loans on creation and update CIRC-173

- descriptors/ModuleDescriptor-template.json
- ramls/circulation.raml
- ramls/request.json
- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/domain/RequestQueueRepository.java
- src/main/java/org/folio/circulation/domain/RequestStatus.java
- src/main/java/org/folio/circulation/domain/UpdateItem.java
- src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
- src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/test/java/api/loans/scenarios/ServicePointCheckInTests.java
- src/test/java/api/loans/scenarios/ServicePointCheckOutTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/fixtures/RequestsFixture.java
- src/test/java/api/support/fixtures/ServicePointExamples.java
- src/test/java/api/support/fixtures/ServicePointsFixture.java
- CIRC-193: Ensure that an item is not ready for pick up until it is at the pick up service point location.
- CIRC-172: Add in transit status to item and request.
> CIRC-193 & CIRC-172 - additions to item/request statuses

- src/main/java/org/folio/circulation/domain/policy/FixedScheduleRenewalDueDateStrategy.java
- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/main/java/org/folio/circulation/domain/policy/RollingRenewalDueDateStrategy.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/org/folio/circulation/domain/policy/FixedLoanPolicyRenewalDueDateCalculationTests.java
- src/test/java/org/folio/circulation/domain/policy/RollingLoanPolicyRenewalDueDateCalculationTests.java
CIRC-212
Change renewal failure messages to match requirements.
Resolves: [CIRC-212](https://issues.folio.org/browse/CIRC-212)
> CIRC-212 Change renewal failure messages to match requirements

- src/main/java/org/folio/circulation/CirculationVerticle.java
Till CIRC-239 is implemented, this can alleviate the mod-circulation hang problem (CIRC-225) under normal and even high load.
> CIRC-225: bump up connection pool size to alleviate app hang

- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/domain/LoanRepository.java
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/UpdateLoan.java
- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/main/java/org/folio/circulation/support/ClockManager.java
- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
- src/test/java/api/support/builders/LoanPolicyBuilder.java
- src/test/java/api/support/fixtures/RequestsFixture.java
- src/test/java/api/support/fixtures/ServicePointsFixture.java
Followed logic defined in [CIRC-203](https://issues.folio.org/browse/CIRC-203) to potentially reduce the due date of a loan when a recall request. The logic determines this by using a series of settings from the loan policy.
>  Implement CIRC-203

- README.md
Add known limitations about tenant-selected timezone and locale support
> Add known limitations to README

- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/validation/BlockRenewalValidator.java
- src/main/java/org/folio/circulation/resources/OverrideRenewalByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/RenewByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/RenewByIdResource.java
- src/main/java/org/folio/circulation/resources/RenewalResource.java
- src/main/java/org/folio/circulation/storage/SingleOpenLoanByUserAndItemBarcodeFinder.java
- src/test/java/api/requests/RequestsAPILoanRenewalTests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/http/ResourceClient.java
- Create a Validator.
- Add the Validator to
OverrideRenewalByBarcodeResource,
RenewByBarcodeResource,
RenewByIdResource.
- Create UTs
> CIRC-202 Block Renewal With Existing Recall Request

- src/main/java/org/folio/circulation/domain/notice/NoticeContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/PatronNoticeEvent.java
- src/main/java/org/folio/circulation/domain/notice/PatronNoticeEventBuilder.java
- src/main/java/org/folio/circulation/domain/notice/PatronNoticePolicy.java
- src/main/java/org/folio/circulation/domain/notice/PatronNoticePolicyMapper.java
- src/main/java/org/folio/circulation/domain/notice/PatronNoticeService.java
- src/main/java/org/folio/circulation/domain/policy/CirculationPolicyRepository.java
- src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
Refactor _PatronNoticeService_ class to encapsulate **notice policy** retrieving.
- use _PatronNoticeEvent_ class for storing all information related to event
- change _PatronNoticeService_ method signature to take _PatronNoticeEvent_ as the parameter 
- retrieve **notice policy** in  _PatronNoticeService_ implementation
https://issues.folio.org/browse/CIRC-269
> CIRC-269 Refactoring PatronNoticeService class

- ramls/request.json
-documented Request.item.enumeration field
> CIRC-270 Add new properties to the item representation on request

- src/main/java/org/folio/circulation/domain/UserRepository.java
- src/main/java/org/folio/circulation/domain/notice/NoticeContextUtil.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/main/java/org/folio/circulation/resources/RequestNoticeAdapter.java
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
- src/test/java/api/support/matchers/PatronNoticeMatcher.java
Resolves: CIRC-262
Implement sending request-related notices (user-initiated events)
https://issues.folio.org/browse/CIRC-262
> CIRC-262 Implement sending request-related notices (user-initiated events)

- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/main/java/org/folio/circulation/support/JsonPropertyFetcher.java
Fix _NullPointerException_ in _LoanPolicy_
Avoid returning null value from JsonPropertyFetcher#getBooleanProperty
> Fix Loan policy NPE

- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/support/builders/ItemBuilder.java
Resolves [CIRC-301](https://issues.folio.org/browse/CIRC-301)
The ability to check out items in either on order or in process status
was already available. These tests demonstrate that and will help prevent
regressions.
> CIRC-301 Tests for checking out on order and in process items

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/LoanRepository.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/org/folio/circulation/domain/validation/InactiveUserValidatorTests.java
Fixes behavior for [CIRC-295](https://issues.folio.org/browse/CIRC-295)
Changing boolean flag to "old due date" value. 
The reason for this change is that there are cases when due date is changed several times, and the last value is the same as value before all changes.
> [CIRC-295] Fix sending recall notice on loan due date changed

- src/main/java/org/folio/circulation/support/CqlQuery.java
- src/test/java/org/folio/circulation/support/CqlQueryTests.java
Resolves: [CIRC-312](https://issues.folio.org/browse/CIRC-312)
Request status is not changed after check-in
> [CIRC-312] Request status is not changed after check-in

- ramls/request.json
@mreno-EBSCO identified a number of issues with the current `request.json` schema
* The "tags" object is under "pickupServicePoint", which can't be correct since. I believe it should be in the "properties" map of the main (request) object.
* The "pickupServicePoint" field should be of type "object".
* Some of these properties might be able to be marked "read-only" and contain "additionalProperties" set to "false", although I seem to recall issues around this property.
During the investigation I noticed a few additional issues.
Some of these changes are strictly breaking changes to the interface.
The `tags` and item properties placement are clearly mistakes and so I believe can be justified as a bug fix.
The rest of the tidy up should not affect the client as it only documents the intent …
> Fix tags and derived properties in request schema CIRC-321

- src/main/java/org/folio/circulation/domain/LoanRepository.java
- src/test/java/api/support/fakes/FakeOkapi.java
> CIRC-335: Handle change due date for the loan issue.

- src/main/java/org/folio/circulation/domain/UserRepository.java
- src/test/java/api/loans/LoanAPITests.java
> CIRC-336: Field 'userId' is the same for different loans - FIXED.

- src/main/java/org/folio/circulation/domain/policy/CirculationPolicyRepository.java
Diagnosing this issue is challenging as the response from the circulation rules does not seem to tally with the lookup of the policy, increasing the logging to try to narrow down the cause.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> Increase logging when determining policy from circulation rules CIRC-359

- src/main/java/org/folio/circulation/domain/LoanRepository.java
- src/main/java/org/folio/circulation/domain/LoanService.java
- src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
https://issues.folio.org/browse/CIRC-305
Fix bug on check out recalled item, dueDate should at the end of the day
> [CIRC-305] Due Time Odd When Checking Out Recalled Item

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/notice/NoticeContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/NoticeEventType.java
- src/main/java/org/folio/circulation/resources/RenewalResource.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/OverrideRenewByBarcodeTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/loans/ScheduledDueDateNoticesProcessingTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/builders/NoticeConfigurationBuilder.java
- src/test/java/api/support/fixtures/NoticeMatchers.java
Resolves: [CIRC-355](https://issues.folio.org/browse/CIRC-355)
Add sending patron notice to renewal process.
> CIRC-355 Send patron notice on renewal

- descriptors/ModuleDescriptor-template.json
Mod-circulation-storage is being upgraded to RAML Module Builder 26. This required some changes to how audit tables work.
Unfortunately, the loan audit table is exposed to clients as the `loan action history` meaning that this required a breaking compatibility change to the `loan-storage` interface
As this aspect of the `loan-storage` interface is not used directly by mod-circulation, dual support for 5.x and 6.0 can be offered.
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.
> Support loan-storage 6.0 interface CIRC-380

- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/test/java/api/loans/OverrideRenewByBarcodeTests.java
Changes in override scenarios
This resolves [CIRC-319](https://issues.folio.org/browse/CIRC-319)
> CIRC-319.1 Fix override scenarios. Renewal behavior for rolling loan policy with due date schedule

- descriptors/ModuleDescriptor-template.json
> Add version 7.0 of `instance-storage` to dependency list CIRC-396

- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/domain/MoveRequestService.java
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/RequestQueue.java
- src/main/java/org/folio/circulation/domain/RequestQueueRepository.java
- src/main/java/org/folio/circulation/domain/RequestServiceUtility.java
- src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
- src/main/java/org/folio/circulation/domain/UpdateUponRequest.java
- src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/test/java/api/requests/scenarios/CancelRequestTests.java
- src/test/java/api/requests/scenarios/MoveRequestTests.java
- src/test/java/api/requests/scenarios/RequestQueueTests.java
- src/test/java/api/support/fakes/FakeOkapi.java
- src/test/java/api/support/fakes/FakeStorageModule.java
- src/test/java/api/support/fakes/FakeStorageModuleBuilder.java
- src/test/java/org/folio/circulation/domain/RequestQueueTests.java
Resolves [CIRC-395](https://issues.folio.org/browse/CIRC-395) [issue](https://issues.folio.org/browse/CIRC-395?focusedCommentId=55779&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-55779) discovered during testing. 
- reordering of actions to move request
- reorder request queue on newly created request
- updating requests in order which avoid duplicate positions in request queue
- additional test for specific scenario of moving two requests from one item to another
- cherry-pick excellent work by @marc-johnson on adding validation to the request test fixture
- update tests
- Does this introduce breaking …
> CIRC-395: resolve request queue positions issue

- descriptors/ModuleDescriptor-template.json
- ramls/check-in-by-barcode-response.json
- ramls/circulation.raml
- ramls/examples/check-in-by-barcode-response.json
- src/main/java/org/folio/circulation/domain/CheckInProcessRecords.java
- src/main/java/org/folio/circulation/domain/notice/NoticeContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledDueDateNoticeHandler.java
- src/main/java/org/folio/circulation/domain/representations/CheckInByBarcodeResponse.java
- src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/RenewalResource.java
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/OverrideRenewByBarcodeTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/loans/ScheduledDueDateNoticesProcessingTests.java
- src/test/java/api/loans/scenarios/InTransitToHomeLocationTests.java
- src/test/java/api/loans/scenarios/ServicePointCheckInTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
- src/test/java/api/support/CheckInByBarcodeResponse.java
- src/test/java/api/support/fixtures/TemplateContextMatchers.java
- src/test/java/api/support/matchers/JsonObjectMatcher.java
Resolves: [CIRC-378](https://issues.folio.org/browse/CIRC-378)
Add staff slips context to check-in response body
> CIRC-378 Add staff slips context to check-in response body

- src/test/java/api/requests/RequestTypeItemStatusWhiteListTests.java
- src/test/java/api/requests/scenarios/MoveRequestPolicyTests.java
- src/test/java/api/requests/scenarios/MoveRequestTests.java
- src/test/java/api/support/builders/MoveRequestBuilder.java
- separated move request tests dealing with policies
- fixed move request from one item copy to another
- created items with different barcodes
- specify items as final
- some minor cleanup
> CIRC-316: fixed sporadic failing test

- src/main/java/org/folio/circulation/domain/RequestQueue.java
- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/main/java/org/folio/circulation/resources/RegularRenewalStrategy.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/requests/RequestsAPILoanRenewalTests.java
- src/test/java/api/support/matchers/FailureMatcher.java
- src/test/java/org/folio/circulation/domain/policy/FixedLoanPolicyRenewalDueDateCalculationTests.java
- src/test/java/org/folio/circulation/domain/policy/InvalidLoanPolicyTests.java
- src/test/java/org/folio/circulation/domain/policy/RollingLoanPolicyRenewalDueDateCalculationTests.java
- src/test/java/org/folio/circulation/domain/policy/UnknownLoanPolicyProfileTests.java
Resolves: [CIRC-384](https://issues.folio.org/browse/CIRC-384)
Add support to display multiple renewal failures
> CIRC-384 Multiple renewal failures: recall-related + other failure reasons

- pom.xml
Get master into https://folio-testing.aws.indexdata.com/
Bump version number to 16.6.0-SNAPSHOT.
Note that v16.5.0 has already been released.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
> CIRC-410: 16.6.0-SNAPSHOT after 16.5.0 release

- src/main/java/org/folio/circulation/domain/LoanRepository.java
- src/main/java/org/folio/circulation/domain/LoanRepresentation.java
1. Mechanism for keeping 'patronGroupIdAtCheckout' to storage if Patron object is empty in user - created.
2. Useless log regarding empty PatronGroup removed.
JIRA ticket: https://issues.folio.org/browse/CIRC-415 …
> CIRC-415: Change due date fails

- CODEOWNERS
> FOLIO-2208 Use Team for codeowners

- src/main/java/org/folio/circulation/domain/LoanRepository.java
**JIRA ticket**: https://issues.folio.org/browse/CIRC-422
The main purpose is **to avoid** alert while changing "due date" if feesFines exists on this loan. 
So, "**_feesAndFines_**" field was removed from **storageLoan** object in LoanRepository before saving it in the storage.
Ideally all of the PRs involved in breaking changes would be merged in the …
> CIRC-422: 'Change due date fails-feesAndFines field not recognized' - Fixed.

- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
Resolves: [CIRC-420](https://issues.folio.org/browse/CIRC-420)
Check in receipt didn't render the checked in date/time value
Rename token for consistency with UI
> CIRC-420 fix issue with check in date token

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/ConfigurationRepository.java
- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/domain/LoanAndRelatedRecords.java
- src/main/java/org/folio/circulation/domain/RequestAndRelatedRecords.java
- src/main/java/org/folio/circulation/domain/UpdateLoan.java
- src/main/java/org/folio/circulation/domain/notice/schedule/DueDateScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/RenewalResource.java
- src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
- src/test/java/api/support/fixtures/ConfigurationExample.java
[CIRC-434](https://issues.folio.org/browse/CIRC-434) was discovered during testing at Chalmers. 
Placing a recall request can trigger an open loan for the item to be truncated depending upon the loans policy. As the new due date will often be set to the end of a day or a closing time, this needs to respect the tenant chosen timezone.
This was not happening as the timezone is not looked up during request creation.
* Write a test replicating the issue (marked as ignored so as to not break the build)
* Separate the fetching of configuration from loan and related records
* Add timezone into the request and related records
* Fetch the timezone during request creation
* Map the timezone from request and related records to loan and related records
* There are likely other places where timezone …
> CIRC-434 fetch timezone when creating request

- src/main/java/org/folio/circulation/domain/ConfigurationRepository.java
- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/domain/LoanAndRelatedRecords.java
- src/main/java/org/folio/circulation/domain/MoveRequestService.java
- src/main/java/org/folio/circulation/domain/notice/schedule/DueDateScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/RenewalResource.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/main/java/org/folio/circulation/support/Result.java
- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
- src/test/java/api/requests/scenarios/MoveRequestTests.java
- src/test/java/api/support/fixtures/ItemsFixture.java
- src/test/java/org/folio/circulation/support/results/ResultCombineAfterTests.java
[CIRC-443](https://issues.folio.org/browse/CIRC-443) was discovered during testing at Chalmers. 
Moving a recall request can trigger an open loan for the destination item to be truncated depending upon the loans policy. As the new due date will often be set to the end of a day or a closing time, this needs to respect the tenant chosen timezone.
This was not happening as the timezone is not looked up whilst moving a request.
* Write a test replicating the issue (marked as ignored so as to not break the build)
* Fetch the timezone whilst moving a request
* The configuration repository needs to be changed to not depend upon loan and related records. In order to make this nicer, investigate an overload of Result.combineAfter that takes a supplier instead of a function
* I think we need to …
> CIRC-443 fetch timezone when moving request

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/LoanService.java
- src/main/java/org/folio/circulation/domain/UpdateLoan.java
- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/main/java/org/folio/circulation/support/JsonPropertyWriter.java
- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
- src/test/java/api/requests/scenarios/MoveRequestTests.java
- src/test/java/api/support/fakes/StorageSchema.java
- src/test/resources/storage-loan-6-2.json
The loan due date should only be changed once due to a recall. Subsequent recalls should not modify the due date. We will now set and respect the `dueDateChangedByRecall` flag. It will be set on a recall, if it has not already been set, and when it comes time to apply recall logic to update the loan, if this flag is set, we no longer perform the recall logic.
This fix also has changed an expectation of CIRC-289 (moving recall requests) and the unit test was updated to reflect the new expected outcome.
- What other modules …
> CIRC-440: prevent multiple recalls from changing the loan due date

- doc/circulationrules.md
priority last-line/first-line
See implementation:
https://github.com/folio-org/mod-circulation/blob/v16.6.0/src/main/antlr4/org/folio/circulation/rules/CirculationRules.g4#L92-L119
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.
> Fix fallback-policy positioning documentation

- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/test/java/api/loans/scenarios/ServicePointCheckInTests.java
To add "lastCheckedInDateTime" token for staff slips
Resolves story: [CIRC-428](https://issues.folio.org/browse/CIRC-428)
- add "lastCheckedInDateTime" https://issues.folio.org/browse/CIRC-428
- update test
> [CIRC-428] Add "lastCheckedInDateTime" token

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/AddressType.java
- src/main/java/org/folio/circulation/domain/AddressTypeRepository.java
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/RequestRepresentation.java
- src/main/java/org/folio/circulation/domain/User.java
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/main/java/org/folio/circulation/support/Clients.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/support/builders/Address.java
- src/test/java/api/support/fixtures/AddressExamples.java
- src/test/java/api/support/fixtures/AddressTypesFixture.java
Jira: CIRC-454
Load address type during check in by barcode
Add delivery slip tokens related to address
Add slip tokens to support "delivery" fullfilment type
Copy token values from requester, 
fetch AddressType from mod-users and add it as token
> CIRC-454: Add address tokens to staffSlipContext

- descriptors/ModuleDescriptor-template.json
- src/test/java/api/loans/scenarios/CheckoutWithRequestScenarioTests.java
- src/test/java/api/support/fakes/FakeOkapi.java
- src/test/java/api/support/fakes/StorageSchema.java
- src/test/java/api/support/fixtures/LocationsFixture.java
- src/test/resources/loccamp.json
- src/test/resources/locinst.json
- src/test/resources/loclib.json
"location-units" version bumped to '2.0'
While it's helpful for reviewers to help …
> CIRC-474: Fix the impact of the API change as per MODINVSTOR-315 for mod-circulation.

- descriptors/ModuleDescriptor-template.json
Required by https://github.com/folio-org/mod-inventory-storage/pull/338
While it's …
> CIRC-466, MODINVSTOR-364: Update holdings-storage API version to 4.0

- src/main/java/org/folio/circulation/domain/HoldShelfClearanceRequestContext.java
- src/main/java/org/folio/circulation/resources/RequestHoldShelfClearanceResource.java
- src/test/java/api/requests/HoldShelfClearanceReportTests.java
Fix bug in the hold shelf clearance report
Resolve: [CIRC-516](https://issues.folio.org/browse/CIRC-516)
> CIRC-516 Item not cleared of Hold shelf clearance report after check in

- src/main/java/org/folio/circulation/resources/RequestHoldShelfClearanceResource.java
- src/test/java/api/requests/HoldShelfClearanceReportTests.java
The purpose of this PR is to fix Hold Shelf Clearance report and update test cases to reproduce scenario outlined in user story.
Only one "Awaiting pickup" request returned due to limit=1. Fixed limit in query. …
> [CIRC-516] Item reappears on Hold shelf clearance when it goes into Awaiting pickup for another SP

- doc/circulationrules.md
The location hierarchy (a, b, c, s) has been implemented in the circulation rules:
* institution https://issues.folio.org/browse/CIRC-405
* campus https://issues.folio.org/browse/CIRC-413
* library https://issues.folio.org/browse/CIRC-414
The circulation rules documentation needs to be updated accordingly.
> CIRC-405: Update doc that location hierarchy has been implemented.

- Jenkinsfile
Fixes typo in Jenkinsfile to activate kubernetes deployment stage in pipeline (deploys latest snapshot and release builds to CI kubernetes cluster. This is a perquisite for PR preview).
> fix misconfiguration for k8s CI in Jenkinsfile

- src/main/java/org/folio/circulation/resources/RequestHoldShelfClearanceResource.java
The purpose of this change is to remove redundant constant is Hold Shelf expiration report logic …
> Hold shelf expiration report, remove constant

- descriptors/ModuleDescriptor-template.json
A new status code has been added to the module for the `/calendar/periods/{servicePointId} /period/{periodId}` endpoint.
Resolve: [MODCAL-57](https://issues.folio.org/browse/MODCAL-57)
Raising the mod-calendar version in the descriptor.
> Breaking change API mod-calendar MODCAL-57

- descriptors/ModuleDescriptor-template.json
The purpose of this change is to remove unnecessary circle permission
While it's helpful …
> CIRC-529 remove circle perm dependency

- src/main/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteList.java
- src/test/java/api/requests/RequestTypeItemStatusWhiteListTests.java
Configure which types of requests are allowed or disallowed when item status = Awaiting delivery
Resolves: [CIRC-511](https://issues.folio.org/browse/CIRC-511)
Update white list of allowed request types for item in status = Awaiting delivery with:
- Hold;
- Recall 
> CIRC-511  Update request whitelist to handle new "Awaiting delivery" status

- descriptors/ModuleDescriptor-template.json
- ramls/examples/items-in-transit.json
- ramls/inventory-reports.raml
- ramls/items-in-transit.json
- src/main/java/org/folio/circulation/domain/representations/ItemReportRepresentation.java
- src/main/java/org/folio/circulation/resources/ItemsInTransitResource.java
- src/main/java/org/folio/circulation/support/JsonStringArrayHelper.java
- src/test/java/api/requests/ItemsInTransitReportTests.java
- src/test/java/api/support/builders/ItemBuilder.java
- src/test/java/api/support/fixtures/ItemExamples.java
Implement in transit report: call number, enumeration, volume and year fields from an item
Resolves: [CIRC-520](https://issues.folio.org/browse/CIRC-520)
- Get call number, enumeration, volume and year fields from an item
- Sort by check in service point
> CIRC-520 BE: In transit report:  enumeration, volume and year fields from an item; sort by check in service point

- src/main/java/org/folio/circulation/domain/representations/ItemReportRepresentation.java
- src/test/java/api/requests/ItemsInTransitReportTests.java
Blocked patron can successfully place a request
Resolves [CIRC-476](https://issues.folio.org/browse/CIRC-476)
- add validation if manual blocks exist;
[CIRC-476](https://issues.folio.org/browse/CIRC-476)
> CIRC-569 BE: In transit report: the export contains the name of the requesting patron, and not the patron group.

- src/main/java/org/folio/circulation/domain/notice/session/ExpiredSession.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionRepository.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionType.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronExpiredSessionRepository.java
- src/main/java/org/folio/circulation/resources/ExpiredSessionProcessingResource.java
- src/test/java/api/loans/EndExpiredPatronActionSessionTests.java
Modify CHECK-OUT processor to support CHECK-IN end expired sessions
Resolves [CIRC-560](https://issues.folio.org/browse/CIRC-560)
- modify CHECK-OUT processor to support CHECK-IN end expired sessions;
[CIRC-560](https://issues.folio.org/browse/CIRC-560)
> CIRC-560 Modify CHECK-OUT processor to support CHECK-IN end expired sessions

- src/test/java/api/requests/ItemsInTransitReportTests.java
The item in transit report tests use a `map of strings` instead of `JsonObject` to interact with the responses from API requests.
This causes failures when using stricter evaluation, e.g. JVM 13, as it is not possible to implicitly convert an array or boolean into a string. I don't know why this is allowed on JVM 1.8
Replace the checks that uses maps with JsonObject, changing the matchers to be more type safe in the process.
- Are …
> CIRC-595 Use JSON object for in transit items report checks

- src/test/java/org/folio/circulation/domain/policy/FixedLoanPolicyRenewalDueDateCalculationTests.java
- src/test/java/org/folio/circulation/domain/policy/RollingLoanPolicyCheckOutDueDateCalculationTests.java
Two loan policy due date calculation tests started failing due to being close to the end of the year and using now as the system time.
* Used a fixed date time for the system time
* Cleaned up the assertions to compare date time rather than milliseconds from epoch
Tests should not rely on now, as it tends to make them unstable around year, month or daylight savings transitions
- Do PRs …
> CIRC-601 Fix tests that broke due to being less than 2 weeks before the end of the year

- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/CheckOutCalculateDueDateTests.java
- src/test/java/api/support/APITestContext.java
- src/test/java/api/support/fixtures/LoanPoliciesFixture.java
Some tests have been failed because they were relaying on a sample due date schedule, that had hardcoded 2019 year. …
> CIRC-609 - Fix failed tests because of use 2019 year for sample fixed schedules

- src/test/java/api/CirculationRulesAPITests.java
- src/test/java/api/CirculationRulesEngineAPITests.java
- src/test/java/api/support/APITestContext.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/RestAssuredClient.java
- src/test/java/api/support/RestAssuredConfiguration.java
- src/test/java/api/support/RestAssuredResponseConversion.java
- src/test/java/api/support/fixtures/CirculationRulesFixture.java
- src/test/java/api/support/http/api/support/NamedQueryStringParameter.java
In order to reduce the coupling and reuse between the API tests and the main code, we can start to replace the use of OkapiHttpClient with RestAssured.
This reduces the chances that tests are affected by unintentional changes in the production code. Hopefully it also reduces the amount of code and improves the readability of the tests.
This also reduces the dependency upon vert.x 3.x HttpClient (some of the methods used in mod-circulation are deprecated), which helps with the eventual migration to vert.x 4.0. Eventually, the remaining production usage will be replaced with the WebClient.
This is the fourth in a series of pull requests. This focuses on the circulation rules API tests as they required specific involved work to migrate them to Rest Assured.
In particular, they relied on …
> CIRC-596 migrate circulation rules tests

- descriptors/ModuleDescriptor-template.json
Another permission is missing from the move requests API endpoint
While it's helpful for …
> Grant calendar permission when moving requests CIRC-308

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/domain/notice/schedule/DueDateNotRealTimeScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/DueDateScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/RequestScheduledNoticeService.java
- src/main/java/org/folio/circulation/support/AsyncCoordinationUtil.java
- src/main/java/org/folio/circulation/support/RecordNotFoundFailure.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/CheckOutCalculateDueDateTests.java
- src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java
- src/test/java/api/loans/DueDateScheduledNoticesProcessingTests.java
- src/test/java/api/requests/RequestScheduledNoticesTests.java
- src/test/java/api/support/APITestContext.java
- src/test/java/api/support/fixtures/LoanPoliciesFixture.java
Release priority bug fixes for 2019 Q4
* Cherry pick changes from bug fix pull requests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> Release 17.0.2

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/notice/schedule/DueDateNotRealTimeScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/DueDateScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/support/AsyncCoordinationUtil.java
- src/main/java/org/folio/circulation/support/RecordNotFoundFailure.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/CheckOutCalculateDueDateTests.java
- src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java
- src/test/java/api/loans/DueDateScheduledNoticesProcessingTests.java
- src/test/java/api/requests/RequestScheduledNoticesProcessingTests.java
- src/test/java/api/support/APITestContext.java
- src/test/java/api/support/fixtures/LoanPoliciesFixture.java
- src/test/java/api/support/fixtures/TemplateContextMatchers.java
v16.7 with cherry-picked bugfix for [CIRC-582](https://issues.folio.org/browse/CIRC-582)
> v16.7.6 bugfix release

- src/main/java/org/folio/circulation/domain/RequestRepository.java
- src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledNoticesRepository.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionRepository.java
- src/main/java/org/folio/circulation/support/CollectionResourceClient.java
- src/main/java/org/folio/circulation/support/http/client/OkapiHttpClient.java
- src/main/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClient.java
- src/test/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClientTests.java
In order to prepare for the imminent release of vert.x 4.0, mod-circulation needs to migrate it's client to use the Vert.x web client because this allows for making requests using an absolute URL.
The methods for making requests using an absolute URL were deprecated in the existing vert.x HTTP client.
* Introduce a new client based upon vert.x web client
* add methods for each HTTP method in turn
* migrating use to the new client incrementally
* Finally, remove the old client
Each HTTP method is introduced in the new client and migrated in a separate pull request (to try to keep them a bit smaller).
* Replace `post` requests
* Replace `put` requests
* Remove the old client (and introduce a new interface)
* It would've been nicer to change the existing interface to better fit what was …
> CIRC-308 use web client for delete requests

- src/main/java/org/folio/circulation/domain/AnonymizeStorageLoansRepository.java
- src/main/java/org/folio/circulation/domain/LoanRepository.java
- src/main/java/org/folio/circulation/domain/RequestRepository.java
- src/main/java/org/folio/circulation/domain/notice/PatronNoticeService.java
- src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledNoticesRepository.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionRepository.java
- src/main/java/org/folio/circulation/support/CollectionResourceClient.java
- src/main/java/org/folio/circulation/support/http/client/OkapiHttpClient.java
- src/main/java/org/folio/circulation/support/http/client/ResponseInterpreter.java
- src/main/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClient.java
- src/test/java/org/folio/circulation/domain/UpdateRequestQueueTest.java
- src/test/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClientTests.java
In order to prepare for the imminent release of vert.x 4.0, mod-circulation needs to migrate it's client to use the Vert.x web client because this allows for making requests using an absolute URL.
The methods for making requests using an absolute URL were deprecated in the existing vert.x HTTP client.
This pull request is part of a series of changes, and replaces the existing `post` methods.
* Introduce a new client based upon vert.x web client
* add methods for each HTTP method in turn
* Use types for representing common query parameters
* migrating use to the new client incrementally
* Finally, remove the old client
Each HTTP method is introduced in the new client and migrated in a separate pull request (to try to keep them a bit smaller).
* Replace `put` requests
* Remove the old …
> CIRC-308 use web client for post

- pom.xml
- src/main/java/org/folio/circulation/CirculationVerticle.java
- src/main/java/org/folio/circulation/support/logging/LogMessageSanitizer.java
- src/test/java/api/support/builders/InstanceBuilder.java
- src/test/java/api/support/builders/ItemBuilder.java
- src/test/java/api/support/builders/JsonBuilder.java
- src/test/java/api/support/builders/NoticePolicyBuilder.java
- src/test/java/api/support/builders/RequestPolicyBuilder.java
- src/test/java/api/support/fakes/FakeOkapi.java
- src/test/java/api/support/fakes/FakeStorageModule.java
- src/test/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClientTests.java
- src/test/java/org/folio/circulation/support/logging/LogMessageSanitizerTests.java
In order to prepare for the imminent release of vert.x 4.0, mod-circulation needs to migrate it's client to use the Vert.x web client because this allows for making requests using an absolute URL.
The methods for making requests using an absolute URL were deprecated in the existing vert.x HTTP client.
This pull request is part of a series of changes, and upgrades the .
* Introduce a new client based upon vert.x web client
* add methods for each HTTP method in turn
* Use types for representing common query parameters
* migrating use to the new client incrementally
* Remove the old client 
* Upgrade vert.x to 3.8.4 in preparation for 4.0.0
There are a number of subtle breaking changes to behaviour in between 3.7.0 and 3.8.4
* Asterix paths no long include the root path
* JSON array …
> CIRC-308 Upgrade Vertx to 3.8.4

- pom.xml
This upgrade is intended to resolve 
* https://github.com/advisories/GHSA-gjmw-vf9h-g25v
* https://github.com/advisories/GHSA-fmmc-742q-jg75
* https://github.com/advisories/GHSA-mx7p-6679-8g3q
* https://github.com/advisories/GHSA-h822-r4r5-v8jg
* https://github.com/advisories/GHSA-85cw-hj65-qqv9
Ideally all of the PRs involved in breaking changes would …
> CIRC-633 Upgrade Jackson Databind to 2.9.10.1 

- pom.xml
- src/main/resources/log4j.properties
- src/main/resources/log4j2.properties
- src/test/java/api/support/fakes/FakeCQLToJSONInterpreter.java
- src/test/java/api/support/fakes/FakeStorageModule.java
- src/test/java/org/folio/circulation/FakeCQLToJSONInterpreterSearchingTests.java
- src/test/java/org/folio/circulation/FakeCQLToJSONInterpreterSortingTests.java
A [vulnerability](https://issues.folio.org/browse/CIRC-635) has been identified with log4j and It appears that this won't be patched.
As an alternative log4j has been replaced with log4j2
* Based upon recent work in Okapi to do a similar migration
* Removes direct system.out usage in test fakes
* Could asynchronous logging improve performance
Ideally all …
> CIRC-635 use log4j core

- src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
- src/test/java/api/loans/scenarios/ChangeDueDateTests.java
Declared lost item: Prevent change due date
Resolves: [CIRC-625](https://issues.folio.org/browse/CIRC-625)
- add validation if an item has `declared lost item` status during change due date;
> CIRC-625 Declared lost item: Prevent change due date

- src/main/java/org/folio/circulation/domain/validation/ItemLimitValidator.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
Fix issue with filtering opened loans by material type and loan type
[CIRC-558](https://issues.folio.org/browse/CIRC-558)
> CIRC-558 fix issue with counting opened loans

- src/main/java/org/folio/circulation/domain/validation/ItemLimitValidator.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
Resolves [CIRC-558](https://issues.folio.org/browse/CIRC-558)
Update error message according to the changes of requirements.
> CIRC-558 update error message

- descriptors/ModuleDescriptor-template.json
- ramls/check-in-by-barcode-request.json
- ramls/circulation.raml
- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/LoanAction.java
- src/main/java/org/folio/circulation/domain/LoanCheckInService.java
- src/main/java/org/folio/circulation/domain/representations/CheckInByBarcodeRequest.java
- src/main/java/org/folio/circulation/domain/validation/CheckInValidators.java
- src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/ClaimItemReturnedAPITests.java
- src/test/java/api/support/builders/CheckInByBarcodeRequestBuilder.java
- src/test/java/api/support/builders/ClaimItemReturnedRequestBuilder.java
- src/test/java/api/support/fixtures/LoansFixture.java
https://issues.folio.org/browse/CIRC-660 - Claimed returned: check in item
- Add new `claimedReturnedResolvedBy` enum property for check-in-by-barcode API;
- Add validators;
- Introduce new loan actions:
- `checkedInFoundByLibrary`;
- `checkedInReturnedByPatron`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> CIRC-660: Resolve claimed returned item status via check-in

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/CheckInRecord.java
- src/main/java/org/folio/circulation/services/LogCheckInService.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/InHouseUseCheckInTest.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/fakes/StorageSchema.java
- src/test/java/org/folio/circulation/services/LogCheckInServiceTest.java
- src/test/resources/check-in-storage-0-2.json
https://issues.folio.org/browse/CIRC-665: Record additional properties for each check-in
Following additional properties have to be recorded during each check-in in order to record in-house use of an item:
- item status;
- Request queue size for item;
- Effective location for item.
Ideally all of the PRs involved in breaking changes would be merged in …
> CIRC-665: Record in house use data for each check-in.

- src/main/java/org/folio/circulation/domain/FeeFineRepository.java
- src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/builders/FeeFineBuilder.java
- src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
Remove automatic creation fee/fine types during check-in process - they will be created as predefined data during `mod-feesfines` initialization (see [MODFEE-28](https://issues.folio.org/browse/MODFEE-28)).
This resolves [CIRC-656](https://issues.folio.org/browse/CIRC-656).
- remove automatic creation of fee/fine types from check-in process
- if type is not found - no fine ("account") should be created
- Are the JIRAs under active …
> [CIRC-656] do not create overdue fine automatically

- src/main/java/org/folio/circulation/domain/LoanRepository.java
- src/main/java/org/folio/circulation/domain/anonymization/service/LoansForTenantFinder.java
- src/main/java/org/folio/circulation/support/http/client/CqlQuery.java
- src/test/java/api/loans/anonymization/AnonymizeLoansAfterXIntervalTests.java
- src/test/java/api/loans/anonymization/LoanAnonymizationTests.java
- src/test/java/api/support/fakes/FakeCQLToJSONInterpreter.java
- src/test/java/api/support/fakes/FakeLoanAnonymizationResource.java
- src/test/java/api/support/fakes/FakeOkapi.java
- src/test/java/api/support/http/InterfaceUrls.java
https://issues.folio.org/browse/CIRC-666: Poor Performance of mod-circulation Edelweiss
* Do not fetch already anonymized loans
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> CIRC-666: Do not anonymize already anonymized loans.

- src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
- src/main/java/org/folio/circulation/domain/OverduePeriodCalculatorService.java
- src/test/java/org/folio/circulation/domain/OverduePeriodCalculatorServiceTest.java
This pull request fixes [CIRC-682](https://issues.folio.org/browse/CIRC-682)
Change behavior related to grace period in OverduePeriodCalculatorService and extend its unit tests.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> CIRC-682 Handle grace period correctly when overdue fine is charged

- src/main/java/org/folio/circulation/domain/representations/AccountStorageRepresentation.java
- src/test/java/api/support/matchers/OverdueFineMatcher.java
- src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
Currently automatic fees/fines ("accounts") are created without `materialType` field, unlike manual fees/fines. This pull request aims to fix this issue.
Map item's material type to newly created overdue fines. …
> [CIRC-685] Add materialType field for Automated Fee/fines

- src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
Fixes [CIRC-686](https://issues.folio.org/browse/CIRC-686). Also, additional renewal scenarios are added to `OverdueFineCalculatorServiceTest`.
Unit tests (`OverdueFineCalculatorServiceTest`) failed from time to time during Jenkins builds. At the same time, it couldn't be reproduced on local machine.
Investigation showed that sometimes `Loan.isOverdue()` method returns wrong results which causes fee/fine calculation process to exit too early. The root cause of this is still unclear, but it's probably related to `ClockManager` class and the fact that Jenkins is running on servers with UTC timezone. To fix this, instead of calling `isOverdue()` we're now calling `isOverdue(DateTime.now(DateTimeZone.UTC))` to avoid usage of ClockManager. This approach seems to help - more than 40 Jenkins …
> CIRC-686 fix unit tests

- src/main/java/org/folio/circulation/domain/LoanRepository.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/http/CqlQuery.java
https://issues.folio.org/browse/CIRC-699 - Bugfest: 500 Error when filtering Requests by Type = Page
Use `FindWithMultipleCqlIndexValues` to fetch open loans for items, when fetching multiple requests in order to omit `414 Uri too long` error.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> CIRC-699: use partition to fetch loans to release.

- src/main/java/org/folio/circulation/domain/FeeFineOwnerRepository.java
- src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
- src/main/java/org/folio/circulation/support/http/client/CqlQuery.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/matchers/OverdueFineMatcher.java
- src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
Overdue fines are not assigned to any particular owner by default. To determine the owner of a newly created overdue fine, we look for the owner of the service point which item's effective location belongs to. To do that we currently fetch all owners and then filter them by owned service point. Since the current page limit for fetching owners is 10, it ocasionally causes problems when the number of existing owners exceeds this limit.
Filter owners by the service point on DB side, which by defintion should return 1 owner max. …
> [CIRC-702] Find an owner for service point on DB side

- src/main/java/org/folio/circulation/domain/representations/AccountStorageRepresentation.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/support/matchers/OverdueFineMatcher.java
- src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
Fixes [CIRC-694](https://issues.folio.org/browse/CIRC-694).
Returned Date and Due Date didn't appear on the Fee/Fine details page as well as patron Fees/Fines page.
Add `dueDate` and `returnedDate` to `AccountStorageRepresentation`, change tests accordingly.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> CIRC-694 Returned Date and Due Date on Fee/Fine Details page

- src/main/java/org/folio/circulation/domain/FeeFineOwnerRepository.java
- src/main/java/org/folio/circulation/support/http/client/CqlQuery.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/org/folio/circulation/support/http/client/CqlQueryTests.java
Fix overdue fine creation logic.
Resolves [CIRC-702](https://issues.folio.org/browse/CIRC-702).
Increase page limit for fetching fee/fine owners to 200 (the number is suggested by PO). 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
> [CIRC-702] Overdue fines not calculating for any overdue items

- descriptors/ModuleDescriptor-template.json
Add missing permissions to allow for proper functionality.
Resolves: [CIRC-700](https://issues.folio.org/browse/CIRC-700)
Added `overdue-fines-policies.item.get` and `lost-item-fees-policies.item.get`. …
> [CIRC 700] (B18.0) Can't check out items with check out permissions

- src/main/java/org/folio/circulation/domain/FeeFineOwnerRepository.java
- src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
- src/main/java/org/folio/circulation/domain/UpdateLoan.java
- src/main/java/org/folio/circulation/domain/representations/AccountStorageRepresentation.java
- src/main/java/org/folio/circulation/support/http/client/CqlQuery.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/matchers/OverdueFineMatcher.java
- src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
- src/test/java/org/folio/circulation/support/http/client/CqlQueryTests.java
This PR contains bugfixes for release 18.0.3:
- Increases page limit for fetching fee/fine owners ([CIRC-702](https://issues.folio.org/browse/CIRC-702))
- Adds due date and returned date to "Fee/Fine Details" page ([CIRC-694](https://issues.folio.org/browse/CIRC-694)) …
> Bugfixes for 18.0.3

- src/main/java/org/folio/circulation/resources/CirculationRulesResource.java
- src/main/java/org/folio/circulation/support/CollectionResourceClient.java
Fix issue with validation error for existing policies
Resolves: [CIRC-705](https://issues.folio.org/browse/CIRC-705)
> CIRC-705 fix limit issue for policies

- src/main/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClient.java
Extend the timeout for HTTP requests to 20 seconds because slow responses are causing errors in hosted environments.
This is a temporary workaround, and the slow requests should be investigated and addressed where possible.
* Parameter to define the default timeout
* Be able to define a default externally e.g. with an environment variable or configuration entry
- Do PRs exist for these …
> CIRC-709 extend http request timeout to 20 seconds

- src/main/java/org/folio/circulation/domain/representations/AccountStorageRepresentation.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/support/matchers/OverdueFineMatcher.java
- src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
Resolves CIRC-698.
While it's helpful for reviewers to help identify potential problems, …
> CIRC-698 Overdue fine location name instead of id

- src/main/java/org/folio/circulation/domain/OverduePeriodCalculatorService.java
Change service point for calendar using in calculation minutes for overdue fines.  According to the requirements it should be the service point hours for the primary service point of the effective location of the item.
Resolves [CIRC-736](https://issues.folio.org/browse/CIRC-736)
> CIRC-736 update service point for using calendar

- src/main/java/org/folio/circulation/domain/OverduePeriodCalculatorService.java
[CIRC-736](https://issues.folio.org/browse/CIRC-736)  should be a hot fix for Q1 2020
> Release 18.0.9

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/ItemStatus.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/support/builders/ItemBuilder.java
- src/test/java/api/support/fakes/StorageSchema.java
- src/test/resources/item-storage-8-4.json
https://issues.folio.org/browse/CIRC-746 - BE: Check in: lost and paid items
* Verify that lost and paid item can be checked in;
* Use `item-storage:8.4`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
> CIRC-746: Verify that lost and paid item can be checked in.

- src/main/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteList.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteListTests.java
https://issues.folio.org/browse/CIRC-748 - BE: Lost and paid: prevent all request types.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> CIRC-748: Disallow all requests for lost and paid items.

- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/support/matchers/ItemMatchers.java
https://issues.folio.org/browse/CIRC-747 - BE: Check out Lost and paid item
While it's …
> CIRC-747: Verify that lost and paid item can be checked out.

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/CirculationVerticle.java
- src/main/java/org/folio/circulation/domain/EventType.java
- src/main/java/org/folio/circulation/resources/TenantActivationResource.java
- src/main/java/org/folio/circulation/services/ModulePubSubUnregisteringException.java
- src/main/java/org/folio/circulation/services/PubSubRegistrationService.java
- src/main/java/org/folio/circulation/support/http/server/WebContext.java
- src/main/resources/MessagingDescriptor.json
- src/test/java/api/CirculationRulesAPITests.java
- src/test/java/api/TenantActivationResourceTests.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/CheckOutCalculateDueDateTests.java
- src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
- src/test/java/api/loans/scenarios/ChangeDueDateByReplacingLoanTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
- src/test/java/api/requests/scenarios/HoldShelfExpirationDateTests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/RestAssuredClient.java
- src/test/java/api/support/fakes/FakeOkapi.java
- src/test/java/api/support/fakes/FakePubSub.java
- src/test/java/api/support/fixtures/TenantActivationFixture.java
- src/test/java/api/support/matchers/EventTypeMatchers.java
- src/test/java/api/support/matchers/PubSubRegistrationMatchers.java
- src/test/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClientTests.java
Split from https://github.com/folio-org/mod-circulation/pull/556
While it's helpful for …
> CIRC-734: Splitting out pub/sub registration from main logic.

- pom.xml
- src/main/java/org/folio/circulation/domain/LoanRepository.java
- src/main/java/org/folio/circulation/domain/representations/LoanProperties.java
- src/main/java/org/folio/circulation/domain/representations/StoredFeeFineAction.java
- src/main/java/org/folio/circulation/services/FeeFineFacade.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
- src/main/java/org/folio/circulation/services/feefine/FeeRefundProcessor.java
- src/main/java/org/folio/circulation/support/utils/CollectionUtil.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
- src/test/java/api/support/matchers/AccountActionsMatchers.java
- src/test/java/api/support/matchers/AccountMatchers.java
- src/test/java/api/support/matchers/LoanAccountActionsMatcher.java
- src/test/java/api/support/matchers/LoanAccountMatcher.java
https://issues.folio.org/browse/CIRC-765 - BE: Refund lost item fees for 'Lost and paid' items
* Assigned lost item fees for `Lost and paid` item has to be refunded on check-in similar to `Declared lost` items;
* But these `Lost and paid` items has no open loan associated anymore at the moment of check in.
* Retrieve last associated loan for such items using following CQL `itemId==<the-item-id> sortBy loanDate/sort.descending, limit=1`;
* Return an error message if no loan found;
* Return an error message if the loan has no `declaredLostDate` property associated (means it is declared lost);
* Populate `actionDate` property as `now() + n milliseconds` for refund fee/fine actions in order to keep historical order for them (ISO timestamp is the same for all of them, because they are created …
> CIRC-765: Refund lost item fees for 'Lost and paid' items.

- src/main/java/org/folio/circulation/domain/CheckInProcessRecords.java
- src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
- src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
See comment under [CIRC-717](https://issues.folio.org/browse/CIRC-717?focusedCommentId=78670&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-78670)
> If a patron has been billed a lost item fee/fine and/or lost item processing fee (whether they paid or not, which means Item Status can be "Declared lost" or "Lost and paid") and the Lost Item Fee Policy setting "No fees/fines shall be refunded if a lost item is returned more than X <intervals> late" has been surpassed, then an overdue fine should NOT be calculated. The patron will not be refunded the lost item fees they have been billed or have paid, so we should NOT also charge them overdue fines. 
* Store result of refund/cancellation of lost item fees in `CheckInProcessRecords` shared object so then …
> CIRC-717: Do not assign overdue fine if lost item fees were not refunded

- pom.xml
> Change next version to 19.0.0 CIRC-753 CIRC-465

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/PickSlipsResource.java
- src/test/java/api/requests/PickSlipsTests.java
Purpose: include [CIRC-768](https://issues.folio.org/browse/CIRC-768) into Q2-2020/Goldenrod release.
Resolves [CIRC-776](https://issues.folio.org/browse/CIRC-776).
> Bugfix release 19.0.1

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/domain/UserRepository.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionRepository.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionService.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronExpiredSessionRepository.java
- src/main/java/org/folio/circulation/resources/ExpiredSessionProcessingResource.java
- src/main/java/org/folio/circulation/resources/PickSlipsResource.java
- src/test/java/api/loans/EndExpiredPatronActionSessionTests.java
- src/test/java/api/requests/PickSlipsTests.java
Purpose: include [CIRC-760](https://issues.folio.org/browse/CIRC-760) and [CIRC-768](https://issues.folio.org/browse/CIRC-768) into Q1-2020/Fameflower release.
Resolves [CIRC-777](https://issues.folio.org/browse/CIRC-777).
> Hotfix release 18.0.11

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/CIRC-807 - Bugfest: Failure to change due date when item is recalled …
> CIRC-807: Add missing permissions for change due date with request case.

- descriptors/ModuleDescriptor-template.json
See [CIRC-806](https://issues.folio.org/browse/CIRC-806)
* Add missing permission
While …
> Allow an overridden check out to publish messages to pub-sub CIRC-806

- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionRepository.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionService.java
- src/main/java/org/folio/circulation/resources/ExpiredSessionProcessingResource.java
- src/test/java/api/loans/EndExpiredPatronActionSessionTests.java
- fix issue with removing expired sessions which have nonexistent loanId or patronId;
- add tests;
Resolves: [CIRC-815](https://issues.folio.org/browse/CIRC-815) 
> CIRC-815 fix issue with removing expired sessions

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/resources/DeclareLostResource.java
- src/test/java/api/loans/DeclareLostAPITests.java
https://issues.folio.org/browse/CIRC-792
While it's helpful for reviewers to help …
> CIRC-792: [BUGFIX] Do not allow declaring item lost if it is already lost. 

- src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
- src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
Resolves [CIRC-816](https://issues.folio.org/browse/CIRC-816).
Fee/fine action's "Created At" field should contain check-in service point's name instead of a fee/fine owner name.
Additional call is made to fetch service points related to a loan. No new permissions needed - both check-in and renew endpoint already have inventory-storage.service-points.item.get.
- Do PRs exist for these …
> CIRC-816 Overdue fine action record does not include Service Point as Created at

- NEWS.md
- pom.xml
Origin changes:
https://github.com/folio-org/mod-circulation/pull/594
https://github.com/folio-org/mod-circulation/pull/580
Jira:
https://issues.folio.org/browse/CIRC-827
https://issues.folio.org/browse/CIRC-796 …
> [CIRC-827,  CIRC-796]: Fix security issues upgrade to vert.x and RMB

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/resources/RenewalValidator.java
- src/test/java/api/loans/OverrideRenewByBarcodeTests.java
Includes:
* https://github.com/folio-org/mod-circulation/pull/588
* https://github.com/folio-org/mod-circulation/pull/590
* https://github.com/folio-org/mod-circulation/pull/584
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> Bug/fix release 19.0.6

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
- src/main/java/org/folio/circulation/domain/notice/schedule/JsonScheduledNoticeMapper.java
- src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledNoticesRepository.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionRepository.java
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionService.java
- src/main/java/org/folio/circulation/resources/ExpiredSessionProcessingResource.java
- src/test/java/api/loans/DueDateScheduledNoticesTests.java
- src/test/java/api/loans/EndExpiredPatronActionSessionTests.java
- src/test/java/api/support/fixtures/FeeFineOwnerFixture.java
- src/test/java/api/support/fixtures/FeeFineTypeFixture.java
- src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
> Bugfix release 19.0.7

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/CIRC-803
While it's helpful for reviewers to help …
> CIRC-803: Add permission for scheduled-anonymize-processing endpoint.

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Includes #602
While it's helpful for reviewers to help identify potential problems, …
> 19.0.8 release

- src/main/java/org/folio/circulation/resources/RequestHoldShelfClearanceResource.java
https://issues.folio.org/browse/CIRC-817
Remove `CompletableFuture#join` call.
While …
> CIRC-817: Remove blocking code.

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/RequestHoldShelfClearanceResource.java
Releases https://github.com/folio-org/mod-circulation/pull/604
While it's helpful for …
> CIRC-817: release 

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/CIRC-853 - Missing module permission for placing instance holds …
> CIRC-836: Add missing permissions for instance level requests endpoint.

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/CIRC-853 - Missing module permission for cancelling request …
> CIRC-853: Add missing permissions for cancel request endpoint.

- src/main/java/org/folio/circulation/domain/representations/ItemSummaryRepresentation.java
- src/test/java/api/loans/LoanAPITests.java
Add item copy number to loan representation so that it could be used for loan exports and for fee/fine history and details pages.
Resolves [CIRC-861](https://issues.folio.org/browse/CIRC-861).
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> [CIRC-861] Add item copy number to loan representation

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/ItemStatus.java
- src/main/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteList.java
- src/main/java/org/folio/circulation/domain/validation/ItemStatusValidator.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/builders/ItemBuilder.java
- src/test/java/api/support/fakes/StorageSchema.java
- src/test/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteListTests.java
- src/test/java/org/folio/circulation/domain/validation/ItemStatusValidatorTest.java
- src/test/resources/item-storage-8-5.json
https://issues.folio.org/browse/CIRC-669 - Backend - Aged to lost: Check out (not allowed)
https://issues.folio.org/browse/CIRC-670 - Backend - Aged to lost: Prevent all request types
* Use `item-storage:8.5`;
* Prevent check out of aged to lost item;
* Prevent all request types for aged to lost items.
Ideally all of the PRs involved in breaking changes …
> [CIRC-669, CIRC-670]: Prevent check out and requests for 'Aged to lost' items

- src/main/java/org/folio/circulation/services/feefine/FeeRefundProcessor.java
- src/test/java/api/loans/scenarios/RefundLostItemFeesTestBase.java
- src/test/java/api/support/matchers/AccountActionsMatchers.java
https://issues.folio.org/browse/CIRC-716:
Per Holly:
> When the REFUND ACTION RECORD is written, the Transaction Information is set to "Refund+ed+ to patron" or "Refund+ed+ to <transfer-account>" (depending on the situation). The use of the past tense is intentional.  …
> CIRC-716: Change tense for refund transaction info.

- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionService.java
- src/main/java/org/folio/circulation/infrastructure/storage/sessions/PatronActionSessionRepository.java
- src/test/java/api/loans/EndExpiredPatronActionSessionTests.java
- add loans fetching for session records;
- update tests;
Resolves: [CIRC-869](https://issues.folio.org/browse/CIRC-869)
> CIRC-869 Add loans fetching for session record

- pom.xml
FOLIO back end modules are being upgraded to support JDK 11 in order to continue working with sonar after October.
Mod-circulation would not build on later versions of Java due errors caused by an incompatible version of Rest Assured.
* Upgraded Rest Assured
* Testing using Adopt OpenJDK 11 and 14
Ideally all of the PRs involved in breaking changes would …
> Upgrade rest-assured to work with Java 14 CIRC-862

- src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
- src/main/java/org/folio/circulation/domain/representations/StoredFeeFineAction.java
- src/main/java/org/folio/circulation/infrastructure/storage/feesandfines/FeeFineOwnerRepository.java
- src/main/java/org/folio/circulation/services/FeeFineFacade.java
- src/main/java/org/folio/circulation/services/feefine/AccountRefundContext.java
- src/main/java/org/folio/circulation/services/feefine/FeeRefundProcessor.java
- src/main/java/org/folio/circulation/services/support/CreateAccountCommand.java
- src/main/java/org/folio/circulation/support/fetching/CqlIndexValuesFinder.java
- src/main/java/org/folio/circulation/support/fetching/MultipleCqlIndexValuesCriteria.java
- src/main/java/org/folio/circulation/support/http/client/CqlQuery.java
- src/test/java/api/support/RestAssuredClient.java
- src/test/java/api/support/fakes/FakeCQLToJSONInterpreter.java
- src/test/java/api/support/fixtures/FeeFineOwnerFixture.java
- src/test/java/api/support/http/TimedTaskClient.java
- src/test/java/api/support/matchers/LoanAccountActionsMatcher.java
- src/test/java/api/support/matchers/LoanAccountMatcher.java
- src/test/java/org/folio/circulation/services/FeeFineFacadeTest.java
https://issues.folio.org/browse/CIRC-852 - Age to lost: Assign lost fees for aged to lost loans - SET COST
This is first part of the story, and contains minor changes needed to support the whole feature.
* Allow a "system" fee/fine to be created;
* Allow fetching multiple fee/fine owners by service points;
* Refactor `CqlIndexValuesFinder` to accept comparison operator when building a long search query;
* Add `<=` and `>=` operators for fake CQL interpreter;
* Add certain fee/fine record matchers. 
- What other modules will …
> CIRC-852: [PT 1] Initial refactoring before implementing assigning fees.

- src/main/java/org/folio/circulation/infrastructure/storage/notes/NotesRepository.java
- src/test/java/api/support/builders/NoteTypeBuilder.java
The CQL used for finding note types used a `typeName` property which does not exist in the notes interface.
* Identified the mismatch with manual testing on folio-snapshot and postman
* changed the note type definition in the API tests (and tests failed)
* changed the CQL query in the production code
Ideally all of the PRs involved in breaking changes …
> Use name instead of type name for note types CIRC-742

- src/main/java/org/folio/circulation/domain/validation/ItemLimitValidator.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/support/builders/ItemBuilder.java
- Exclude claim returned items from item blocking limits counting;
- Create test;
Resolves: [CIRC-750](https://issues.folio.org/browse/CIRC-750)
> CIRC-750 Exclude claim returned items from item limits

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/resources/RenewalValidator.java
- src/main/java/org/folio/circulation/resources/handlers/LoanRelatedFeeFineClosedHandlerResource.java
- src/main/java/org/folio/circulation/resources/renewal/OverrideRenewalStrategy.java
- src/test/java/api/handlers/CloseAgedToLostLoanWhenLostItemFeesAreClosedApiTests.java
- src/test/java/api/support/fixtures/AgeToLostFixture.java
https://issues.folio.org/browse/CIRC-877 - Backend - Aged to lost: Closing (Lost and paid status) - SET COST
When associated lost item fees (both `Lost item` and `Lost item processing` fees) are resolved then allow aged to lost loan to be closed as `Lost and paid`.
* Adjust `LoanRelatedFeeFineClosedHandlerResource.java` to also be able to close `Aged to lost` loans.
* Add `isLoanWithLostItem` method to loan and replace similar logic in override renew resource.
* Add API tests to cover JIRA requirements.
- What other modules …
> CIRC-877: Close aged to lost loans when associated lost fees are resolved.

- src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
- src/main/java/org/folio/circulation/services/LostItemFeeChargingService.java
- src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
- src/main/java/org/folio/circulation/services/agedtolost/LoanToChargeFees.java
- src/main/java/org/folio/circulation/services/agedtolost/MarkOverdueLoansAsAgedLostService.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicyTest.java
- src/test/java/org/folio/circulation/services/agedtolost/LoanToChargeFeesTest.java
https://issues.folio.org/browse/CIRC-878 - Backend - Aged to lost: Close loans when no fees charged - SET COST.
Close aged to lost loans when no fee/fines have to be charged immediately. 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
> CIRC-878: Close loans with no fees to charge.

- src/main/java/org/folio/circulation/support/SingleRecordFetcher.java
> Sanitise both inputs to try to remove sonar vulnerability warning CIRC-381

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/representations/CheckOutByBarcodeRequest.java
- src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
To prepare for using lombok to help reduce some of the reported sonar warnings for mod-circulation
* Remove the redundant fields for service point IDs
* Introduce a check out request object simplify some of the check out resource logic
* Move the logic for defaulting certain properties to the builder methods instead of the constructor
* Replace the loan constructor with lombok generation
- Are the JIRAs under active development? …
> Introduce checkout request CIRC-381

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionService.java
- src/test/java/api/loans/EndExpiredPatronActionSessionTests.java
> Bugfix release 19.0.15

- src/main/java/org/folio/circulation/domain/Account.java
- src/main/java/org/folio/circulation/domain/CheckInContext.java
- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/domain/Request.java
Reduce the amount of Sonar warnings as they cause noise in the build processes.
* Use lombok to generate large constructors …
> Use lombok for large constructors CIRC-381

- src/main/java/org/folio/circulation/domain/AddressType.java
- src/main/java/org/folio/circulation/domain/ClaimItemReturnedRequest.java
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/schedule/DueDateScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/representations/ChangeDueDateRequest.java
- src/main/java/org/folio/circulation/domain/representations/ChangeItemStatusRequest.java
- src/main/java/org/folio/circulation/domain/representations/CheckInByBarcodeRequest.java
- src/main/java/org/folio/circulation/domain/representations/DeclareItemLostRequest.java
- src/main/java/org/folio/circulation/domain/representations/EndPatronSessionRequest.java
- src/main/java/org/folio/circulation/domain/representations/RequestByInstanceIdRequest.java
- src/main/java/org/folio/circulation/infrastructure/storage/users/AddressTypeRepository.java
- src/main/java/org/folio/circulation/resources/DeclareClaimedReturnedItemAsMissingResource.java
- src/main/java/org/folio/circulation/resources/renewal/RenewByBarcodeRequest.java
- src/main/java/org/folio/circulation/resources/renewal/RenewByIdRequest.java
- src/test/java/api/loans/DeclareClaimedReturnedItemAsMissingApiTests.java
- src/test/java/api/support/builders/DeclareClaimedReturnedItemAsMissingRequestBuilder.java
Ongoing series of pull requests to reduce the noise created by many outstanding sonar warnings
* Use lombok to reduce boiler plate code, particularly in data classes
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> CIRC-381 use lombok to reduce boiler plate

- src/test/java/org/folio/circulation/rules/Text2DroolsTest.java
Ongoing series of pull requests to reduce the noise created by many outstanding sonar warnings
* Replace the use of try-catch with a JUnit rule and hamcrest matchers
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> Replace catching exceptions with rule in text to drools tests CIRC-381

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/api/support/matchers/LoanHistoryMatcher.java
https://issues.folio.org/browse/CIRC-889 - Extra "Aged to lost" loan action is created when aged to lost loan is billed …
> CIRC-889: Use blank loan action on age to lost charge fee.

- pom.xml
* Ongoing series of pull requests to reduce the noise created by many outstanding sonar warnings
* Use latest stable surefire plugin (and remove comment as the next major version might not be released soon)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> CIRC-381 Use newer surefire plugin

- src/main/java/org/folio/circulation/domain/LoanRepresentation.java
- src/main/java/org/folio/circulation/domain/RequestRepresentation.java
- src/main/java/org/folio/circulation/domain/ServicePoint.java
- src/main/java/org/folio/circulation/domain/User.java
- src/main/java/org/folio/circulation/domain/representations/ItemReportRepresentation.java
- src/main/java/org/folio/circulation/support/JsonPropertyFetcher.java
Ongoing series of pull requests to reduce the noise created by many outstanding sonar warnings
Follow up to premature merging on #662 
* Use JSON property fetcher where possible, as that always uses an explicit default for boolean properties
* Remove redundant definition of properties for whether a service point is a pickup location
Ideally all of the …
> Default boolean properties CIRC-381

- pom.xml
- src/main/java/org/folio/circulation/support/http/client/ResponseInterpreter.java
- src/test/java/api/support/APITestContext.java
- src/test/java/api/support/RestAssuredClient.java
- src/test/java/api/support/RestAssuredResponseConversion.java
- src/test/java/api/support/fakes/FakeOkapi.java
Speed-up test execution on jenkins by running tests in parallel (via JVM fork) and decreasing amount of log outputs.
1. Run tests in parallel using `maven-surefire-plugin` fork capabilities (running separate JVM processes).
1. Add minor changes, so that `FakeOkapi` and `CirculationVerticle` uses dynamic port.
1. Use `debug` logging level in `ResponseInterpreter.java`, so each received response is not logged.
1. Configure `RestAssuredClient` to log only failed requests and responses by replacing `log(),all()` with `log().ifValidationFails()` and `log().greaterThan(300)`.
If there are breaking …
> Speed-up test execution on jenkins.

- pom.xml
> Fix code coverage report.

- src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
- src/main/java/org/folio/circulation/services/agedtolost/LoanToChargeFees.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/org/folio/circulation/services/agedtolost/LoanToChargeFeesTest.java
https://issues.folio.org/browse/CIRC-878 - Backend - Aged to lost: Close loans when no fees charged - SET COST
Holly has clarified that loans with delayed billing have to be closed also.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
> CIRC-878: Close loans that have not to be charged.

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/CIRC-903 - Permissions: declare lost for claimed returned item error
Missing permissions: …
> CIRC-903: Missing notes permissions when claimed returned item is declared lost.

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/CIRC-902 - Permissions: mark claimed returned item as missing …
> CIRC-902: Missing notes permissions when claimed returned item marked missing.

- pom.xml
- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/RequestQueue.java
- src/main/java/org/folio/circulation/domain/RequestType.java
- src/main/java/org/folio/circulation/domain/UpdateItem.java
- src/main/java/org/folio/circulation/domain/notes/NoteCreator.java
- src/main/java/org/folio/circulation/domain/validation/InactiveUserValidator.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestRepository.java
- src/main/java/org/folio/circulation/resources/CirculationRulesResource.java
- src/main/java/org/folio/circulation/rules/Text2Drools.java
- src/main/java/org/folio/circulation/support/FetchSingleRecord.java
- src/main/java/org/folio/circulation/support/http/client/Response.java
- src/main/java/org/folio/circulation/support/utils/CommonUtils.java
- src/test/java/api/loans/LoanAPITests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/RestAssuredResponseConversion.java
- src/test/java/api/support/fixtures/CalendarExamples.java
- src/test/java/org/folio/circulation/support/http/client/ResponseInterpretationTests.java
Ongoing series of pull requests to reduce the noise created by many outstanding sonar warnings …
> Remove sonar warnings CIRC-381

- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/domain/RequestRepresentation.java
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/policy/FixedDueDateSchedules.java
- src/main/java/org/folio/circulation/domain/representations/ContributorsToNamesMapper.java
- src/main/java/org/folio/circulation/domain/representations/ItemReportRepresentation.java
- src/main/java/org/folio/circulation/domain/representations/ItemSummaryRepresentation.java
- src/main/java/org/folio/circulation/infrastructure/storage/loans/AnonymizeStorageLoansRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/notices/PatronNoticePolicyMapper.java
- src/main/java/org/folio/circulation/support/StreamToListMapper.java
- src/main/java/org/folio/circulation/support/json/JsonArrayPropertyFetcher.java
- src/main/java/org/folio/circulation/support/json/JsonArrayToStreamMapper.java
- src/main/java/org/folio/circulation/support/json/JsonObjectArrayPropertyFetcher.java
- src/main/java/org/folio/circulation/support/json/JsonStringArrayPropertyFetcher.java
- src/test/java/api/loans/LoanAPITests.java
- src/test/java/api/requests/HoldShelfClearanceReportTests.java
- src/test/java/api/requests/ItemsInTransitReportTests.java
- src/test/java/api/requests/PickSlipsTests.java
- src/test/java/api/support/MultipleJsonRecords.java
- src/test/java/api/support/http/ResourceClient.java
- src/test/java/api/support/matchers/ValidationErrorMatchers.java
- src/test/java/org/folio/circulation/support/StreamToListMappingTests.java
- src/test/java/org/folio/circulation/support/json/JsonArrayToStreamMapperTests.java
- src/test/java/org/folio/circulation/support/json/JsonObjectArrayPropertyFetcherTests.java
- src/test/java/org/folio/circulation/support/json/JsonPropertyFetcherTests.java
- src/test/java/org/folio/circulation/support/json/JsonStringArrayPropertyFetcherTests.java
* Reduce the duplication between different ways of mapping a JSON array to a stream or list
* Introduce a new class for the basic mapping from a JSON array to a stream
* Use the new class to simplify existing methods
* Remove redundant methods that are only used in a handful of places
* Introduce a new class and method to mapping a stream to a list which can be composed with the above 
- …
> Consolidate json property reading CIRC-381 

- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/infrastructure/storage/feesandfines/FeeFineOwnerRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/LocationRepository.java
- src/main/java/org/folio/circulation/services/LostItemFeeChargingService.java
- src/test/java/api/loans/DeclareLostAPITests.java
- src/test/java/org/folio/circulation/domain/ItemPermanentLocationTest.java
- src/test/java/org/folio/circulation/domain/ItemTest.java
- src/test/java/org/folio/circulation/infrastructure/storage/inventory/LocationRepositoryTest.java
https://issues.folio.org/browse/CIRC-920 - Wrong location used to determine fee/fine owner for items declared lost.
Item "effective" permanent location should be used to find fee/fine owner for a lost fee.
The algorithm:
* Use Item location: Permanent
* If Item location: Permanent does not exist, use Holdings location: Permanent
* If Holdings location: Permanent does not exist, use Effective location for item
Note: the last is not possible, because holdings permanent location is a required property.
- What other modules will …
> CIRC-920: Use effective permanent location of an item when determining owner.

- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/LocationRepository.java
- src/main/java/org/folio/circulation/services/agedtolost/LoanToChargeFees.java
- src/main/java/org/folio/circulation/support/utils/CollectionUtil.java
- src/test/java/api/loans/OverrideRenewByBarcodeTests.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/api/support/fixtures/AgeToLostFixture.java
https://issues.folio.org/browse/CIRC-922 - Wrong location used to determine fee/fine owner for items aged to lost.
Use item effective permanent location to identify fee/fine owner when item aged to lost. …
> CIRC-922: Use permanent location service point to identify fee/fine owner for aged to lost items.

- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
- src/test/java/api/requests/scenarios/MoveRequestTests.java
@khandramai point to couple of failed tests on master - https://jenkins-aws.indexdata.com/job/folio-org/job/mod-circulation/job/master/684/#showFailuresLink.
They are failing only when the pipeline executed at 10:00 PM - 11:59 PM UTC. The idea of fix to move loan date to target time zone and then do manipulations needed.
Ideally all of the PRs involved …
> Fix time zone issue in tests.

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/UpdateLoan.java
- src/main/java/org/folio/circulation/resources/RenewalValidator.java
- src/test/java/api/loans/OverrideRenewByBarcodeTests.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/api/requests/RequestsAPILoanRenewalTests.java
- src/test/java/api/requests/scenarios/RecallItemsTests.java
- src/test/java/api/support/fixtures/RequestsFixture.java
- src/test/java/api/support/matchers/JsonObjectMatcher.java
- src/test/java/api/support/matchers/LoanHistoryMatcher.java
https://issues.folio.org/browse/CIRC-928 - Recall request retains override comment from check out …
> CIRC-928: Remove loan action comment when item is recalled.

- Dockerfile
- Jenkinsfile
- pom.xml
> CIRC-883: Migrate to java 11.

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/DueDateNotRealTimeScheduledNoticeProcessingResource.java
- src/main/java/org/folio/circulation/resources/DueDateScheduledNoticeProcessingResource.java
- src/main/java/org/folio/circulation/resources/FeeFineScheduledNoticeProcessingResource.java
- src/main/java/org/folio/circulation/resources/RequestScheduledNoticeProcessingResource.java
- src/main/java/org/folio/circulation/resources/ScheduledNoticeProcessingResource.java
- src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java
> Bugfix release 19.0.16

- pom.xml
Pub-sub client was released yesterday and builds are now failing because of the unresolved snapshot dependency.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> Use released pubsub-client version.

- src/main/java/org/folio/circulation/resources/renewal/OverrideRenewalStrategy.java
- src/test/java/org/folio/circulation/resources/renewal/OverrideRenewalStrategyTest.java
https://issues.folio.org/browse/CIRC-949 - Overriding failed renewal for aged to lost item, non-renewable loan policy does not change aged to lost status.
There are cases for which override renew is allowed. When a loan that matches multiple cases (item is not loanable and it is aged to lost) only logic for the first matched case is triggered and as a result an aged to lost item is still in aged to lost status + billing info is not cleared out.
Introduce `overrideRenewLoan` method that is executed for all the cases and sets `Checked out` status regardless override case.
If there are breaking …
> CIRC-949: Always set Checked out status after override renew.

- src/main/java/org/folio/circulation/domain/representations/AccountPaymentStatus.java
- src/main/java/org/folio/circulation/services/FeeFineFacade.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundContext.java
- src/main/java/org/folio/circulation/services/feefine/AccountRefundContext.java
- src/main/java/org/folio/circulation/services/feefine/FeeRefundProcessor.java
- src/main/java/org/folio/circulation/services/support/RefundAccountCommand.java
- src/test/java/api/loans/scenarios/CheckInAgedToLostItemTest.java
- src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
- src/test/java/api/loans/scenarios/OverrideRenewAgedToLostItemTest.java
- src/test/java/api/loans/scenarios/OverrideRenewDeclaredLostItemTest.java
- src/test/java/api/loans/scenarios/RefundAgedToLostFeesTestBase.java
- src/test/java/api/loans/scenarios/RefundDeclaredLostFeesTestBase.java
- src/test/java/api/support/matchers/AccountActionsMatchers.java
- src/test/java/api/support/matchers/AccountMatchers.java
- src/test/java/org/folio/circulation/services/FeeFineFacadeTest.java
https://issues.folio.org/browse/CIRC-951 - Change 'Action' from 'Cancelled item returned' to 'Cancelled item renewed' for renewed items
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> CIRC-951: Wrong cancellation reason is used when lost item is renewed.

- src/test/java/api/requests/scenarios/MoveRequestPolicyTests.java
Fix the failing test that @jsavell mentioned in https://github.com/folio-org/mod-circulation/pull/693.
Do asserts using awaitility because patron notices are processed asynchronously. 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
> Fix failing moveRecallRequestWithExistingRecallsAndWithMGDAndRDValuesChangesDueDateToRD test.

- src/test/java/api/requests/scenarios/MoveRequestPolicyTests.java
Fix remaining failed notice tests.
While it's helpful for reviewers to help identify …
> Fix remaining notice tests.

- src/main/java/org/folio/circulation/domain/validation/ProxyRelationshipValidator.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
https://issues.folio.org/browse/CIRC-884 - Improve error message when checking out on behalf of yourself.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> CIRC-884: Improve validation error message when proxy is the same as user.

- NEWS.md
- pom.xml
Updating artifact version to 19.3.0
> Release - 19.2.0 (master artifact version changing)

- src/test/java/api/requests/RequestsAPICreationTests.java
Clean up the tests a little bit before adding to them
While it's helpful for reviewers …
> CIRC-528 Preparation

- src/main/java/org/folio/circulation/domain/Location.java
- src/main/java/org/folio/circulation/resources/AbstractCirculationRulesEngineResource.java
- src/main/java/org/folio/circulation/resources/CirculationRulesResource.java
- src/main/java/org/folio/circulation/rules/CirculationRulesProcessor.java
- src/main/java/org/folio/circulation/rules/ExecutableRules.java
- src/main/java/org/folio/circulation/rules/cache/CirculationRulesCache.java
- src/test/java/api/CirculationRulesEngineAPITests.java
Increase the diagnostic output when applying circulation rules fails to try to assist with determining the cause
* Fail when the rules definition is blank
* Fail when the applying the rules fails  …
> Increased diagnostics when applying rules CIRC-960

- src/main/java/org/folio/circulation/infrastructure/storage/sessions/PatronActionSessionRepository.java
- src/test/java/api/loans/EndExpiredPatronActionSessionTests.java
- fix NPE for non existent item for loan;
- to cover this scenario by test;
Resolves: [CIRC-926](https://issues.folio.org/browse/CIRC-926)
> CIRC-926 fix NPE For session expiration with non existent item

- src/main/java/org/folio/circulation/rules/Drools.java
https://issues.folio.org/browse/CIRC-960 - Tests on jenkins periodically fail
While it's …
> CIRC-960: Make drools thread safe.

- pom.xml
- quick-test.sh
* Upgrade to JUnit 5 as is better supported and can be used to write neater unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> Upgrade to Junit 5 CIRC-959

- src/main/java/org/folio/circulation/domain/ItemStatus.java
- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/main/java/org/folio/circulation/resources/renewal/RegularRenewalStrategy.java
- src/test/java/api/requests/RequestsAPILoanRenewalTests.java
- src/test/java/api/support/builders/JsonBuilder.java
- src/test/java/api/support/builders/LoanPolicyBuilder.java
- src/test/java/api/support/builders/RequestBuilder.java
- src/test/java/api/support/matchers/ResultMatchers.java
- src/test/java/org/folio/circulation/resources/renewal/RegularRenewalStrategyTest.java
https://issues.folio.org/browse/CIRC-956 - Renewal that fails for multiple reasons does not show all reasons
Return all renew failure reasons when do regular renewal.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> CIRC-956: Show multiple renew failure reasons.

- src/main/java/org/folio/circulation/services/PubSubPublishingService.java
- src/main/java/org/folio/circulation/services/PubSubRegistrationService.java
- src/test/java/org/folio/circulation/services/PubSubPublishingServiceTest.java
Revert recent pub-sub changes.
While it's helpful for reviewers to help identify …
> Revert pub-sub changes.

- src/test/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicyTest.java
Due to leap/non leap years transition some tests fail now, I've changed some test values to smaller. …
> Fix LostItemPolicyTest test.

- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/builders/RequestBuilder.java
Disallow attempts to create requests with no reference to an item
While it's helpful for …
> Refuse to create request when no item ID included CIRC-528

- descriptors/ModuleDescriptor-template.json
As a result of breaking changes introduced in scope of [MODFEE-88](https://issues.folio.org/browse/MODFEE-88) major version of interface "feesfines" was updated from 15.6 to 16.0. Since mod-circulation depends on this interface, it needs to adopt this change as well. …
> [CIRC-972] Update version of interface "feesfines" to 16.0

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/CIRC-970 - Renewal appears to fail when user has minimal permissions.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> CIRC-970: Add missing fee/fine actions permissions for loan renew.

- src/main/java/org/folio/circulation/domain/representations/logs/LoanLogContext.java
- src/main/java/org/folio/circulation/services/EventPublisher.java
[CIRC-986](https://issues.folio.org/browse/CIRC-986) - User details are absent in aged to lost loan circ log record
User details in aged to lost loan should appear in circ log
* fixed loan log event …
> CIRC-986 - User details are absent in aged to lost loan circ log record

- pom.xml
- src/main/java/org/folio/circulation/support/json/JsonPropertyFetcher.java
- src/test/java/api/support/fakes/CqlPredicate.java
- src/test/java/api/support/fakes/FakeCQLToJSONInterpreter.java
- src/test/java/api/support/fakes/FakeStorageModule.java
Use the Z3950 lib (it is used in RMB) to parse CQL queries and build java predicate. This is needed to support more complex queries, for example: `status.name=="Open" and (itemStatus=="Declared lost" or (itemStatus=="Aged to lost" and agedToLostDelayedBilling.lostItemHasBeenBilled=="true"))`
Ideally all of the PRs involved in breaking changes would be …
> Use Z3950 lib to parse CQL in circulation tests.

- src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/scenarios/CheckInAgedToLostItemTest.java
- src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
https://issues.folio.org/browse/CIRC-955 - Loan is returned in check in response for Lost and paid item.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> CIRC-955: Do not return loan in check-in response for lost and paid item.

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/policy/FixedDueDateSchedules.java
- src/main/java/org/folio/circulation/support/utils/DateTimeUtil.java
- src/test/java/org/folio/circulation/domain/policy/FixedLoanPolicyCheckOutDueDateCalculationTests.java
> Bugfix release 19.2.5

- src/main/java/org/folio/circulation/domain/TimePeriod.java
- src/main/java/org/folio/circulation/support/json/JsonPropertyFetcher.java
- src/main/java/org/folio/circulation/support/utils/DateTimeUtil.java
- src/test/java/api/loans/CheckOutCalculateDueDateTests.java
- src/test/java/api/support/ExampleTimeZones.java
- src/test/java/api/support/fixtures/CheckOutFixture.java
- src/test/java/api/support/http/CheckOutResource.java
- src/test/java/api/support/matchers/DateTimeMatchers.java
- src/test/java/org/folio/circulation/support/json/DateAndTimeJsonPropertyFetcherTests.java
Before attempting to remove the use of `LocalDate` in these tests, I wanted to clean them up a little to try to help prepare them for the change.
* Moved utility methods and constants to separate classes
* Simplified the assertions on due date by removing unnecessary comments and using hamcrest matchers
* Moved getting the loan due date to a new check out resource
* Removed redundant checks on the correct loan policies being set on the loan (other API tests verify this)
* Removed redundant comments
- What other modules will …
> Tidy up checkout calculation tests CIRC-966

- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/test/java/api/queue/RequestQueueResourceTest.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- remove dueDateChanged checking for sending notice by recall trigger;
- update tests;
Resolves: https://issues.folio.org/browse/CIRC-989
> CIRC-989 remove dueDateChanged checking for sending notice

- descriptors/ModuleDescriptor-template.json
- Add permissions for /fixed-due-date-schedule-storage/fixed-due-date-schedules to /circulation/due-date-scheduled-notices-processing endpoint
Resolves: [CIRC-1023](https://issues.folio.org/browse/CIRC-1023)
> CIRC-1023 add permission for fixed-due-date-schedules

- src/main/java/org/folio/circulation/services/agedtolost/MarkOverdueLoansAsAgedLostService.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/api/support/builders/DeclareItemLostRequestBuilder.java
https://issues.folio.org/browse/CIRC-1033 - Declared lost items are also aging to lost
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> CIRC-1033: Do not age to lost declared lost items.

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/services/agedtolost/MarkOverdueLoansAsAgedLostService.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/api/support/builders/DeclareItemLostRequestBuilder.java
Includes:
* https://github.com/folio-org/mod-circulation/pull/769 (CIRC-1033)
* https://github.com/folio-org/mod-circulation/pull/770 (CIRC-1023)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> Release mod-circulation 19.2.8

- src/main/java/org/folio/circulation/resources/renewal/RegularRenewalStrategy.java
- src/test/java/api/support/matchers/ResultMatchers.java
- src/test/java/org/folio/circulation/resources/renewal/RegularRenewalStrategyTest.java
https://issues.folio.org/browse/CIRC-999 - Redundant renewal failure reasons display.
When loan policy is not loanable, renewal fails with two reasons - item is not loanable, loan is not renewable. Per Emma - there should be only one reason - loan is not loanable. …
> CIRC-999: Do not show loan is not renewable when it is not loanable on renew

- descriptors/ModuleDescriptor-template.json
- ramls/circulation.raml
- ramls/request-by-instance-id.json
- ramls/request.json
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/UpdateRequestService.java
- src/main/java/org/folio/circulation/domain/representations/RequestByInstanceIdRequest.java
- src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
- src/test/java/api/requests/InstanceRequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
- src/test/java/api/requests/scenarios/MoveRequestTests.java
- src/test/java/api/support/builders/RequestBuilder.java
- src/test/java/api/support/builders/RequestByInstanceIdRequestBuilder.java
https://issues.folio.org/browse/CIRC-988 - BE: Patron note on Request
* Allow patronComments for item\instance level requests;
* Bump `circulation` API minor version;
* Disallow update of the `patronComments` property;
* Make sure the property present on create of request/on get many/on move.
* Require `request-storage` v3.4.
Ideally all of the PRs …
> CIRC-988: Allow patron comments on item/instance level requests.

- descriptors/ModuleDescriptor-template.json
- ramls/pick-slips-response.json
- ramls/pick-slips.raml
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/requests/PickSlipsTests.java
https://issues.folio.org/browse/CIRC-1037 - BE: Create staff slip token for Patron comment on requests
* Add request.patronComments to the slip context.
* Bump pick slips API version to `0.3`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> CIRC-1037: Add request.patronComments to slips context.

- src/main/java/org/folio/circulation/domain/notice/schedule/RequestScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/RequestScheduledNoticeService.java
- src/test/java/api/requests/RequestScheduledNoticesProcessingTests.java
* Check if a request is cancelled before rescheduling notices
Resolves: [CIRC-1021](https://issues.folio.org/browse/CIRC-1021)
> CIRC-1021 Scheduled notices are sent after request cancellation 

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/requests-reports.raml
- src/test/java/api/requests/HoldShelfClearanceReportTests.java
https://issues.folio.org/browse/CIRC-1036 - BE: Display Patron Comments in Hold Shelf Clearance Report
* Update request-reports to 0.8 version (the patronComments is returned by default but this has not been reflected);
* Update lombok version, the prev version was not compatible with Idea 2020.3;
* Add an assert to verify that patronComments returned in the report.
- Do PRs exist for …
> CIRC-1036: Add patron comments to hold shelf report

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/ItemStatus.java
- src/main/java/org/folio/circulation/domain/validation/ItemStatusValidator.java
- src/test/java/api/support/fakes/StorageSchema.java
- src/test/java/org/folio/circulation/domain/validation/ItemStatusValidatorTest.java
- src/test/resources/item-storage-8-7.json
https://issues.folio.org/browse/CIRC-1011 - BE: Prevent check out for items with intellectual item status.
* Require item-storage API of 8.7 version;
* Do not allow check out of `Intellectual item` items. …
> CIRC-1011: Prevent check out for intellectual item status.

- src/main/java/org/folio/circulation/domain/validation/CheckInValidators.java
- src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/support/builders/ItemBuilder.java
- src/test/java/org/folio/circulation/domain/validation/CheckInValidatorsTests.java
* Refuse attempts to check in `intellectual items`, refer to [CIRC-1008](https://issues.folio.org/browse/CIRC-1008)
* Demonstrate the current behaviour in an API test
* Introduce validator (with unit tests)
* Use validator during check-in (and change API test to demonstrate new behaviour)
* mapping failures for results is quite hard to follow
Ideally all …
> Prevent check in of intellectual items CIRC-1008

- src/main/java/org/folio/circulation/infrastructure/storage/users/UserRepository.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
- src/test/java/api/loans/AgedToLostScheduledNoticesProcessingTests.java
- src/test/java/api/support/fixtures/EventSubscribersFixture.java
Extend Lost Item Fee refund logic to allow creation of scheduled patron notices for adjustments of fully paid Lost Item Fees.
Additionally fetch User and Item when refunding fully paid Lost Item Fees, otherwise we can't find Patron Notice Policy and schedule notices. …
> [CIRC-964] Fix scheduling notices for adjustment of fully paid lost item fees

- src/main/java/org/folio/circulation/domain/ItemStatus.java
- src/main/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteList.java
- src/test/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteListTests.java
https://issues.folio.org/browse/CIRC-1027 - BE: New item statuses: prevent requests
Prevent requests for items in statuses:
- Intellectual item
- In process (non-requestable)
- Long missing
- Unavailable
- Unknown …
> CIRC-1027: Prevent requests for the new statuses.

- src/main/java/org/folio/circulation/domain/ItemStatus.java
- src/test/java/org/folio/circulation/domain/validation/CheckInValidatorsTests.java
https://issues.folio.org/browse/CIRC-1007 - BE: Check in items with new statuses
Make sure items in following statuses can be checked in:
- Long missing
- In process (non-requestable)
- Restricted
- Unavailable
- Unknown …
> CIRC-1007: Check in items with new statuses.

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
- src/main/java/org/folio/circulation/services/agedtolost/MarkOverdueLoansAsAgedLostService.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/api/support/builders/LostItemFeePolicyBuilder.java
- src/test/java/api/support/fixtures/LostItemFeePoliciesFixture.java
- src/test/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicyTest.java
- src/test/java/org/folio/circulation/services/agedtolost/LoanToChargeFeesTest.java
https://issues.folio.org/browse/CIRC-1005 - Use separate aged to lost settings for recalled items …
> CIRC-1005: Use alternative recall properties for age to lost process.

- src/main/java/org/folio/circulation/domain/ItemStatus.java
- src/test/java/org/folio/circulation/domain/validation/ItemStatusValidatorTest.java
https://issues.folio.org/browse/CIRC-1009 - BE: Check out items with new statuses
Make sure items with the following statuses can be checked out:
- Long missing
- In process (non-requestable)
- Restricted
- Unavailable
- Unknown
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> CIRC-1009: Make sure items with new statuses can be checked out.

- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/schedule/FeeFineScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/TriggeringEvent.java
- src/test/java/api/loans/AgedToLostScheduledNoticesProcessingTests.java
- src/test/java/api/loans/FeeFineScheduledNoticesTests.java
- src/test/java/api/support/fixtures/TemplateContextMatchers.java
- src/test/java/api/support/matchers/PatronNoticeMatcher.java
Extend context of patron notices created for for automatic fee/fine adjustments (automatic refund and/or cancellation of lost item fees) to enable tokens related to fee/fine action.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> [CIRC-1065] Enable action-tokens for automatic fee/fine adjustments

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/LoanAction.java
- src/main/java/org/folio/circulation/domain/notice/schedule/LoanScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/resources/LoanScheduledNoticeProcessingResource.java
- src/test/java/api/loans/AgedToLostScheduledNoticesProcessingTests.java
- src/test/java/api/loans/ClaimItemReturnedAPITests.java
- src/test/java/api/loans/DueDateScheduledNoticesTests.java
- Stop sending scheduled notices after item claimed returned
- Check if item is claimed returned before sending notice
Resolves: [CIRC-1051](https://issues.folio.org/browse/CIRC-1051)
> CIRC-1051 Receiving overdue notices after item claimed returned

- src/main/java/org/folio/circulation/services/agedtolost/MarkOverdueLoansAsAgedLostService.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
https://issues.folio.org/browse/CIRC-1056 - If item record does not exist, age item to lost process should skip loan …
> CIRC-1056: Exclude loans from age to lost process if item is not found.

- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
The new asynchronous result class will need to be used in production code, both as an example and to demonstrate the behaviour is preserved. 
The chosen code is the requests collection resource class. This has been reformatted prior to introducing the new asynchronous result class to make it simpler to follow the chain of methods, to reduce the amount of changes in a single pull request
* Change the formatting of class initialisation to split by line length rather than per-parameter
* Use implicit type inference for most variables
* Use consistent order of initialisation of common variables
If there …
> CIRC-1066 Reformat request collection resource

- src/main/java/org/folio/circulation/domain/Loan.java
- src/test/java/api/loans/AgedToLostScheduledNoticesProcessingTests.java
- remove scheduled notices for renewed through override items;
- update test;
Resolves: [CIRC-1051](https://issues.folio.org/browse/CIRC-1051)
> CIRC-1051 add renew through override checking

- README.md
- descriptors/ModuleDescriptor-template.json
To resolve permissions failures when making downstream requests during renewal by ID
* https://issues.folio.org/browse/CIRC-1079
* Include note about Okapi and {{permissions}} implicit dependencies for moving permissions inline again (in preparation for removing more of the hidden permission sets that were introduced as a [workaround|https://issues.folio.org/browse/OKAPI-851])
* Check that the permission sets for renewal by ID and barcode are consistent
* Consolidate them to a single permission set (so new permissions can be added in one place in future)
If there are breaking changes, please …
> Add missing permissions for renewal by ID CIRC-1079 

- Jenkinsfile
- ramls/loan-anonymization.raml
The RAML documentation for the anonymization interface included an empty body definition that is invalid, as the body must be defined with a media type.
Detected by the new [api-lint|https://github.com/folio-org/folio-tools/tree/master/api-lint] process:
```
Violation - Payload media type is mandatory
Model: file://ramls/loan-anonymization.raml
Profile: RAML 1.0
Conforms? false
Number of results: 1
Level: Violation
- Source: http://a.ml/vocabularies/amf/parser#Payload-mediaType-minCount
Message: Payload media type is mandatory
Level: Violation
Target: file://ramls/loan-anonymization.raml#/web-api/end-points/%2Floan-anonymization%2Fby-user%2F%7BuserId%7D/post/request/default
Property: http://a.ml/vocabularies/core#mediaType
Position: Some(LexicalInformation([(23,8)-(24,0)]))
Location: …
```
> Remove erroneous body definition from anonymization RAML CIRC-1084

- src/main/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteList.java
- src/test/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteListTests.java
Allow restricted items to be requested
While it's helpful for reviewers to help identify …
> Allow restricted items to be requested CIRC-1085

- src/main/java/org/folio/circulation/domain/validation/overriding/CombinedOverridingRenewValidator.java
- src/main/java/org/folio/circulation/resources/RenewalValidator.java
- src/main/java/org/folio/circulation/resources/renewal/RegularRenewalStrategy.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/test/java/api/loans/RenewalAPITests.java
- exclude checking for existing blocks to allow overriding of manual block;
- remove redundant test;
Resolves: **[CIRC-1089](https://issues.folio.org/browse/CIRC-1089)**
> CIRC-1089 Renewal should succeed when patron block override requested without an automated patron block

- pom.xml
- src/main/java/org/folio/circulation/services/PubSubRegistrationService.java
Resolves: [CIRC-1096](https://issues.folio.org/browse/CIRC-1096)
Upgrade PubSub Client version to 2.0.1
Change mod-pubsub-client version to 2.0.1 in pom.xml
> CIRC-1096 Upgrade PubSub client to v2

- descriptors/ModuleDescriptor-template.json
> CIRC-1099 - add libraries collection get permission

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[CIRC-1102](https://issues.folio.org/browse/CIRC-1102) - Release 20.0.1
> Release - 20.0.1

- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
- src/test/java/api/requests/scenarios/MoveRequestTests.java
To reduce false failures for [tests](https://jenkins-aws.indexdata.com/job/folio-org/job/mod-circulation/job/master/809/) that use the system time meaning they are different each time and the current time can contradict with the assumptions in the test. In this case, the tests failed due to them executing less than 3 days before the end of the month.
* Replace system time with frozen clock
* Move the clock forward in time (instead of providing different parameters to APIs)
* Use literal values for expectations in the tests rather than calculation based upon variables
If there are breaking changes, …
> Use clock instead of system date in timezone dependent tests CIRC-1090

- descriptors/ModuleDescriptor-template.json
Fixes [CIRC-1114 Not receiving change due date notice](https://issues.folio.org/browse/CIRC-1114)
Iris Bugfest logs:
`2021-04-16T11:56:15.807Z 11:56:15 ERROR LogHelper            Failed to send patron notice request: PatronNotice{recipientId='ef2e7dad-b240-4b1c-91be-8bca561061ff', templateId='ec9c41b6-122e-4035-ba6f-295ed4993808'}. Cause: [403] Access requires permission: patron-notice.post`
Previously `patron-notice.post` permission was added to `modperms.circulation.loans.change-due-date.post`, but further investigation has shown that dedicated `change-due-date` endpoint is not actually being used for changing due date. Instead, it is done with `PUT /circulation/loans/{id}`.
Add `patron-notice.post` permission to `modperms.circulation.loans.item.put`
Before merging this PR, please go …
> CIRC-1114 Add notices permission to loans PUT endpoint

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/main/java/org/folio/circulation/support/json/JsonPropertyFetcher.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/requests/ItemsInTransitReportTests.java
- src/test/java/api/requests/PickSlipsTests.java
- src/test/java/api/requests/RequestScheduledNoticesProcessingTests.java
- src/test/java/api/requests/RequestScheduledNoticesTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
- src/test/java/api/support/builders/RequestBuilder.java
- src/test/java/api/support/fixtures/TemplateContextMatchers.java
- src/test/java/api/support/utl/DateTimeUtils.java
Request expiration date should expire at the end of the day selected
Resolves: [CIRC-1119](https://issues.folio.org/browse/CIRC-1119)
- Add truncating of request expiration date to the end of the day;
- Update tests;
> CIRC-1119 create truncating of request expiration

- NEWS.md
- descriptors/ModuleDescriptor-template.json
Discovered there was a typo in the permission name.
> CIRC-1117: adjusting permission name

- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/support/fixtures/TemplateContextMatchers.java
Request pickup notice is not sent when requester barcode is changed after request is created.
Find requester by ID (stored in the request) instead of barcode. Requester barcode is captured when request is created, and is not updated once changed in user record.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> [CIRC-1139] Fix sending request pickup notices when requester barcode was changed

- ramls/circulation.raml
- ramls/request-by-instance-id.json
For this API the client does not pick the item.
This should be reflected in the description.
> Fix instance request documentation

- pom.xml
- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/LoanAndRelatedRecords.java
- src/main/java/org/folio/circulation/domain/validation/ChangeDueDateValidator.java
- src/main/java/org/folio/circulation/resources/ChangeDueDateResource.java
- src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/main/java/org/folio/circulation/services/EventPublisher.java
- src/test/java/api/loans/LoanAPITests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
- src/test/java/org/folio/circulation/domain/validation/ChangeDueDateValidatorTest.java
[CIRC-1140](https://issues.folio.org/browse/CIRC-1140) - No Log Record entry when loan due date was changed
No Log Record entry when loan change due date was made.
Enable publishing of due date changes, improve event description
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> CIRC-1140 - No Log Record entry when loan due date was changed

- NEWS.md
- pom.xml
Each time mod-circulation sends an event towards mod-pubsub a new instance of HTTP client (`HttpClientImpl`) is created, but not closed afterwards, wich results in clients piling up in memory. This bug in `mod-pubsub-client` was fixed by [MODPUBSUB-166](https://issues.folio.org/browse/MODPUBSUB-166), so now mod-circulation needs to be updated to use the fixed version of the library.
Update version of `mod-pubsub-client` to v2.0.7.
Tested by running 1000 checkin/checkout cycles and analyzing the heap dump afterwards:
- What …
> [CIRC-1121] Update version of mod-pubsub-client to fix memory leak

- README.md
- pom.xml
- src/main/java/org/folio/circulation/rules/Drools.java
Update Drools from 7.0.0.Final to 7.53.0.Final.
The new Drools version updates xstream to 1.4.16 fixing these vulnerabilies:
* XStream is vulnerable to a Remote Command Execution attack: https://nvd.nist.gov/vuln/detail/CVE-2021-21345
* A Server-Side Forgery Request can be activated unmarshalling with XStream to access data streams from an arbitrary URL referencing a resource in an intranet or the local host: https://nvd.nist.gov/vuln/detail/CVE-2021-21342
* A Server-Side Forgery Request can be activated unmarshalling with XStream to access data streams from an arbitrary URL referencing a resource in an intranet or the local host: https://nvd.nist.gov/vuln/detail/CVE-2021-21349
* XStream is vulnerable to an Arbitrary Code Execution attack: https://nvd.nist.gov/vuln/detail/CVE-2021-21351
* …
> CIRC-1147: Drools 7.53.0.Final, xstream 1.4.16 (CVE-2021-21342, CVE-2021-21345)

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/support/fixtures/TemplateContextMatchers.java
Create bugfix release v20.1.6.
Resolves [CIRC-1149](https://issues.folio.org/browse/CIRC-1149). …
> Hotfix release v20.1.6

- src/main/java/org/folio/circulation/domain/validation/UserManualBlocksValidator.java
- src/test/java/api/requests/RequestsAPICreationTests.java
Resolves [CIRC-1078](https://issues.folio.org/browse/CIRC-1078).
Manual requesting block is ignored if its expiration date is not set.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> [CIRC-1078] Respect manual requesting block without expiration date

- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/support/builders/RequestBuilder.java
- src/test/java/api/support/fixtures/RequestsFixture.java
Send Request Awaiting Pickup notice when item becomes available because previous request is cancelled/expires while the item is on the holdshelf.
Resolves [CIRC-1141](https://issues.folio.org/browse/CIRC-1141). …
> [CIRC-1141] Send Request Awaiting Pickup notice when previous request was cancelled/expired

- src/main/java/org/folio/circulation/domain/policy/library/ClosedLibraryStrategyService.java
- src/main/java/org/folio/circulation/domain/policy/library/ClosedLibraryStrategyUtils.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/support/fixtures/CalendarExamples.java
- Fix the issue related to truncating due date to the previous open day if patron expiration is earlier;
- Get another opening days from calendar for patron expiration day;
> CIRC-1159 Fix issue with truncating due date 

- pom.xml
> [CIRC-1162] Update POM for release 20.1.7

- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/support/utl/DateTimeUtils.java
- add tests to cover renew due date truncating scenarios
Resolves: [CIRC-888](https://issues.folio.org/browse/CIRC-888)
> CIRC-888 add tests for renew due date truncating

- src/main/java/org/folio/circulation/domain/anonymization/LoanAnonymization.java
- src/main/java/org/folio/circulation/resources/LoanAnonymizationResource.java
- src/main/java/org/folio/circulation/resources/ScheduledAnonymizationProcessingResource.java
- src/test/java/org/folio/circulation/domain/anonymization/LoanAnonymizationTests.java
Preparation for changing how anonymization works
Some of the smaller tests do not provide sufficient assertions, which was hiding incorrect setup in the tests
* Make sure the assertions in the test fail in the expected ways when the code isn't working as expected
> Improve loan anonymization tests CIRC-1178

- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/main/java/org/folio/circulation/services/EventPublisher.java
[CIRC-1188](https://issues.folio.org/browse/CIRC-1188) - Screen is hanging on a loading screen when trying to view loan details on the Circulation log page
If the user filters by "Recall requested" in the "Loans" section of the Circulation log page, then scroll to the right and select "Loan details" on the ellipses in the "Action" column, the screen is hanging on a loading screen.
* changed event publisher logic to send correct user id
- Do JIRAs exist to update the impacted …
> CIRC-1188 - Screen is hanging on a loading screen when trying to view loan details on the Circulation log page

- src/main/java/org/folio/circulation/services/EventPublisher.java
- src/test/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicyTest.java
[CIRC-1165](https://issues.folio.org/browse/CIRC-1165) - Circ log filter for renewed doesn't work
Renewed and Renewed through override loan actions doesn't appear in circulation audit log
* updated logic to send Renewed through override loan action event
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
> CIRC-1165 - Circ log filter for renewed doesn't work

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/UserManualBlock.java
- src/main/java/org/folio/circulation/domain/validation/UserManualBlocksValidator.java
- src/main/java/org/folio/circulation/services/EventPublisher.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/OverrideRenewByBarcodeTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/fixtures/UserManualBlocksFixture.java
- src/test/java/api/support/matchers/EventActionMatchers.java
- src/test/java/api/support/matchers/EventMatchers.java
- src/test/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicyTest.java
[CIRC-1191](https://issues.folio.org/browse/CIRC-1191) - Bugfix release 22.0.1
> CIRC-1191 - Release 22.0.1

- pom.xml
To change the next version to a patch version rather than minor as this branch is intended for patch releases.
> Change to next patch version instead of minor CIRC-1191

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/notice/schedule/LoanScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledNoticeConfig.java
- src/test/java/api/loans/DueDateScheduledNoticesProcessingTests.java
- src/test/java/api/loans/DueDateScheduledNoticesTests.java
- src/test/java/api/support/builders/NoticeConfigurationBuilder.java
- src/test/java/api/support/fixtures/DeclareLostFixtures.java
Reimplement conditions described in [CIRC-1051](https://issues.folio.org/browse/CIRC-1051).
Resolves [CIRC-1205](https://issues.folio.org/browse/CIRC-1205).
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
> [CIRC-1205] fix conditions to stop sending recurring loan-related notices

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/notice/schedule/LoanScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledNoticeConfig.java
- src/test/java/api/loans/DueDateScheduledNoticesProcessingTests.java
- src/test/java/api/loans/DueDateScheduledNoticesTests.java
- src/test/java/api/support/builders/NoticeConfigurationBuilder.java
- src/test/java/api/support/fakes/PublishedEvents.java
- src/test/java/api/support/fixtures/DeclareLostFixtures.java
- src/test/java/api/support/utl/PatronNoticeTestHelper.java
> [CIRC-1206] Release 22.0.4

- NEWS.md
Resolves [CIRC-1292](https://issues.folio.org/browse/CIRC-1292)
Update release notes in the NEWS.md, add info about the work completed by Vega in R3 2021
> CIRC-1292 - Update NEWS.md - Vega R3 2021

- NEWS.md
[CIRC-1194](https://issues.folio.org/browse/CIRC-1194) - Updating NEWS.md (Firebird R3 2021)
> CIRC-1294 - Update NEWS.md - Firebird R3 2021

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/RequestQueue.java
- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/main/java/org/folio/circulation/resources/ChangeDueDateResource.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
- src/test/java/api/requests/PickSlipsTests.java
- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
I added code to both renewal and dueDateChange resources to check
for specified conditions and clear the flag.  I modified an existing 
renewal test to check for this, and wrote a new test for due date change.
I had two unrelated failing tests-these were failing in master, so
not sure how they got there.  Both involved code that wanted a 
time-zone offset in a very specific format (three digit offset), 
with the actual zoned datetime using a slightly different format 
(three-digit offset with a Z at the end).  I modified the tests to accept 
the time-zone offset with a Z at the end.
> CIRC-1112: Recalls not being honored when there has been a renew or change due date

- src/main/java/org/folio/circulation/services/EventPublisher.java
[CIRC-1344](https://issues.folio.org/browse/CIRC-1344) - Investigate Description field for renewed through override actions in Circ Log
Add description field when action is Renewed through override
Populate LoanLogContext with description.
> CIRC-1344 - Investigate Description field for renewed through override actions in Circ Log

- src/main/java/org/folio/circulation/infrastructure/storage/loans/LoanRepository.java
- src/main/java/org/folio/circulation/resources/ChangeDueDateResource.java
I am adding some logging code to try and pinpoint the problem with
the fix for this issue with regard to change due date operations.
I'm logging the state of the loan object before the flag check code 
operates, as well as which parts of that code trigger as the check 
progresses.  I also added logging to the update code which operates 
right before loan objects are saved.
I moved the flag check up in the promise chain so that it's closer to 
the save operation, to minimize chances that the changes are somehow 
being meddled with by other operations.
> CIRC-1112: Adding Logging Code

- ramls/examples/request.json
- ramls/request.json
- src/main/java/org/folio/circulation/domain/RequestLevel.java
- src/main/java/org/folio/circulation/domain/representations/RequestProperties.java
- src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/main/java/org/folio/circulation/resources/handlers/error/CirculationErrorType.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
- src/test/java/api/support/builders/RequestBuilder.java
Extend request model with `holdingsRecordId`, which at this point will only be present in item-level requests.
Resolves [CIRC-1353](https://issues.folio.org/browse/CIRC-1353).
> [CIRC-1353] Add holdingsRecordId to request

- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/domain/RequestRepresentation.java
- src/main/java/org/folio/circulation/domain/representations/InstanceProperties.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/support/builders/InstanceBuilder.java
- src/test/java/api/support/fixtures/InstanceExamples.java
- src/test/java/org/folio/circulation/domain/RequestRepresentationTests.java
https://issues.folio.org/browse/CIRC-1364
> CIRC-1364 Add Year to the request JSON structure

- src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
[CIRC-1374](https://issues.folio.org/browse/CIRC-1374)
_Fix build issue in mod-circulation master branch_
> CIRC-1374: Fix build issue in mod-circulation master branch

- ramls/request.json
[CIRC-1376](https://issues.folio.org/browse/CIRC-1376)
_Remove holdingsRecordId from Item in requests_
> CIRC-1376b: Remove holdingsRecordId from Item in requests

- ramls/request.json
[CIRC-1376](https://issues.folio.org/browse/CIRC-1376)
_Remove holdingsRecordId from Item in requests_
> CIRC-1376a: Remove holdingsRecordId from Item in requests

- NEWS.md
- pom.xml
- src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
> Bugfix release 22.1.4

- src/main/java/org/folio/circulation/domain/RequestRepresentation.java
- src/test/java/api/requests/RequestsAPIRelatedRecordsTests.java
- src/test/java/api/requests/scenarios/RequestQueueTests.java
Link to [ticket](https://issues.folio.org/browse/CIRC-1385)
Item.holdingsRecordId field was removed from RequestRepresentation
> CIRC-1385 tlr-feature

- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
https://issues.folio.org/browse/CIRC-1359
When item fulfilling a hold TLR checked in, itemId and holdingsRecordId fields should be filled.
> CIRC-1359 Link item to hold TLR when checked in

- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/domain/validation/RequestLoanValidator.java
- src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/main/java/org/folio/circulation/resources/handlers/error/CirculationErrorType.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/requests/RequestScheduledNoticesProcessingTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/requests/scenarios/CancelRequestTests.java
- src/test/java/api/support/fixtures/ItemsFixture.java
Link to [ticket](https://issues.folio.org/browse/CIRC-1361)
Validation for TLR was added
> CIRC-1361 Add validation for TLR-request

- src/main/java/org/folio/circulation/domain/Instance.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/InstanceRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestRepository.java
- src/test/java/api/requests/RequestsAPICreationTests.java
https://issues.folio.org/browse/CIRC-1394 fixed
> CIRC-1394 Publication data missing in Instance when call API circulation/requests?query=id

- descriptors/ModuleDescriptor-template.json
[CIRC-1408](https://issues.folio.org/browse/CIRC-1408)
[FOLIO-3376](https://issues.folio.org/browse/FOLIO-3376)
> CIRC-1408 Require request-storage-batch 1.0

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/LoanAction.java
- src/main/java/org/folio/circulation/domain/representations/logs/LogContextActionResolver.java
- src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
[CIRC-1373](https://issues.folio.org/browse/CIRC-1373) - Add new Action when an automated fee/fine is charged if item is aged to lost
Rollback changes, see commentaries at [CIRC-1373](https://issues.folio.org/browse/CIRC-1373)
> CIRC-1373 - Add new Action when an automated fee/fine is charged if item is aged to lost - Rollback changes

- src/main/java/org/folio/circulation/services/ItemsInTransitReportService.java
- src/main/java/org/folio/circulation/services/support/ItemsInTransitReportContext.java
- src/test/java/org/folio/circulation/services/ItemsInTransitReportServiceTest.java
JIRA ticket [CIRC-1339](https://issues.folio.org/browse/CIRC-1339)
Part of the new items-in-transit report implementation. 
Use the same fetcher as the original implementation to fetch items in batches
> CIRC-1339 - Items in transit report performance: fetch items

- pom.xml
Log4j 2.16.0 causes this error message many times when running mod-circulation.jar:
2022-01-12 18:28:05,983 main ERROR Unable to create Lookup for bundle java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/lookup/JndiLookup
at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:81)
at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:631)
at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:243)
at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:289)
at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:626)
at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699) …
> CIRC-1415: Log4j 2.17.1

- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemReportRepository.java
Increase performance of Items in Transit Report ([CIRC-1420](https://issues.folio.org/browse/CIRC-1420)).
Increase page size for fetching items in status `In transit`. According to performance testing results, this nearly halves the time required to build a report with 35k entries: 37s with 1000 items per page, 67s with 100 items per page.
> [CIRC-1420] Increase page limit in ItemReportRepository

- descriptors/ModuleDescriptor-template.json
Define missed permission in permissionSet
Resolves: [CIRC-1453](https://issues.folio.org/browse/CIRC-1453)
> CIRC-1453 Define missed permissions in perm set

- src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/org/folio/circulation/domain/UpdateRequestQueueTest.java
- Update logic for checkout request update;
- Create test;
Resolves:  [CIRC-1450](https://issues.folio.org/browse/CIRC-1450)
- Ignore request update if the request is not associated with the item
> CIRC-1450 Update logic for checkout request update

- descriptors/ModuleDescriptor-template.json
Extend permissionSets with a displayName + description
Added requested permissions
https://issues.folio.org/browse/CIRC-1469
> Extend permissionSets by permissions

- src/main/java/org/folio/circulation/resources/TitleLevelRequestNoticeSender.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/scenarios/CancelRequestTests.java
- src/test/java/api/support/PubsubPublisherTestUtils.java
- src/test/java/api/support/matchers/EventMatchers.java
[CIRC-1495](https://issues.folio.org/browse/CIRC-1495) - Fix TLR notice circulation log record
Fix issue with notice circulation log record content.
Fix business logic - add complete notice log content for processing.
> CIRC-1495 - Fix TLR notice circulation log record

- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
https://issues.folio.org/browse/CIRC-1476
> CIRC-1476 - Allow recalls to extend due dates for overdue loans loan policy setting not being honored in Lotus bugfest

- src/main/java/org/folio/circulation/domain/RequestAndRelatedRecords.java
- src/main/java/org/folio/circulation/domain/UpdateLoan.java
- src/main/java/org/folio/circulation/services/EventPublisher.java
- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
https://issues.folio.org/browse/CIRC-1505
> CIRC-1505 - Circ log may not be displaying the correct info for the date change when an item is recalled

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/services/FeeFineFacade.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
- src/main/java/org/folio/circulation/services/feefine/AccountActionResponse.java
- src/test/java/api/loans/AgedToLostScheduledNoticesProcessingTests.java
- src/test/java/api/loans/scenarios/CheckInAgedToLostItemTest.java
- src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
- src/test/java/api/loans/scenarios/RefundAgedToLostFeesTestBase.java
- src/test/java/api/loans/scenarios/RefundDeclaredLostFeesTestBase.java
- src/test/java/api/support/fakes/FakeFeeFineOperationsModule.java
Currently we decide if refunded fee/fine should be cancelled based on **initial** (before refund) remaining amount of the fee/fine. Instead, we should make this decision based on the updated (after refund) remaining amount, which is provided by mod-feesfines in the refund response (since [MODFEE-247](https://issues.folio.org/browse/MODFEE-247)).
Resolves [CIRC-1496](https://issues.folio.org/browse/CIRC-1496).
> [CIRC-1496] Cancel refunded account according to its current remaining amount

- src/main/java/org/folio/circulation/infrastructure/storage/ConfigurationRepository.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
- src/test/java/api/queue/RequestQueueResourceTest.java
- src/test/java/api/requests/InstanceRequestsAPICreationTests.java
- src/test/java/api/requests/RequestScheduledNoticesProcessingTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/requests/scenarios/CancelRequestTests.java
- src/test/java/api/requests/scenarios/HoldShelfFulfillmentTests.java
- src/test/java/api/requests/scenarios/MoveRequestTests.java
- To remove the ability for a user to enable/disable title level requests;
- Disable tests that use TLR settings;
Resolves: [CIRC-1510](https://issues.folio.org/browse/CIRC-1510)
> [CIRC-1510] Disable TLR feature, disable tests

- src/main/java/org/folio/circulation/domain/notice/schedule/GroupedLoanScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/services/agedtolost/LoanToChargeFees.java
- replace deprecated logger for overnight notices;
Resolves: [CIRC-1516](https://issues.folio.org/browse/CIRC-1516)
> CIRC-1516 replace deprecated logger

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/notice/schedule/GroupedLoanScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/services/agedtolost/LoanToChargeFees.java
Resolves: [CIRC-1518](https://issues.folio.org/browse/CIRC-1518)
> Bugfix release 23.0.6

- src/main/java/org/folio/circulation/infrastructure/storage/ConfigurationRepository.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
- src/test/java/api/queue/RequestQueueResourceTest.java
- src/test/java/api/requests/InstanceRequestsAPICreationTests.java
- src/test/java/api/requests/RequestScheduledNoticesProcessingTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/requests/scenarios/CancelRequestTests.java
- src/test/java/api/requests/scenarios/HoldShelfFulfillmentTests.java
- src/test/java/api/requests/scenarios/MoveRequestTests.java
- To restore the ability for a user to enable/disable title level requests;
- Enable tests that use TLR settings;
Resolves: [CIRC-1520](https://issues.folio.org/browse/CIRC-1520)
> [CIRC-1520] Enable TLR feature, enable ignored tests

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/schedule/GroupedLoanScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledNoticeHandler.java
- src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java
> [CIRC-1522] Bugfix release 23.0.7

- src/main/java/org/folio/circulation/infrastructure/storage/inventory/LocationRepository.java
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/main/java/org/folio/circulation/resources/TitleLevelRequestNoticeSender.java
- src/test/java/api/requests/scenarios/PageRequestWorkflowTests.java
[CIRC-1467](https://issues.folio.org/browse/CIRC-1467)
_TLR confirmation notice: Two fields don't populate_
> CIRC-1467: TLR confirmation notice, two fields don't populate

- src/main/java/org/folio/circulation/domain/validation/ClosedRequestValidator.java
- src/test/java/api/requests/scenarios/ClosedRequestTests.java
[CIRC-1530](https://issues.folio.org/browse/CIRC-1530)
_Change the failure message of the closed request validator_
> CIRC-1530: Change the failure message of the closed request validator

- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
- src/test/java/api/requests/InstanceRequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/fixtures/RequestPoliciesFixture.java
- src/test/java/org/folio/circulation/resources/RequestByInstanceIdResourceTests.java
Change requests sequence creation for mod-patron
- Changed requests types sequence
- Update TLR policy condition
- Tests fixed
https://issues.folio.org/browse/CIRC-1479
> CIRC-1479 TLR not respecting request policies

- ramls/loan.json
- ramls/service-point.json
- ramls/servicepoint-properties.json
Put to accordance fields available in loan schema to actual json response 
Update loan schema
https://issues.folio.org/browse/CIRC-915
> CIRC-915 Business loan response contains properties that are not defined in schema

- src/main/java/org/folio/circulation/domain/RequestQueue.java
- src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
[CIRC-1549](https://issues.folio.org/browse/CIRC-1549)
> CIRC-1549: TLR Recalls not fulfilling correctly

- src/main/java/org/folio/circulation/domain/policy/lostitem/ChargeAmountType.java
- src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostApiTest.java
- src/test/java/api/support/builders/LostItemFeePolicyBuilder.java
- src/test/java/api/support/fixtures/LostItemFeePoliciesFixture.java
[CIRC-895](https://issues.folio.org/browse/CIRC-895)
> [CIRC-895] Age items to lost when Lost Item Fee Policy is configured with actual cost

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/circulation.raml
- ramls/request.json
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/main/java/org/folio/circulation/support/json/JsonPropertyWriter.java
- src/test/java/api/requests/RequestsAPICreationTests.java
Release ticket: https://issues.folio.org/browse/CIRC-1551
Released bugfix: https://issues.folio.org/browse/CIRC-1546
> [CIRC-1551] Release 23.0.10

- src/main/java/org/folio/circulation/services/ActualCostRecordService.java
- src/main/java/org/folio/circulation/services/LostItemFeeChargingService.java
- src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
- src/test/java/api/loans/DeclareLostAPITests.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
Disable creation of actual cost records for Morning Glory release.
[CIRC-1554](https://issues.folio.org/browse/CIRC-1554).
> [CIRC-1554] Disable actual cost record creation

- src/main/java/org/folio/circulation/services/ActualCostRecordService.java
- src/main/java/org/folio/circulation/services/LostItemFeeChargingService.java
- src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
- src/test/java/api/loans/DeclareLostAPITests.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
[CIRC-1555](https://issues.folio.org/browse/CIRC-1555)
Re-enable actual cost functionality after Morning Glory release
Revert everything that was done in CIRC-1554
> CIRC-1555 Re-enable actual cost functionality

- src/main/java/org/folio/circulation/domain/notice/schedule/RequestScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
- src/main/java/org/folio/circulation/domain/representations/ItemsInTransitReport.java
- src/main/java/org/folio/circulation/infrastructure/storage/ConfigurationRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
- src/main/java/org/folio/circulation/services/LostItemFeeChargingService.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
- src/main/java/org/folio/circulation/services/PubSubPublishingService.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostApiTest.java
- src/test/java/api/support/fixtures/LostItemFeePoliciesFixture.java
Resolves [CIRC-1557](https://issues.folio.org/browse/CIRC-1557)
Loan should age to lost when actual cost is selected in the lost item fee policy
> CIRC-1557 Age to lost actual cost loans

- NEWS.md
- pom.xml
Release ticket: https://issues.folio.org/browse/CIRC-1560
Released bugfix: https://issues.folio.org/browse/CIRC-1557
> [CIRC-1560] Release 23.0.11

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/services/EventPublisher.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
[CIRC-1573](https://issues.folio.org/browse/CIRC-1573) - CIRC (mod-circulation) MG BF release
> CIRC-1573 - Release 23.1.1

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/support/utils/DateFormatUtil.java
- src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java
- src/test/java/api/loans/RenewByBarcodeTests.java
- src/test/java/api/loans/RenewByIdTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/org/folio/circulation/domain/LoanTest.java
https://issues.folio.org/browse/CIRC-1595
> [CIRC-1595] Release 23.1.2

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/CIRC-1593
> CIRC-1593: Add missing permission

- src/main/java/org/folio/circulation/domain/representations/ItemsInTransitReport.java
- src/test/java/api/requests/ItemsInTransitReportTests.java
- Fix NPE in Items In Transit report;
- Add tests;
Resolves: [CIRC-1588](https://issues.folio.org/browse/CIRC-1588)
> CIRC-1588 Fix NPE, add tests

- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestQueueRepository.java
- src/main/java/org/folio/circulation/resources/RenewalValidator.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/test/java/api/loans/RenewalAPITests.java
Renewal is not allowed when first request in the request queue for the borrowed item is an item-level recall. We should forbid renewal when there is a recall request of **any level** in **any position** in the request queue.
[CIRC-1610](https://issues.folio.org/browse/CIRC-1610)
> CIRC-1610: Refuse renewal when title-level recall exists

- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestQueueRepository.java
- src/main/java/org/folio/circulation/resources/context/RenewalContext.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/requests/RequestsAPILoanRenewalTests.java
- src/test/java/org/folio/circulation/domain/policy/FixedLoanPolicyRenewalDueDateCalculationTests.java
- src/test/java/org/folio/circulation/domain/policy/RollingLoanPolicyRenewalDueDateCalculationTests.java
- src/test/java/org/folio/circulation/resources/renewal/RegularRenewalTest.java
Use unified request queue (the one with requests of all levels) during renewal.
[CIRC-1611](https://issues.folio.org/browse/CIRC-1611)
> CIRC-1611: Consider TLRs during renewal

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestQueueRepository.java
- src/main/java/org/folio/circulation/resources/RenewalValidator.java
- src/main/java/org/folio/circulation/resources/context/RenewalContext.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/requests/RequestsAPILoanRenewalTests.java
- src/test/java/org/folio/circulation/domain/policy/FixedLoanPolicyRenewalDueDateCalculationTests.java
- src/test/java/org/folio/circulation/domain/policy/RollingLoanPolicyRenewalDueDateCalculationTests.java
- src/test/java/org/folio/circulation/resources/renewal/RegularRenewalTest.java
[CIRC-1614](https://issues.folio.org/browse/CIRC-1614)
> CIRC-1614: release v23.1.5

- pom.xml
- src/test/java/org/folio/circulation/support/StringUtilTests.java
- src/test/java/org/folio/circulation/support/http/ContentTypeTest.java
[CIRC-1628](https://issues.folio.org/browse/CIRC-1628)
> CIRC-1628 Upgrade to RMB 35.0.0 and Vertx 4.3.3

- src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
- src/main/java/org/folio/circulation/services/agedtolost/LoanToChargeFees.java
- src/test/java/api/handlers/CloseAgedToLostLoanWhenLostItemFeesAreClosedApiTests.java
- src/test/java/api/handlers/CloseDeclaredLostLoanWhenLostItemFeesAreClosedApiTests.java
- src/test/java/api/handlers/CloseLostLoanWhenLostItemFeesAreClosed.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/api/support/matchers/ItemMatchers.java
> CIRC-1624 Do not close the loan when Actual Cost Record is created

- NEWS.md
- pom.xml
https://issues.folio.org/browse/CIRC-1635
> CIRC-1635: Release 23.2.0

- NEWS.md
- pom.xml
[CIRC-1647](https://issues.folio.org/browse/CIRC-1647)
> CIRC-1647: Release 23.3.0

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/ActualCostRecord.java
- src/main/java/org/folio/circulation/infrastructure/storage/ActualCostRecordRepository.java
- src/main/java/org/folio/circulation/services/CloseLoanWithLostItemService.java
- src/main/java/org/folio/circulation/services/actualcostrecord/ActualCostRecordExpirationService.java
- src/main/java/org/folio/circulation/services/actualcostrecord/ActualCostRecordService.java
- src/main/java/org/folio/circulation/storage/mappers/ActualCostRecordMapper.java
- src/main/java/org/folio/circulation/support/AsyncCoordinationUtil.java
- src/test/java/api/loans/ExpiredActualCostRecordsProcessingTests.java
- src/test/java/api/support/matchers/ActualCostRecordMatchers.java
- src/test/java/org/folio/circulation/support/AsyncCoordinationUtilTest.java
- Change status of Actual Cost Record from `Open` to `Expired` once it is processed
- Process only records in status `Open`, ignore all others
[CIRC-1649](https://issues.folio.org/browse/CIRC-1649)
> CIRC-1649: Update actual cost record status upon expiration

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/RequestQueue.java
- src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/fixtures/ItemsFixture.java
- src/test/java/org/folio/circulation/domain/RequestQueueTests.java
Resolves: [CIRC-1669](https://issues.folio.org/browse/CIRC-1669)
> [CIRC-1669] Release 23.1.6

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/RequestQueue.java
- src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/fixtures/ItemsFixture.java
- src/test/java/org/folio/circulation/domain/RequestQueueTests.java
Resolves: [CIRC-1664](https://issues.folio.org/browse/CIRC-1664)
> [CIRC-1664] Release v23.3.1

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/rules/Drools.java
- src/main/java/org/folio/circulation/rules/cache/CirculationRulesCache.java
- src/test/java/org/folio/circulation/rules/Text2DroolsTest.java
- src/test/java/org/folio/circulation/rules/cache/CirculationRulesCacheTest.java
Resolves: [CIRC-1678](https://issues.folio.org/browse/CIRC-1678)
> [CIRC-1678] Release v23.1.7

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/rules/Drools.java
- src/main/java/org/folio/circulation/rules/cache/CirculationRulesCache.java
- src/test/java/org/folio/circulation/rules/Text2DroolsTest.java
- src/test/java/org/folio/circulation/rules/cache/CirculationRulesCacheTest.java
https://issues.folio.org/browse/CIRC-1681
> CIRC-1681: Release mod-circulation v23.3.2

- descriptors/ModuleDescriptor-template.json
[CIRCSTORE-353](https://issues.folio.org/browse/CIRCSTORE-353) introduced a breaking change by making request status a required property. Update versions of interfaces impacted by this change.
Resolves [CIRC-1685](https://issues.folio.org/browse/CIRC-1685)
> CIRC-1685: Update versions of interfaces request-storage and request-storage-bacth

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/fixtures/AgeToLostFixture.java
Resolves: [CIRC-1689](https://issues.folio.org/browse/CIRC-1689)
> [CIRC-1689] Release 23.1.8

- pom.xml
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/representations/ItemsInTransitReport.java
- src/main/java/org/folio/circulation/services/ItemsInTransitReportService.java
- src/test/java/api/requests/ItemsInTransitReportTests.java
- Fix NPE for In transit report;
- Add exceptions logging;
Resolves: [CIRC-1675](https://issues.folio.org/browse/CIRC-1675)
> [CIRC-1675] Fix NPE for In transit report processing

- pom.xml
https://issues.folio.org/browse/CIRC-1645
> CIRC-1645: Add missing dependency for logging

- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/representations/CheckInByBarcodeResponse.java
- src/main/java/org/folio/circulation/infrastructure/storage/users/PatronGroupRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/users/UserRepository.java
- src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/main/java/org/folio/circulation/resources/PickSlipsResource.java
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/requests/PickSlipsTests.java
Add the field "requester.patronGroup" to the Requester Object in the Staff Slip context
https://issues.folio.org/browse/CIRC-1578
Determined the Patron Group via the patron group ID and set it in the requester's context json. 
Async program handling of completableFuture result that is returned to set the value in patronGroup.
##Code coverage on the new lines 
##Evidence 
{"pickSlips":[{"item":{"title":"The Long Way to a Small, Angry Planet","primaryContributor":"Chambers, Becky","allContributors":"Chambers, Becky","barcode":"036000291452","status":"Paged","enumeration":null,"volume":null,"chronology":null,"yearCaption":"","materialType":"Book","loanType":"Can Circulate","copy":"","numberOfPieces":null,"descriptionOfPieces":null,"effectiveLocationSpecific":"3rd …
> CIRC-1578 - Add the field "requester.patronGroup" to the Requester Object in the Staff Slip context

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/fixtures/AgeToLostFixture.java
Resolves: [CIRC-1722](https://issues.folio.org/browse/CIRC-1722)
> [CIRC-1722] Release 23.3.3

- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/services/LostItemFeeChargingService.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundContext.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
- src/test/java/api/loans/DeclareLostAPITests.java
- src/test/resources/log4j2-test.properties
Existing open actual cost record (lost item fee with actual cost) for the loan must be cleared when declaring item lost.
Resolves [CIRC-1711](https://issues.folio.org/browse/CIRC-1711)
> CIRC-1711: Cancel actual cost lost item fees when declaring item lost

- src/test/java/api/loans/DeclareLostAPITests.java
- src/test/java/api/support/matchers/LoanAccountMatcher.java
- src/test/resources/log4j2-test.properties
When loan is aged to lost, and an open actual cost record exists for it, declaring such item lost must cancel the actual cost record regardless of fee refund interval configured in Lost Item Fee Policy. Change existing test to reflect this.
Resolves [CIRC-1711](https://issues.folio.org/browse/CIRC-1711)
> CIRC-1711: Actual cost record must be cancelled regardless of fee refund interval

- src/main/java/org/folio/circulation/domain/representations/anonymization/AnonymizeLoansRepresentation.java
- src/test/java/org/folio/circulation/domain/representations/anonymization/AnonymizeLoansRepresentationTest.java
[CIRC-1731](https://issues.folio.org/browse/CIRC-1731)
Address review comment for https://github.com/folio-org/mod-circulation/pull/1243 - test public method instead of private
> CIRC-1731 Use public AnonymizeLoansRepresentation::from method for test

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/OpeningDay.java
- src/main/java/org/folio/circulation/domain/OverduePeriodCalculatorService.java
- src/main/java/org/folio/circulation/domain/policy/library/LibraryTimetableConverter.java
- src/test/java/api/loans/CheckOutCalculateDueDateTests.java
- src/test/java/api/loans/CheckOutCalculateOffsetTimeTests.java
- src/test/java/org/folio/circulation/domain/OpeningDayTest.java
https://issues.folio.org/browse/CIRC-1742
Release mod-circulation v23.3.4
> [CIRC-1742] Hotfix release 23.3.4

- NEWS.md
- pom.xml
Resolves: [CIRC-1744](https://issues.folio.org/browse/CIRC-1744) Release mod-circulation 23.5.0
[BE release procedure](https://docs.google.com/document/d/1044I8jehoiu243BQ8GIUWCprdIYiDLqBEu5BZMjmCs0/edit)
> CIRC-1744: Release 23.5.0

- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/test/java/api/support/fixtures/TemplateContextMatchers.java
https://issues.folio.org/browse/CIRC-1580
> CIRC-1580: Fee amount tokens not showing 2nd decimal in automated notices, if 2nd decimal = 0 / For 2 other tokens

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/RequestQueue.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/fixtures/UsersFixture.java
https://issues.folio.org/browse/CIRC-1763
> Bugfix release 23.5.3

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/StoreLoanAndItem.java
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
- src/main/java/org/folio/circulation/resources/DeclareLostResource.java
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/main/java/org/folio/circulation/services/DeclareLostContext.java
- src/main/java/org/folio/circulation/services/DeclareLostItemFeeRefundService.java
- src/main/java/org/folio/circulation/services/DeclareLostService.java
- src/main/java/org/folio/circulation/services/LostItemFeeChargingService.java
- src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
- src/test/java/api/loans/DeclareLostAPITests.java
- src/test/java/api/queue/RequestQueueResourceTest.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIUpdatingTests.java
- src/test/java/api/support/builders/ItemBuilder.java
- src/test/java/api/support/fixtures/UsersFixture.java
https://issues.folio.org/browse/CIRC-1764
> Bugfix release 23.5.4

- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- fix NPE during item context creation for check-in;
Resolves: [CIRC-1797](https://issues.folio.org/browse/CIRC-1797)
> [CIRC-1797] Fix NPE for item context creation

- descriptors/ModuleDescriptor-template.json
- increase request-storage interface version;
Resolves: [CIRC-1800](https://issues.folio.org/browse/CIRC-1800l)
> [CIRC-1800] Increase request-storage interface version

- src/main/java/org/folio/circulation/resources/CirculationRulesReloadResource.java
- src/main/java/org/folio/circulation/rules/cache/CirculationRulesCache.java
Fixing two code smells introduced in the PR for CIRC-1783
> fixing code smells

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/CirculationVerticle.java
- src/main/java/org/folio/circulation/resources/CirculationRulesReloadResource.java
- src/main/java/org/folio/circulation/resources/CirculationRulesResource.java
- src/main/java/org/folio/circulation/rules/cache/CirculationRulesCache.java
- src/main/java/org/folio/circulation/rules/cache/Rules.java
- src/test/java/api/CirculationRulesEngineAPITests.java
- src/test/java/api/support/fixtures/CirculationRulesFixture.java
- src/test/java/api/support/http/InterfaceUrls.java
Resolves: [CIRC-1844](https://issues.folio.org/browse/CIRC-1844)
> [CIRC-1844] Release v23.3.5

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/CirculationVerticle.java
- src/main/java/org/folio/circulation/resources/CirculationRulesReloadResource.java
- src/main/java/org/folio/circulation/resources/CirculationRulesResource.java
- src/main/java/org/folio/circulation/rules/cache/CirculationRulesCache.java
- src/main/java/org/folio/circulation/rules/cache/Rules.java
- src/test/java/api/CirculationRulesEngineAPITests.java
- src/test/java/api/support/fixtures/CirculationRulesFixture.java
- src/test/java/api/support/http/InterfaceUrls.java
Resolves: [CIRC-1845](https://issues.folio.org/browse/CIRC-1845)
> [CIRC-1845] Release v23.5.5

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/test/java/api/requests/RequestsAPICreationTests.java
To release Release mod-circulation - Orchid CSP #3 for CIRC-1832
> [CIRC-1843] Release v23.5.6

- descriptors/ModuleDescriptor-template.json
Fix incorrect permission used in timer `/circulation/rules-reload`.
Resolves [CIRC-1860](https://issues.folio.org/browse/CIRC-1860).
Use permission for reading circulation rules: `circulation-storage.circulation-rules.get` (mod-circulation-storage) instead of `circulation.rules.get` (mod-circulation).
> CIRC-1860: Use correct permission for circulation rules reload

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[CIRC-1864](https://issues.folio.org/browse/CIRC-1864)
> Bugfix release 23.5.7

- src/main/java/org/folio/circulation/domain/RequestServiceUtility.java
- src/test/java/api/requests/RequestsAPICreationTests.java
Spelling of the error message "One or more Pickup Locations are no longer available" must be changed to "One or more Pickup locations are no longer available" ("Locations" -> "locations").
Resolves [CIRC-1877](https://issues.folio.org/browse/CIRC-1877).
> CIRC-1877: Fix spelling of error message

- src/main/java/org/folio/circulation/CirculationVerticle.java
- src/main/java/org/folio/circulation/support/logging/LogHelper.java
Add support for logging variables such as `requestId`, `userId` and `tenantId`.
Resolves [CIRC-1709](https://issues.folio.org/browse/CIRC-1709).
Fill logging context (provided by RMB) manually for every request.
> CIRC-1709: Add support for logging variables

- descriptors/ModuleDescriptor-template.json
CIRC-1848 Add missing permission for add-info endpoint to work
Fix bug for not admin users
> CIRC-1848 Add missing permission for add-info endpoint to work

- src/main/java/org/folio/circulation/rules/Drools.java
Resolves: [CIRC-1809](https://issues.folio.org/browse/CIRC-1809)
> [CIRC-1809] Update logging for Drools

- src/main/java/org/folio/circulation/rules/NameConverter.java
- src/main/java/org/folio/circulation/rules/RulesExecutionParameters.java
- src/main/java/org/folio/circulation/rules/Text2Drools.java
Cover org.folio.circulation.rules by logging in alphabetical order, from Institution.java to Text2Drools.java
Resolves: [CIRC-1881](https://issues.folio.org/browse/CIRC-1881)
> [CIRC-1881] Add logging to rules package

- descriptors/ModuleDescriptor-template.json
[CIRC-1914](https://issues.folio.org/browse/CIRC-1914)
> CIRC-1914: Update 'feesfines' interface version to 19.0

- src/main/java/org/folio/circulation/domain/ConfigurationService.java
- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/support/utils/LogUtil.java
[CIRC-1813](https://issues.folio.org/browse/CIRC-1813)
> CIRC-1813: Logging in org.folio.circulation.domain package

- descriptors/ModuleDescriptor-template.json
Revert changes in timer for scheduled age-to-lost fee charging introduced in #1338 as they were made unintentionally and are breaking expected behavior.
Resolves [CIRC-1947](https://issues.folio.org/browse/CIRC-1947).
> CIRC-1947: Revert changes in timer for scheduled-age-to-lost-fee-charging

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Resolves [CIRC-1948](https://issues.folio.org/browse/CIRC-1948).
> CIRC-1948: Bugfix release 24.0.2 (Poppy R2 2023 Bugfix)

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/requests/PickSlipsTests.java
- src/test/java/api/support/fixtures/AddressExamples.java
> Bugfix release 24.0.3

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[CIRC-1957](https://issues.folio.org/browse/CIRC-1957)
Includes [CIRC-1953](https://issues.folio.org/browse/CIRC-1953) (#1362)
> CIRC-1957: Bugfix release 24.0.4

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/MoveRequestProcessAdapter.java
- src/main/java/org/folio/circulation/domain/MoveRequestService.java
- src/main/java/org/folio/circulation/domain/MultipleRecords.java
- src/main/java/org/folio/circulation/domain/OpeningDay.java
- src/main/java/org/folio/circulation/domain/OverdueFineService.java
- src/main/java/org/folio/circulation/domain/OverduePeriodCalculatorService.java
- src/main/java/org/folio/circulation/domain/ProxyRelationship.java
- src/main/java/org/folio/circulation/domain/RequestServiceUtility.java
- src/main/java/org/folio/circulation/domain/StoredRequestRepresentation.java
- src/main/java/org/folio/circulation/domain/UpdateItem.java
- src/main/java/org/folio/circulation/domain/UpdateLoan.java
- src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
- src/main/java/org/folio/circulation/domain/UpdateRequestService.java
- src/main/java/org/folio/circulation/support/http/client/Response.java
Improve logging in org.folio.circulation.domain from MaterialType to UserManualBlock in alphabetic order
Resolves: [CIRC-1910](https://issues.folio.org/browse/CIRC-1910)
> [CIRC-1910] Logging - circulation domain (M - U)

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
- src/main/java/org/folio/circulation/support/Clients.java
- src/main/java/org/folio/circulation/support/CollectionResourceClient.java
- src/main/java/org/folio/circulation/support/SingleRecordFetcher.java
- src/test/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepositoryTests.java
Covers: [CIRC-1907](https://issues.folio.org/browse/CIRC-1907)
Purpose
The main goal of this PR is to implement changes to get Virtual DCB items from mod-circulation-item during checkin/checkout process
Approach
Implemented a new repository, and during checkin/checkout processes if an item is not found in mod-inventory search for an item in mod-circulation-item
Learning
Please review [UXPROD-4325](https://issues.folio.org/browse/UXPROD-4325)
> CIRC-1907 Check in/Check out for the virtual item

- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/requests/PickSlipsTests.java
- src/test/java/api/support/fixtures/AddressExamples.java
The purpose of this PR is to revert code changes for staff slips as it was before working as expected. The country name will be needed to be fixed for only notice that is taken care in CIRC-1931
> [CIRC-1955] - Revert country name changes for staff slips.

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/requests/PickSlipsTests.java
- src/test/java/api/support/fixtures/AddressExamples.java
To release 24.0.5 for poppy bugfix.
> CIRC-1967 - Release 24.0.5

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/LoanHistory.java
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/schedule/FeeFineScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/LoanScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/domain/notice/schedule/RequestScheduledNoticeHandler.java
- src/main/java/org/folio/circulation/infrastructure/storage/loans/LoanHistoryRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/loans/LoanRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/sessions/PatronActionSessionRepository.java
- src/main/java/org/folio/circulation/resources/ChangeDueDateResource.java
- src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
- src/main/java/org/folio/circulation/resources/LoanNoticeSender.java
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/main/java/org/folio/circulation/support/Clients.java
- src/test/java/api/loans/AgedToLostScheduledNoticesProcessingTests.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java
- src/test/java/api/loans/DueDateScheduledNoticesProcessingTests.java
- src/test/java/api/loans/EndExpiredPatronActionSessionTests.java
- src/test/java/api/loans/OverdueFineScheduledNoticesProcessingTests.java
- src/test/java/api/loans/OverrideRenewByBarcodeTests.java
- src/test/java/api/loans/PatronActionSessionTests.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
- src/test/java/api/loans/scenarios/ChangeDueDateByReplacingLoanTests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/fixtures/TemplateContextMatchers.java
Re-apply loan.additionalInfo to notice contexts, as per CIRC-1793, only without invocation of thread blocking join() method, ref CIRC-1942.
> CIRC-1946 Add field, "loan.additionalInfo" to  notice context

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/services/EventPublisher.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
Resolves: [CIRC-1950](https://issues.folio.org/browse/CIRC-1950)
> [CIRC-1950] Release v24.0.7

- src/main/java/org/folio/circulation/EventConsumerVerticle.java
- src/main/java/org/folio/circulation/services/events/UniqueKafkaModuleIdProvider.java
Add more logging to #1371.
[CIRC-1958](https://issues.folio.org/browse/CIRC-1958)
> CIRC-1958: Additional logging

- NEWS.md
- pom.xml
> Bugfix release 24.0.9

- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
CIRC-1966
If mod-circulation-item is not enable for the tenant then there might be a search failure for an item . So in this PR we are returning a success empty response .
> [CIRC-1966]-Added validation

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
- src/main/java/org/folio/circulation/support/Clients.java
- src/test/java/api/loans/LoanAPITests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/builders/CirculationItemsBuilder.java
- src/test/java/api/support/fakes/FakeOkapi.java
- src/test/java/api/support/fixtures/CirculationItemsFixture.java
- src/test/java/api/support/http/InterfaceUrls.java
- src/test/java/api/support/http/ResourceClient.java
- src/test/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepositoryTests.java
* [CIRC-1966]-Added intigration with mod-circulation-item
* [CIRC-1966]-Added intigration with mod-circulation-item
* [CIRC-1966]-Added intigration with mod-circulation-item
* [CIRC-1966]-Added intigration with mod-circulation-item
> [CIRC-1966]-Added integration with mod-circulation-item (#1379)

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/test/java/api/requests/PickSlipsTests.java
- src/test/java/api/support/builders/UserBuilder.java
- src/test/java/api/support/fixtures/AddressExamples.java
> CIRC-1996 - Release mod-circulation for 24.0.11

- src/main/java/org/folio/circulation/domain/CheckInContext.java
- src/main/java/org/folio/circulation/domain/representations/logs/CirculationCheckInCheckOutLogEventMapper.java
- src/main/java/org/folio/circulation/domain/representations/logs/LogEventPayloadField.java
- src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
- src/test/java/api/support/matchers/EventMatchers.java
In order to fix MODAUD-176 tenant's timezone value is required to convert the return date and system return date and then compare it to created the backdate description in circ log.
Added timezone in the payload before being sent to mod-audit for creating circ log entries.
> CIRC-2006 - Add tenant's timezone in the payload that will be used to create circ log entries.

- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
> [CIRC-1988-1]-Added fix

- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/support/APITests.java
Covers: [CIRC-1988](https://issues.folio.org/browse/CIRC-1988)
Add unit tests for covering DCB changes
> CIRC-1988 Unit tests for DCB changes

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/infrastructure/storage/SettingsRepository.java
- src/test/java/org/folio/circulation/infrastructure/storage/SettingsRepositoryTest.java
> CIRC-2027 - Release mod-circulation for 24.0.12

- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/domain/RequestRepresentation.java
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/representations/ItemSummaryRepresentation.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/LoanAPITests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/builders/CirculationItemsBuilder.java
- src/test/java/api/support/fixtures/CirculationItemsFixture.java
The purpose of the PR is to implement https://folio-org.atlassian.net/browse/CIRC-2029
The approach we followed is we are checking that the item is a dcbItem and if it is a dcb item, we return the dcbItem title instead of umbrella instance title. We are returning dcbItem title for loan,request,checkin,checkout and staffslipcontext responses.
> CIRC-2029 Returning DCB title in response if the item is a virtual item

- pom.xml
The purpose of the jira is to bump the version from 24.1.0-SNAPSHOT to 24.2.0-SNAPSHOT
> Bump the version to 24.2.0-SNAPSHOT

- src/main/java/org/folio/circulation/domain/Item.java
- src/main/java/org/folio/circulation/domain/RequestRepresentation.java
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/representations/ItemSummaryRepresentation.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/loans/LoanAPITests.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/builders/CirculationItemsBuilder.java
- src/test/java/api/support/fixtures/CirculationItemsFixture.java
> CIRC-2029 Returning DCB title in response if item is a virtual item

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/HoldingsRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/InstanceRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/LoanTypeRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/MaterialTypeRepository.java
- src/main/java/org/folio/circulation/support/FindByIdsAndCombine.java
- src/main/java/org/folio/circulation/support/FindWithMultipleCqlIndexValues.java
- src/main/java/org/folio/circulation/support/fetching/CqlIndexValuesFinder.java
- src/main/java/org/folio/circulation/support/fetching/CqlResultCombiner.java
- src/main/java/org/folio/circulation/support/fetching/FetchUtil.java
- src/main/java/org/folio/circulation/support/fetching/RecordFetching.java
- src/test/java/org/folio/circulation/support/fetching/CqlResultCombinerTest.java
Resolves: [CIRC-2039](https://folio-org.atlassian.net/browse/CIRC-2039?atlOrigin=eyJpIjoiYTUwMjc5ZWE4OGUzNDdhNmI2YjNlYmQwNDUwOWVlNjkiLCJwIjoiaiJ9)
> [CIRC-2039]Release v24.1.1

- pom.xml
- src/test/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClientTests.java
[CIRC-2048](https://folio-org.atlassian.net/browse/CIRC-2048)
Upgrade RMB to 35.2.0, Vertx to 4.5.5, Spring to 6.1.5
> CIRC-2048 Upgrade RMB to 35.2.0

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/CIRC-2070
Add missing permissions (overdue-fines-policies.item.get)
> CIRC-2070 Add missing permissions

- descriptors/ModuleDescriptor-template.json
- ramls/circulation.raml
- src/main/java/org/folio/circulation/domain/AllowedServicePointsRequest.java
- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestPolicyRepository.java
- src/main/java/org/folio/circulation/resources/AllowedServicePointsResource.java
- src/main/java/org/folio/circulation/services/AllowedServicePointsService.java
- src/test/java/api/requests/AllowedServicePointsAPITests.java
Revert adding useStubItem parameter to allowed-service-point endpoint
> [CIRC-2050] Revert adding useStubItem parameter to allowed-service-points

- src/main/java/org/folio/circulation/services/CloseLoanWithLostItemService.java
- src/test/java/api/handlers/CloseDeclaredLostLoanWhenLostItemFeesAreClosedApiTests.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/api/support/fixtures/FeeFineAccountFixture.java
- src/test/java/api/support/matchers/AccountMatchers.java
[CIRC-2066](https://folio-org.atlassian.net/browse/CIRC-2066)
> CIRC-2066: Ignore "Loan related fee/fine closed" events when loan is already closed

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/main/java/org/folio/circulation/services/CloseLoanWithLostItemService.java
- src/test/java/api/handlers/CloseDeclaredLostLoanWhenLostItemFeesAreClosedApiTests.java
- src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
- src/test/java/api/loans/scenarios/CheckoutWithRequestScenarioTests.java
- src/test/java/api/support/builders/CheckOutByBarcodeRequestBuilder.java
- src/test/java/api/support/fixtures/FeeFineAccountFixture.java
- src/test/java/api/support/fixtures/RequestPoliciesFixture.java
- src/test/java/api/support/matchers/AccountMatchers.java
Resolves: [CIRC-2074](https://folio-org.atlassian.net/browse/CIRC-2074)
> [CIRC-2074] Release 24.2.2

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
- src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
- src/test/java/api/requests/scenarios/MoveRequestPolicyTests.java
Resolves: [CIRC-2079](https://folio-org.atlassian.net/browse/CIRC-2079)
> [CIRC-2079] Release 24.2.3

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/LoanRepresentation.java
- src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledDigitalReminderHandler.java
- src/main/java/org/folio/circulation/domain/validation/RenewalOfItemsWithReminderFeesValidator.java
- src/main/java/org/folio/circulation/resources/RenewalValidator.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/test/java/api/loans/OverrideRenewByBarcodeTests.java
- src/test/java/api/loans/ReminderFeeTests.java
- src/test/java/api/requests/RequestsAPILoanRenewalTests.java
Resolves: [CIRC-2080](https://folio-org.atlassian.net/browse/CIRC-2080)
> Tmp release 24.2.4

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/EventConsumerVerticle.java
- src/main/java/org/folio/circulation/services/events/UniqueKafkaModuleIdProvider.java
Resolves: [CIRC-2085](https://folio-org.atlassian.net/browse/CIRC-2085)
> [CIRC-2085] Release 24.2.5

- src/main/java/org/folio/circulation/resources/AllowedServicePointsResource.java
- src/test/java/api/requests/AllowedServicePointsAPITests.java
Sort allowed service points by name.
[CIRC-2094](https://folio-org.atlassian.net/browse/CIRC-2094)
> CIRC-2094: Sort allowed service points by name

- descriptors/ModuleDescriptor-template.json
[CIRC-2095](https://folio-org.atlassian.net/browse/CIRC-2095)
> CIRC-2095: Update interface holdings-storage to version 7.0

- src/test/java/api/settings/CirculationSettingsTests.java
Purpose of the pr -  https://folio-org.atlassian.net/browse/CIRC-2096 
added a test a case related to enableRequestPrintDetailsSetting, which includes persisting , getting and updating the print setting
> CIRC-2096 added test case on enableRequestPrintDetailsSetting

- src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/support/fixtures/RecordCreator.java
- src/test/java/api/support/fixtures/ServicePointsFixture.java
[CIRC-1980](https://folio-org.atlassian.net/browse/CIRC-1980)
Fix intervalId absence in hold shelf expiry period
> CIRC-1980: Error message - after Service point changed from "yes" to "no" as Pickup location

- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestQueueRepository.java
- src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
- src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
- src/main/java/org/folio/circulation/resources/RequestQueueResource.java
- src/main/java/org/folio/circulation/services/RequestQueueService.java
- src/main/java/org/folio/circulation/support/http/client/CqlQuery.java
- src/test/java/api/loans/CheckOutByBarcodeTests.java
- src/test/java/api/support/builders/InstanceBuilder.java
- src/test/java/api/support/fixtures/CirculationItemsFixture.java
- src/test/java/org/folio/circulation/support/http/client/CqlQueryTests.java
Primary ECS request is not updated upon check-in and check-out of the circulation item, because circulation item is belongs to a fake DCB instance. And since primary request and the corresponding circulation item have different `instanceId`, the request is ignored when check-in and check-out process tries to fetch request queue for the item. In order to fix this, we need search title-level requests by both `instanceId` and `itemId`.
> CIRC-2125: Search title-level requests by both `itemId` and `instanceId` during check-in and check-out

- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/domain/RequestServiceUtility.java
- src/test/java/api/requests/RequestsAPICreationTests.java
Error appears when attempting to save request with delivery to allowed Service Points
check if fulfillment preference is Delivery
Resolves: [CIRC-2122](https://folio-org.atlassian.net/browse/CIRC-2122)
> CIRC-2122 Bypass pickup SP check for Delivery requests

- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/domain/EcsRequestPhase.java
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/domain/representations/RequestProperties.java
- src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/main/java/org/folio/circulation/services/ItemForTlrService.java
- src/main/java/org/folio/circulation/storage/ItemByInstanceIdFinder.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/requests/RequestsAPIRetrievalTests.java
- src/test/java/api/support/APITestContext.java
- src/test/java/api/support/builders/RequestBuilder.java
- src/test/java/api/support/fakes/FakeOkapi.java
- src/test/java/api/support/fakes/FakeSearchModule.java
CIRC-2151
Allow to create an ECS TLR Primary phase request.
Validation skipped in order to allow to create a Primary phase ECS TLR request:
- Request policy validation
- Searching for the closest item to the pickup service point
> CIRC-2151 Skip some validation

- descriptors/ModuleDescriptor-template.json
[CIRC-2153](https://folio-org.atlassian.net/browse/CIRC-2153)
> CIRC-2153: Add support for interface instance-storage 11.0

- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/main/java/org/folio/circulation/resources/context/StaffSlipsContext.java
Resolves: [CIRC-2134](https://folio-org.atlassian.net/browse/CIRC-2134)
> [CIRC-2134] Fix typo in StaffSlipsContext

- NEWS.md
- descriptors/ModuleDescriptor-template.json
[CIRC-2156](https://folio-org.atlassian.net/browse/CIRC-2156)
Upgrade the API version in the ModuleDescriptor-template.json:
- `holdings-storage 8.0`
> [CIRC-2156] Upgrade the API version in the ModuleDescriptor-template.json

- NEWS.md
- pom.xml
[CIRC-2136](https://folio-org.atlassian.net/browse/CIRC-2136)
> CIRC-2161 Release mod-circulation v24.3.0

- pom.xml
CIRC-2161 (Ramsons release)
Fix snapshot version 
Change version in POM file from the next bugfix release to the next feature release
> CIRC-2161 Fix snapshot version

- descriptors/ModuleDescriptor-template.json
CIRC-2185
Fix automated patron blocks permission issue
> CIRC-2185 Fix automated patron blocks permission issue

- descriptors/ModuleDescriptor-template.json
- pom.xml
CIRC-2185
Add permission blocks to the descriptor
> CIRC-2185 Add mod-settings permission blocks

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/test/java/api/requests/RequestsAPICreationTests.java
> Release 24.3.1

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/domain/CreateRequestService.java
- src/main/java/org/folio/circulation/domain/EcsRequestPhase.java
- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestPolicyRepository.java
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/main/java/org/folio/circulation/rules/ExecutableRules.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/org/folio/circulation/infrastructure/storage/requests/RequestPolicyRepositoryTest.java
Resolves: [CIRC-2200](https://folio-org.atlassian.net/browse/CIRC-2200)
> CIRC-2200 Release 24.3.3

- descriptors/ModuleDescriptor-template.json
[CIRC-2205](https://folio-org.atlassian.net/browse/CIRC-2205)
> CIRC-2205: Remove redundant permission set declarations

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Resolves: [CIRC-2208](https://folio-org.atlassian.net/browse/CIRC-2208)
> [CIRC-2208] Release 24.3.4

- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/test/java/api/requests/StaffSlipsTests.java
Resolves: [CIRC-2197](https://folio-org.atlassian.net/browse/CIRC-2197)
> CIRC-2197 Fix search slips for requests queue

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/test/java/api/requests/StaffSlipsTests.java
Resolves: [CIRC-2217](https://folio-org.atlassian.net/browse/CIRC-2217)
> CIRC-2217 Release 24.3.5

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/domain/RequestRepresentation.java
- src/main/java/org/folio/circulation/domain/StoredRequestRepresentation.java
- src/test/java/api/queue/RequestQueueResourceTest.java
- src/test/java/api/requests/RequestsAPICreationTests.java
- src/test/java/api/support/builders/ItemBuilder.java
- src/test/java/api/support/builders/RequestBuilder.java
> To release 24.3.7

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/SlipsResource.java
Resolves: [CIRC-2221](https://folio-org.atlassian.net/browse/CIRC-2221)
> CIRC-2221 Release 24.3.8

- pom.xml
- ramls/request.json
- src/main/java/org/folio/circulation/domain/Request.java
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/test/java/org/folio/circulation/resources/RequestNoticeSenderTest.java
> Merge the changes for UXPROD-5001

- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/test/java/api/requests/StaffSlipsTests.java
To fix the issue as mentioned here https://folio-org.atlassian.net/browse/UIREQ-1261?focusedCommentId=251374
While determining the pickslips for TLR and ILR the same request ID was being fetched because a Where clause was missing for requestLevel=Item for ILR same is present for TLR. Added this where clause for the request type as Page.
> CIRC-2265 - Fix duplicate request ID for pickslips

- src/main/java/org/folio/circulation/domain/UpdateRequestService.java
- src/main/java/org/folio/circulation/domain/validation/RequestValidator.java
- src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
- src/test/java/org/folio/circulation/resources/RequestNoticeSenderTest.java
[CIRC-2269](https://folio-org.atlassian.net/browse/CIRC-2269)
> CIRC-2269: [ECS TLR] Send request create notification when the patron is resolved

- pom.xml
> Update pom.xml version

- Dockerfile
- Jenkinsfile
- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/rules/Drools.java
> FOLREL-712 - Java and RMB version upgrade

- pom.xml
- src/test/java/api/support/fixtures/TemplateContextMatchers.java
https://folio-org.atlassian.net/browse/CIRC-2287
Update mod-pubsub client dependency to the latest release version (already upgraded to Java 21).
> CIRC-2287 Update mod-pubsub client

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/domain/mapper/InventoryMapper.java
- src/main/java/org/folio/circulation/domain/mapper/RequestMapper.java
- src/main/java/org/folio/circulation/domain/mapper/StaffSlipMapper.java
- src/main/java/org/folio/circulation/domain/mapper/UserMapper.java
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/combiner/LoanNoticeContextCombiner.java
- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/main/java/org/folio/circulation/resources/context/StaffSlipsContext.java
- src/main/java/org/folio/circulation/services/RequestFetchService.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/requests/StaffSlipsTests.java
https://folio-org.atlassian.net/browse/CIRC-2228
1. Split slip results mapping to separate classes.
2. Write item.title in response when instance is not null
3. Add more logging.
> CIRC-2228: TLRs in Search slips missing key tokens

- NEWS.md
- README.md
- pom.xml
- src/main/java/org/folio/Environment.java
- src/main/java/org/folio/circulation/CirculationVerticle.java
- src/test/java/org/folio/circulation/EnvironmentTest.java
Resolves: [CIRC-2311](https://folio-org.atlassian.net/browse/CIRC-2311)
> CIRC-2311 Release 24.3.14

- descriptors/ModuleDescriptor-template.json
[CIRC-2290](https://folio-org.atlassian.net/browse/CIRC-2290)
> CIRC-2290: Add missing permissions for GET /circulation/loans/{id}

- src/main/java/org/folio/circulation/domain/policy/FixedScheduleCheckOutDueDateStrategy.java
- src/main/java/org/folio/circulation/domain/policy/FixedScheduleRenewalDueDateStrategy.java
- src/main/java/org/folio/circulation/support/results/CommonFailures.java
- src/test/java/org/folio/circulation/domain/policy/FixedScheduleCheckOutDueDateStrategyTest.java
- src/test/java/org/folio/circulation/domain/policy/FixedScheduleRenewalDueDateStrategyTest.java
https://folio-org.atlassian.net/browse/CIRC-2212
Add logging for all internal server errors caused by exceptions.
- Add logging for all internal server errors
- Refactor existing logs not to duplicate stack traces
> CIRC-2212 Update logging of internal server errors

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/domain/mapper/InventoryMapper.java
- src/main/java/org/folio/circulation/domain/mapper/RequestMapper.java
- src/main/java/org/folio/circulation/domain/mapper/StaffSlipMapper.java
- src/main/java/org/folio/circulation/domain/mapper/UserMapper.java
- src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
- src/main/java/org/folio/circulation/domain/notice/combiner/LoanNoticeContextCombiner.java
- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/main/java/org/folio/circulation/resources/context/StaffSlipsContext.java
- src/main/java/org/folio/circulation/services/RequestFetchService.java
- src/test/java/api/loans/CheckInByBarcodeTests.java
- src/test/java/api/requests/StaffSlipsTests.java
Resolves: [CIRC-2316](https://folio-org.atlassian.net/browse/CIRC-2316)
> CIRC-2316 Release 24.4.1

- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/main/java/org/folio/circulation/services/RequestFetchService.java
- src/test/java/api/requests/StaffSlipsTests.java
Fix pick slips for TLRs not having item data.
[CIRC-2317](https://folio-org.atlassian.net/browse/CIRC-2317)
> CIRC-2307: Add item data to pick slips for title level requests

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Resolves: [CIRC-2333](https://folio-org.atlassian.net/browse/CIRC-2333)
> CIRC-2333 Release v24.4.2

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/allowed-service-points.json
- src/main/java/org/folio/circulation/domain/AllowedServicePoint.java
- src/test/java/api/requests/AllowedServicePointsAPITests.java
https://folio-org.atlassian.net/browse/CIRC-2357
> Ramsons (CSP#3) release 24.3.17

- NEWS.md
- README.md
- pom.xml
- src/main/java/org/folio/Environment.java
- src/main/java/org/folio/circulation/CirculationVerticle.java
- src/main/java/org/folio/circulation/domain/OverdueFineService.java
- src/main/java/org/folio/circulation/domain/OverduePeriodCalculatorService.java
- src/main/java/org/folio/circulation/infrastructure/storage/CalendarRepository.java
- src/test/java/org/folio/circulation/EnvironmentTest.java
- src/test/java/org/folio/circulation/domain/OverdueFineServiceTest.java
- src/test/java/org/folio/circulation/domain/OverduePeriodCalculatorServiceTest.java
- src/test/java/org/folio/circulation/infrastructure/storage/CalendarRepositoryTest.java
Resolves: [CIRC-2342](https://folio-org.atlassian.net/browse/CIRC-2342)
> CIRC-2342 Release 24.4.3 

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/main/java/org/folio/circulation/services/RequestFetchService.java
- src/test/java/api/requests/StaffSlipsTests.java
Resolves: [CIRC-2362](https://folio-org.atlassian.net/browse/CIRC-2362)
> CIRC-2362 Release 24.4.4 

- README.md
- src/main/java/org/folio/Environment.java
- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/User.java
- src/main/java/org/folio/circulation/domain/representations/LoanProperties.java
- src/main/java/org/folio/circulation/domain/representations/MetadataProperties.java
- src/main/java/org/folio/circulation/infrastructure/storage/loans/LoanPolicyRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestRepository.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/builders/UserBuilder.java
- src/test/java/api/support/fixtures/UserExamples.java
- src/test/java/api/support/fixtures/UsersFixture.java
- src/test/java/api/support/fixtures/policies/PoliciesActivationFixture.java
- src/test/java/org/folio/circulation/EnvironmentTest.java
[CIRC-2344](https://folio-org.atlassian.net/browse/CIRC-2344)
> CIRC-2344: Renew ECS loan with loan policy used during check-out

- NEWS.md
- README.md
- pom.xml
- src/main/java/org/folio/Environment.java
- src/main/java/org/folio/circulation/domain/Loan.java
- src/main/java/org/folio/circulation/domain/User.java
- src/main/java/org/folio/circulation/domain/representations/LoanProperties.java
- src/main/java/org/folio/circulation/domain/representations/MetadataProperties.java
- src/main/java/org/folio/circulation/infrastructure/storage/loans/LoanPolicyRepository.java
- src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestRepository.java
- src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
- src/test/java/api/loans/RenewalAPITests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/builders/UserBuilder.java
- src/test/java/api/support/fixtures/UserExamples.java
- src/test/java/api/support/fixtures/UsersFixture.java
- src/test/java/api/support/fixtures/policies/PoliciesActivationFixture.java
- src/test/java/org/folio/circulation/EnvironmentTest.java
Resolves: [CIRC-2372](https://folio-org.atlassian.net/browse/CIRC-2372)
> CIRC-2372 Release 24.3.18 

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/test/java/api/requests/RequestsAPICreationTests.java
https://folio-org.atlassian.net/browse/CIRC-2402
> Release v24.3.20 (Ramsons CSP)

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
- src/test/java/api/requests/RequestsAPICreationTests.java
Sunflower (R1 2025) Service Patch 1
https://folio-org.atlassian.net/browse/CIRC-2404
> Sunflower release 24.4.7

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/HoldingsRepository.java
- src/test/java/org/folio/circulation/infrastructure/storage/inventory/HoldingsRepositoryTest.java
https://folio-org.atlassian.net/browse/CIRC-2418
> Release 24.4.8 (Sunflower CSP #1)

- src/main/java/org/folio/circulation/infrastructure/storage/inventory/InstanceRepository.java
- src/main/java/org/folio/circulation/resources/RequestScheduledNoticeProcessingResource.java
- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/main/java/org/folio/circulation/services/RequestFetchService.java
- src/test/java/api/requests/StaffSlipsTests.java
- src/test/java/api/support/builders/HoldingBuilder.java
https://folio-org.atlassian.net/browse/CIRC-2322
> CIRC-2322: Handle duplicates when fetching instances and holdings

- NEWS.md
- pom.xml
- src/main/java/org/folio/circulation/infrastructure/storage/inventory/InstanceRepository.java
- src/main/java/org/folio/circulation/resources/RequestScheduledNoticeProcessingResource.java
- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/main/java/org/folio/circulation/services/RequestFetchService.java
- src/test/java/api/requests/StaffSlipsTests.java
- src/test/java/api/support/builders/HoldingBuilder.java
Resolves: [CIRC-2428](https://folio-org.atlassian.net/browse/CIRC-2428)
> CIRC-2428 Release 24.4.9

- descriptors/ModuleDescriptor-template.json
Resolves: [CIRC-2410](https://folio-org.atlassian.net/browse/CIRC-2410)
> CIRC-2410 Update item-storage interface version

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/test/java/api/requests/StaffSlipsTests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/fixtures/CirculationSettingFixture.java
Resolves: [CIRC-2416](https://folio-org.atlassian.net/browse/CIRC-2416)
> CIRC-2416 Address high memory consumption if pick-slips disabled

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/circulation/resources/SlipsResource.java
- src/test/java/api/printEvents/PrintEventsTests.java
- src/test/java/api/requests/StaffSlipsTests.java
- src/test/java/api/support/APITests.java
- src/test/java/api/support/fixtures/CirculationSettingFixture.java
- src/test/java/api/support/utl/BooleanArgumentProvider.java
Resolves: [CIRC-2454](https://folio-org.atlassian.net/browse/CIRC-2454)
> CIRC-2454 Release 24.4.11
