folio-org/mod-circulation

.gitmodules
ramls/circulation.raml
ramls/schema/README.md

Move raml-util to inside the ramls directory.
Enables reliable use of pathname for $ref in schema files.

RMB-30 move raml util

---

package.json
yarn.lock

Remove yarn resolutions for marked.
The raml-1-parser now has release 1.1.40 which also moved the "marked" to its devDependencies.
Did yarn upgrade.
Further information is linked via [FOLIO-1027 comment-24942](https://issues.folio.org/browse/FOLIO-1027?focusedCommentId=24942&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24942)

FOLIO-1027 upgrade raml-cop dependencies

---

ramls/request.json

Fix regex typo. Was A-Z rather than A-F.
See #62. This was an additional one in another branch.

FOLIO-972 Fix UUID pattern A-Z

---

src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/test/java/api/loans/RenewByBarcodeTests.java
src/test/java/org/folio/circulation/domain/policy/FixedLoanPolicyRenewalDueDateCalculationTests.java

This PR changes one error message:
from:
`loan has reached it's maximum number of renewals` 
to: 
`loan has reached its maximum number of renewals`

Adjust renew error message. Part of CIRC-100

---

NEWS.md
descriptors/ModuleDescriptor-template.json

The change to `locations` involves additions of mandatory
fields, but mod-circulation only reads from the interface
so no code changes should be necessary.

Require 2.0 or 3.0 of `locations` CIRC-143

---

src/main/java/org/folio/circulation/domain/validation/ExistingOpenLoanValidator.java
src/main/java/org/folio/circulation/support/CqlHelper.java
src/main/java/org/folio/circulation/support/HttpResult.java
src/main/java/org/folio/circulation/support/ServerErrorFailure.java
src/test/java/api/support/matchers/FailureMatcher.java
src/test/java/org/folio/circulation/support/results/HttpResultAfterTests.java
src/test/java/org/folio/circulation/support/results/HttpResultAfterWhenTests.java
src/test/java/org/folio/circulation/support/results/HttpResultCombineAfterTests.java
src/test/java/org/folio/circulation/support/results/HttpResultFailAfterTests.java
src/test/java/org/folio/circulation/support/results/HttpResultFailWhenTests.java
src/test/java/org/folio/circulation/support/results/HttpResultGetValueTests.java
src/test/java/org/folio/circulation/support/results/HttpResultInitialisationTests.java
src/test/java/org/folio/circulation/support/results/HttpResultMappingTests.java
src/test/java/org/folio/circulation/support/results/HttpResultNextTests.java
src/test/java/org/folio/circulation/support/results/HttpResultNextWhenTests.java
src/test/java/org/folio/circulation/support/results/ResultExamples.java

There are some circumstances where exceptions are thrown when undertaking an asynchronous activity that never gets captured and reported, meaning that it is possible for some requests to never get a response.
This pull request aims to remove most of the opportunities for this by adding exception handling into the HttpResult class. In future, each endpoint can also include a final `exceptionally` method in the future chain as a precaution.
This also adds more tests for the HttpResult (to be renamed to Result), which should hopefully provide more examples of usage to ease familiarity.

Improve result exception handling CIRC-155 

---

src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
src/test/java/api/requests/RequestsAPIUpdatingTests.java
src/test/java/api/support/fakes/FakeOkapi.java
src/test/java/api/support/fakes/FakeStorageModule.java
src/test/java/api/support/fakes/FakeStorageModuleBuilder.java

See https://issues.folio.org/browse/CIRC-161
Request representations are augmented with information from related records. The current loan for an item is a recent addition to these.
As this information is fetched on demand and not stored, it needs to be removed from the request representation before it can be stored using the request-storage interface
This change also changes the request updating API tests to better reflect expected client behaviour (by fetching the request via `GET /circulation/requests/id` prior to attempting to update. This also helped to recreate the issue, as the request representation following creation does not include the properties that cause issues (which is a related, yet different, issue)

Remove loan from request before storage CIRC-161

---

src/main/java/org/folio/circulation/domain/LoanRepository.java
src/main/java/org/folio/circulation/domain/PatronGroupRepository.java
src/main/java/org/folio/circulation/domain/RequestRepository.java
src/main/java/org/folio/circulation/domain/ServicePointRepository.java
src/main/java/org/folio/circulation/domain/UpdateLoanActionHistory.java
src/main/java/org/folio/circulation/domain/UserRepository.java
src/main/java/org/folio/circulation/support/CollectionResourceClient.java
src/main/java/org/folio/circulation/support/CqlHelper.java
src/test/java/api/requests/RequestsAPIDeletionTests.java
src/test/java/api/requests/RequestsAPIRetrievalTests.java
src/test/java/api/support/fakes/FakeStorageModule.java

See https://issues.folio.org/browse/CIRC-165
*Purpose*
Some related record queries when fetching requests do not provide a named query CQL parameter, instead this is provided as the whole query string itself.
FOLIO collection endpoints typically ignore unexpected query string parameters, and hence treat this as a request for all records. Within small record sets, this makes this difficult to identify, as the expected records are likely found within the first page of all records, and so don't demonstrate unintended behaviour.
*Learning*
This is compounded by the CollectionResourceClient providing a method that accepts a raw query parameter string in it's entirety. This is intended for forwarding of the query string parameters sent by the client directly to storage without needing to parse …

fix invalid queries for request related records CIRC-165

---

src/main/java/org/folio/circulation/domain/LoanRepository.java
src/main/java/org/folio/circulation/support/CqlHelper.java
src/test/java/api/requests/RequestsAPIRetrievalTests.java
src/test/java/api/support/fixtures/LoansFixture.java

*Purpose*
Searching for the current loan for requested items was not working. The previous fix for the structure of the query was necessary however wasn't sufficient
*Approach*
* Check out items, in order to create open loans, in test for fetching multiple requests
* Add test that closed loans are not included when fetching multiple requests
* Introduce way of searching for any of multiple values using CQL for an index other than {{id}}
and including a prefix fragment of CQL in order to search for loans by {{itemId}} and only in the open status.

Incorrect current loan query for multiple requests CIRC-165

---

src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
src/main/java/org/folio/circulation/resources/LoanCollectionResource.java

*Purpose*
At the moment the loan is updated in storage twice during the check in API. This is incorrect, and should only be done once. Not least because only one entry in the loan action history should be created, and this is currently done via storage of the loan (with a trigger in mod-circulation-storage)
The loan must be updated after the item status is determined, as a snapshot of the status is stored with the loan, in order for it to appear in the loan action history.

Only update loan once during check in CIRC-154

---

src/main/java/org/folio/circulation/domain/FindByBarcodeQuery.java
src/main/java/org/folio/circulation/domain/FindByIdQuery.java
src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/LoanCheckInService.java
src/main/java/org/folio/circulation/domain/LoanRepository.java
src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/domain/UpdateItem.java
src/main/java/org/folio/circulation/domain/UserRelatedQuery.java
src/main/java/org/folio/circulation/domain/representations/CheckInByBarcodeRequest.java
src/main/java/org/folio/circulation/domain/validation/CommonFailures.java
src/main/java/org/folio/circulation/domain/validation/MoreThanOneLoanValidator.java
src/main/java/org/folio/circulation/domain/validation/MoreThanOneOpenLoanValidator.java
src/main/java/org/folio/circulation/domain/validation/NoLoanValidator.java
src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
src/main/java/org/folio/circulation/resources/RenewByBarcodeRequest.java
src/main/java/org/folio/circulation/resources/RenewByBarcodeResource.java
src/main/java/org/folio/circulation/resources/RenewByIdRequest.java
src/main/java/org/folio/circulation/resources/RenewByIdResource.java
src/main/java/org/folio/circulation/resources/RenewalResource.java
src/main/java/org/folio/circulation/storage/ItemByBarcodeInStorageFinder.java
src/main/java/org/folio/circulation/storage/ItemByIdInStorageFinder.java
src/main/java/org/folio/circulation/storage/SingleOpenLoanForItemInStorageFinder.java
src/test/java/org/folio/circulation/domain/validation/MoreThanOneLoanValidatorTests.java
src/test/java/org/folio/circulation/domain/validation/NoLoanValidatorTests.java

*Purpose*
Preparation for https://issues.folio.org/browse/CIRC-146
As a check in will be allowed for item which do not have an open loan, it is necessary to be able to find the item and the loan separately, so that the send step can find no loan but allow the process to continue.
These changes are the first step in preparing for that change.

Split finding single open loan CIRC-146

---

descriptors/ModuleDescriptor-template.json
ramls/check-in-by-barcode-response.json
ramls/circulation.raml
ramls/loan.json
src/main/java/org/folio/circulation/domain/representations/ItemSummaryRepresentation.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/loans/LoanAPITests.java
src/test/java/api/loans/scenarios/InTransitToHomeLocationTests.java

*Purpose*
See https://issues.folio.org/browse/CIRC-176
As it is now possible for a check in to be for an item without an associated open loan, the check in API now responds with the item separately (in `circulation 5.2`). However this item representation did not include the `ID` of the item, as previously it was within the loan which had a property for that already.
*Learnings*
* Include the ID of a related record within a summary representation, even though it is mostly redundant. This helps with inspection checks that the correct record has been included and it makes the representation more versatile. With only a very minor increase in redundant information.

Include item id for checked in item CIRC-176

---

.gitignore
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/circulation.raml
ramls/examples/override-renewal-by-barcode-request.json
ramls/override-renewal-by-barcode-request.json
src/main/java/org/folio/circulation/CirculationVerticle.java
src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/LoanRenewalService.java
src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/main/java/org/folio/circulation/domain/policy/RollingOverrideRenewalDueDateStrategy.java
src/main/java/org/folio/circulation/domain/policy/RollingRenewalDueDateStrategy.java
src/main/java/org/folio/circulation/domain/policy/RollingRenewalOverrideDueDateStrategy.java
src/main/java/org/folio/circulation/domain/representations/LoanProperties.java
src/main/java/org/folio/circulation/resources/OverrideByBarcodeRequest.java
src/main/java/org/folio/circulation/resources/OverrideRenewalByBarcodeResource.java
src/main/java/org/folio/circulation/resources/RenewByBarcodeRequest.java
src/main/java/org/folio/circulation/resources/RenewByBarcodeResource.java
src/main/java/org/folio/circulation/resources/RenewByIdRequest.java
src/main/java/org/folio/circulation/storage/SingleOpenLoanByUserAndItemBarcodeFinder.java
src/test/java/api/APITestSuite.java
src/test/java/api/loans/OverrideRenewByBarcodeTests.java
src/test/java/api/support/builders/LoanPolicyBuilder.java
src/test/java/api/support/builders/OverrideRenewalByBarcodeRequestBuilder.java
src/test/java/api/support/fixtures/LoansFixture.java
src/test/java/api/support/http/InterfaceUrls.java
test-via-okapi.sh

CIRC-174
New endpoint **POST /circulation/override-renewal-by-barcode** was implemented to give an ability to override renewal process in case it fails due to list of reasons (see story description).
Resolves: https://issues.folio.org/browse/CIRC-174
Requires updates in circulation-storage: [pull request](https://github.com/folio-org/mod-circulation-storage/pull/123)
Link to flow chart describing renewal override logic: [flow chart](https://drive.google.com/open?id=1MQqE3eJdcXlb-H8dSYul2-hyQmlANrPE)
- new resource _OverrideRenewalByBarcodeResource_ was added;
- functionality for searching loan was moved from _RenewByBarcodeResource_ to _SingleOpenLoanByUserAndItemBarcodeFinder_ for reuse purposes;
- new method _overrideRenewal()_ was added to _LoanPolicy_ class to containing override …

CIRC-174 Implementing renewal overrides

---

src/main/java/org/folio/circulation/domain/policy/FixedScheduleRenewalDueDateStrategy.java
src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/main/java/org/folio/circulation/domain/policy/RollingRenewalDueDateStrategy.java
src/main/java/org/folio/circulation/support/http/server/ValidationError.java
src/test/java/api/loans/RenewalAPITests.java
src/test/java/org/folio/circulation/domain/policy/FixedLoanPolicyRenewalDueDateCalculationTests.java
src/test/java/org/folio/circulation/domain/policy/RollingLoanPolicyRenewalDueDateCalculationTests.java

CIRC-192
Change renewal failure messages to match requirements.
Resolves: [CIRC-192](https://issues.folio.org/browse/CIRC-192)
Additional changes:
Replacing "outside of date ranges" message with different ones for fixed and rolling loan polices.
This was done to make failures distinguishable on UI.

CIRC-192 Change renewal failure messages to match requirements

---

src/main/java/org/folio/circulation/domain/CalendarRepository.java
src/test/java/api/loans/CheckOutCalculateDueDateShortTermTests.java
src/test/java/api/loans/CheckOutCalculateDueDateTests.java
src/test/java/api/loans/CheckOutCalculateOffsetTimeTests.java

1. Update `CheckOutCalculateDueDateTests` test
Tests Short-term loans for CLDDM `Move to the beginning of the next open service point hours`
were moved to `CheckOutCalculateOffsetTimeTests` test, but they were not deleted during the merger
2. Update `CheckOutCalculateOffsetTimeTests` test
Fix: Test did not take into account time outside periods

CIRC-206 Some date based unit tests fail possibly due to the time of day

---

descriptors/ModuleDescriptor-template.json
ramls/circulation.raml
ramls/examples/request.json
ramls/examples/requests.json
ramls/request.json
src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/domain/ServicePoint.java
src/main/java/org/folio/circulation/domain/TimePeriod.java
src/main/java/org/folio/circulation/domain/UpdateItem.java
src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
src/main/java/org/folio/circulation/domain/representations/RequestProperties.java
src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
src/main/java/org/folio/circulation/support/ClockManager.java
src/test/java/api/loans/scenarios/InTransitToHomeLocationTests.java
src/test/java/api/requests/scenarios/HoldShelfExpirationDateTests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/builders/ItemBuilder.java
src/test/java/api/support/builders/RequestBuilder.java
src/test/java/api/support/builders/ServicePointBuilder.java
src/test/java/api/support/fixtures/LoansFixture.java
src/test/java/api/support/fixtures/LocationsFixture.java
src/test/java/api/support/fixtures/RequestsFixture.java
src/test/java/api/support/fixtures/ServicePointExamples.java
src/test/java/api/support/fixtures/ServicePointsFixture.java

In order to complete this story, we needed to expand the `holdShelfExpirationDate` to include a time component. We also took this opportunity to update the `requestExpirationDate` to include a time component. The hold shelf expiration date is calculated using the UTC time zone.

CIRC-194 - populate hold shelf expiration date

---

descriptors/ModuleDescriptor-template.json

As this was defined incorrectly and would cause the environment builds to fail

Remove patron notice policy storage dependency CIRC-197

---

src/main/java/org/folio/circulation/domain/PatronGroupRepository.java
src/main/java/org/folio/circulation/domain/UserRepository.java
src/main/java/org/folio/circulation/support/ItemRepository.java

When there are no "Request" records for an Item, currently the code triggered a count(*) query with limit=0&offset=0 on whole item, holding-records, and instance table. Since those tables are quite large in performance testing environment, those unnecessary queries deteriorates the checkin/out related response time a lot. With this fix, the response time can be reduced about 2-3 times. While working on this, I also made similar fixes to eliminate the unnecessary count(*) query on whole users and groups table.

CIRC-250: remove unnecessary heavy count(*) query on whole item/holding/instance tables

---

src/main/java/org/folio/circulation/domain/CreateRequestService.java
src/test/java/api/requests/RequestsAPICreationTests.java

After recent changes when sending in an invalid itemID mod-circulation is not returning the message "Item is NONE" anymore, but it's still good to reorganize the validation steps to make them more logical and catch errors earlier.  Therefore, I reordered the validation steps as follows:
1. Check for item's existence
2. Check that the patron and patron group are valid
3. Check the item's status and request type against the white list

Check for Item Not Found when creating a request

---

src/main/java/org/folio/circulation/domain/LoanRepository.java
src/test/java/api/loans/scenarios/ChangeDueDateTests.java
src/test/java/api/support/builders/CheckOutByBarcodeRequestBuilder.java
src/test/java/api/support/fakes/FakeOkapi.java
src/test/java/api/support/fixtures/LoansFixture.java

*Context*
Investigation into [UIU-795](https://issues.folio.org/browse/UIU-795) revealed that this issue is caused by the check in and check out service point summary properties (provided to help the UI) are not removed before the loan is sent to storage.
*Approach*
* Demonstrate change due date behaviour in an API test
* Extend test to demonstrate this issue
* Extract methods for removing properties that should not be stored (to improve readability)
* Remove summary properties before storage
* Block summary properties in fake storage module
*Scope*
* Also includes using a known service point when checking out (it appears we don’t validate this at the moment)
*References*
[CIRC-237](https://issues.folio.org/browse/CIRC-237)
[UIU-795](https://issues.folio.org/browse/UIU-795)

Remove service point summary CIRC-237

---

pom.xml
src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/domain/UpdateItem.java
src/main/java/org/folio/circulation/domain/validation/ServicePointPickupLocationValidator.java
src/test/java/api/loans/scenarios/CheckoutWithRequestScenarioTests.java
src/test/java/api/requests/RequestsAPICreateMultipleRequestsTests.java
src/test/java/api/requests/RequestsAPICreationTests.java
src/test/java/api/requests/RequestsAPIDeletionTests.java
src/test/java/api/requests/RequestsAPILoanHistoryTests.java
src/test/java/api/requests/RequestsAPILoanRenewalTests.java
src/test/java/api/requests/RequestsAPILocationTests.java
src/test/java/api/requests/RequestsAPIProxyTests.java
src/test/java/api/requests/RequestsAPIRelatedRecordsTests.java
src/test/java/api/requests/RequestsAPIRetrievalTests.java
src/test/java/api/requests/RequestsAPITitleTests.java
src/test/java/api/requests/RequestsAPIUpdatingTests.java
src/test/java/api/requests/scenarios/RequestsForDifferentItemsTests.java
src/test/java/api/requests/scenarios/SingleClosedRequestTests.java
src/test/java/api/requests/scenarios/SingleOpenHoldShelfRequestTests.java
src/test/java/api/support/builders/RequestBuilder.java
src/test/java/api/support/http/InterfaceUrls.java
src/test/java/api/support/http/ResourceClient.java

This PR:
- Adds a validation requirement that requests to the hold shelf include a pickup service point.
- Updates tests to include a pickup service point where appropriate.
- Removes a check in UpdateItem that should no longer be possible and removed the corresponding test for the condition.

CIRC-243 Require pickup service point for hold shelf requests

---

pom.xml
src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/main/java/org/folio/circulation/domain/validation/ItemIsNotLoanableValidator.java
src/test/java/api/loans/OverrideRenewByBarcodeTests.java
src/test/java/api/loans/RenewalAPITests.java

Resolves: CIRC-251, CIRC-249
Fix bug for cases when action comment in loan record stays unchanged after renew or check-in
Block renewal for items that are not loanable
Add new renewal override case for items that are not loanable
https://issues.folio.org/browse/CIRC-251
https://issues.folio.org/browse/CIRC-249

[CIRC-251, CIRC-249] Remove action comment on renewal and check-in & Adding new renewal override case when item is not loanable

---

pom.xml
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/fakes/FakeOkapi.java

Resolves: CIRC-254
Fix patron notices tests that can fail due to the fact they are sent asynchronously 
Use [Awaitility](https://github.com/awaitility/awaitility) library in tests to wait for async action to complete
https://issues.folio.org/browse/CIRC-254
https://github.com/awaitility/awaitility

CIRC-254 Adding async asserts for check-in/check-out patron notices tests

---

src/main/java/org/folio/circulation/domain/UserRepository.java
src/main/java/org/folio/circulation/support/ItemRepository.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/support/fixtures/LoansFixture.java

CQL queries for finding either items or users by barcode are not URL encoded. This means that spaces cause the HTTP request to fail.
Reported in https://issues.folio.org/browse/CIRC-284
Encode the CQL query for only these particular operations
* Change how collection endpoint queries are performed so CQL queries have to be escaped

Escape searching by barcode CQL CIRC-284

---

pom.xml

In order to ease the challenges with upgrading libraries it is valuable to periodically upgrade them. This is also useful for addressing security issues and gain feedback about deprecation of features.
The back end java modules are intending to become compatible with Java 11 soon. This requires upgrades to some dependencies and maven plugins.
[CIRC-307](https://issues.folio.org/browse/CIRC-307)
* Enforce a minimum version of maven
* Include the maven versions plugin to determine which dependencies and plugins have upgrades 
* Upgrade to the latest release of each dependency and plugin separately
* The deprecated methods in the Vert.x HTTP client will be addressed by migrating to the web client (and changing the collection resource client to return results instead of responses)
* I didn't …

Upgrade dependencies and maven plugins CIRC-307

---

pom.xml

Something is causing drools initialisation to fail in the hosted
environments.
Experiment rolling back to the previous stable version to check if that
fixes the issue.

Downgrade Drools to 7.0.0 CIRC-309

---

src/test/java/org/folio/circulation/rules/Text2DroolsTest.java

* Test alumni in "g visitor alumni"
* Test dvd in "m book cd dvd"
There is a front-end bug:
https://issues.folio.org/browse/UICIRC-255 "Circulation Rules Editor - Error in attributes with multiple values"
The new unit tests ensure that we don't accidentally create a similar back-end bug.

Add unit tests for second and third criterium value.

---

src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
src/test/java/api/requests/InstanceRequestsAPICreationTests.java

The current instance-level request code assumes that RequestExpirationDate is there in the request body so it causes a NullPointerException when it is not present. 
Check for the property requestExpirationDate being null. If not null add it to the converted Request object.
Ideally all of the PRs involved in breaking changes would be merged in the same …

CIRC-345 - fixed defect requiring RequestExpirationDate in the instance-level Request

---

src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
src/test/java/api/loans/scenarios/ChangeDueDateTests.java
src/test/java/api/support/builders/RequestBuilder.java

See https://issues.folio.org/browse/CIRC-351 for more details
* Demonstrate the behaviour with a failing test
* Add the required check to short circuit
* The PUT `/circulation/loans/[id]` endpoint currently attempts to mimic a check out. This was convenient during the transition to the check out / check in APIs, however now it is a source of confusion and issues as it is only behaves partially similar
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

Do not attempt to check in open loan CIRC-351

---

src/main/java/org/folio/circulation/domain/InstanceRequestItemsComparer.java
src/main/java/org/folio/circulation/domain/InstanceRequestRelatedRecords.java
src/main/java/org/folio/circulation/domain/representations/RequestProperties.java
src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
src/main/java/org/folio/circulation/storage/ItemByInstanceIdFinder.java
src/test/java/api/requests/InstanceRequestsAPICreationTests.java

It was clarified that a patron cannot place multiple requests on various copies of the same title.  In this implementation we are going to validate the requester against the requests in the items' request queues.
- Added a validateRequester method to check the requesterId against the requesterIds in the requests of the request queues. If any existing request has matching requesterId, then fail the instance-level request with the message "This requester already has an open request for a copy of this title".
- Previously getting both request queues and loans were done in parallel because one wasn't depending on the other. Now there's a need to validate the requester against all instance's items' request queues, so this check has to be done first, If the validation passes then the step to …

CIRC-371: Refuse new request for patron who already placed a request on a copy of the same title

---

src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/domain/notice/NoticeContextUtil.java
src/main/java/org/folio/circulation/domain/representations/RequestProperties.java
src/test/java/api/requests/RequestsAPIUpdatingTests.java
src/test/java/api/support/fixtures/CancellationReasonsFixture.java
src/test/java/api/support/fixtures/NoticeMatchers.java

Resolves: [CIRC-357](https://issues.folio.org/browse/CIRC-357)
Request reason for cancellation token value not showing on request cancellation notice
- change the token name from `cancellationReason` to `reasonForCancellation` (to be consistent with the [UICIRC-249](https://issues.folio.org/browse/UICIRC-249))
- use cancellation reason `publicDescription` instead of `name`
- use cancellation reason `name` if `publicDescription` is not present

[CIRC-357] Fix absence of request reason for cancellation token on request cancellation notice

---

descriptors/ModuleDescriptor-template.json
ramls/circulation.raml
ramls/request-move.raml
ramls/request.json
ramls/requests-reports.raml

Resolves: [CIRC-350](https://issues.folio.org/browse/CIRC-350)
Request schema (request.json) does not include all possible statuses in "status"
Add `Closed - Unfilled` and `Closed - Pickup expired` statuses to the `request.json` schema

[CIRC-350] Add missing statuses to the request schema

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/loan.json
src/main/java/org/folio/circulation/domain/Account.java
src/main/java/org/folio/circulation/domain/AccountRepository.java
src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/LoanRepresentation.java
src/main/java/org/folio/circulation/domain/representations/LoanProperties.java
src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
src/main/java/org/folio/circulation/support/Clients.java
src/main/java/org/folio/circulation/support/JsonPropertyWriter.java
src/test/java/api/loans/LoanAPITests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/builders/AccountBuilder.java
src/test/java/api/support/fakes/FakeOkapi.java
src/test/java/api/support/http/InterfaceUrls.java
src/test/java/api/support/http/ResourceClient.java

Backend work to support inclusion of fee/fine amount on overdue loans report.
This resolves https://issues.folio.org/browse/CIRC-323
In case of  when there are multiple fees/fines assinged to a single loan, there will be multiple accounts(mod-fees-fines) returned, so the loan class has been extended with a new field that holds a collection of accounts assigned to that loan. And the resulting feefine is calculated as a sum of all the remaining amounts in those accounts.

CIRC-323 Backend: Overdue loans report (fine/fee fields)

---

src/main/java/org/folio/circulation/domain/MoveRequestService.java
src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/domain/RequestQueue.java
src/main/java/org/folio/circulation/domain/RequestServiceUtility.java
src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
src/main/java/org/folio/circulation/domain/representations/RequestProperties.java
src/test/java/api/requests/scenarios/MoveRequestTests.java

Resolves: [CIRC-395](https://issues.folio.org/browse/CIRC-395)
- new remove method on request queue
- order request queue by date and not displaceable
- updating request positions accordingly
- update source and destination request queues
- test expecting reorder
- test preventing reorder of request not displaceable

CIRC-395: Update request queue order when moving request

---

src/main/java/org/folio/circulation/domain/MoveRequestService.java
src/main/java/org/folio/circulation/domain/UpdateItem.java
src/main/java/org/folio/circulation/domain/UpdateRequestService.java
src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
src/test/java/api/requests/scenarios/ClosedRequestTests.java
src/test/java/api/requests/scenarios/MoveRequestTests.java

Resolves: [CIRC-333](https://issues.folio.org/browse/CIRC-333)
- add `onRequestQueueChanged` to `UpdateItem`
- call `onRequestQueueChanged` after move and cancel
- test `ItemStatus` change from Paged to Available on move request and queue becomes empty
- test `ItemStatus` change from Paged to Available on cancel request and queue becomes empty

CIRC-333: Change Paged Item's Status To Available When Queue is Emptied (Requests Are Cancelled or Moved)

---

descriptors/ModuleDescriptor-template.json

CIRC-409: Missing permission in module permission set for /circulation/loans 
Adding a missing permission in module permission set for /circulation/loans. 
See https://issues.folio.org/browse/CIRC-409
Added a line to ModuleDescriptor

CIRC-409: Missing permission in module permission set

---

src/test/java/api/support/fakes/FakeOkapi.java

This is an extension to the previous [fix](https://github.com/folio-org/mod-circulation/pull/318) for [CIRC-415](https://issues.folio.org/browse/CIRC-415) to disallow the unexpected property in the fake storage modules, to stop this issue from recurring.
This is another example of a common class of integration issues we have encountered with mod-circulation.
Over the longer term, there are two changes which need to happen to improve this
* Validate the loan storage schema during the API tests
* Separate the storage of loans from the core domain representation, and stop basing the representation on the business logic representation
- Does …

Disallow patron group at check out property from storage loan CIRC-415

---

src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/Request.java
src/test/java/api/requests/scenarios/MoveRequestTests.java

Preventing the displacement of a request when it is in position one of the queue and the associated item is in status PAGED.
This PR adds the `isPaged` check to an item and utilized within the Request's check for `isNotDisplaceable`. The strictness of `isNotDisplaceable` is was increased to include checks both the request's position (position 1) and the disposition of the item (`isPaged`).

Circ 416 prevent move above page

---

src/main/java/org/folio/circulation/domain/UpdateItem.java
src/test/java/api/requests/scenarios/MoveRequestTests.java

To rectify a logic error that caused an item with a status of CHECKED_OUT to have its status change to PAGED when a requests of certain types was moved onto such an items.
The addition of a check for Item Status of `AVAILABLE` during the `itemStatusOnRequestCreateOrUpdate ` determination of a new item status.

CIRC-411 Checked out item status changes when moving request

---

src/main/java/org/folio/circulation/domain/Configuration.java
src/main/java/org/folio/circulation/domain/ConfigurationRepository.java
src/main/java/org/folio/circulation/domain/ConfigurationService.java
src/main/java/org/folio/circulation/resources/ScheduledNoticeProcessingResource.java
src/test/java/api/loans/ScheduledDueDateNoticesProcessingTests.java
src/test/java/api/support/fixtures/ConfigurationExample.java

The purpose of this story is to make this parameter configurable and set 100 as default value. 
Value should be stored in mod-configuration
Resolves: [CIRC-407](https://issues.folio.org/browse/CIRC-407)

CIRC-407 Sending patron loan notices, make number of emails to be processed in a given timeframe configurable

---

src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/main/java/org/folio/circulation/domain/policy/library/ClosedLibraryStrategyService.java
src/test/java/api/loans/OverrideCheckOutByBarcodeTests.java
src/test/java/api/support/builders/LoanPolicyBuilder.java

Fixes the null pointer exception that occurs when trying to create a recall request after an overridden check out of an item that is not loanable, see [CIRC-424](https://issues.folio.org/browse/CIRC-424) for more details
* Write a test to demonstrate the failure
* Identify the cause and fix it, changing the test to a positive case at the same time
* The loan policy builder was incorrect including loan policy properties even when not loanable, this stopped the issue from being reproduce-able
* The approach to traversing JSON deep in the domain is brittle and means that it is difficult to identify these kind of issues
* Closed due date management shouldn't really be applied unless the due date has changed
Before merging this PR, please go through the following list and take appropriate …

CIRC-424 cannot create request after overridden check out

---

doc/automated-testing.md
doc/guide.md
pom.xml
src/main/java/org/folio/circulation/domain/LoanRepository.java
src/main/java/org/folio/circulation/infrastructure/serialization/JsonSchemaValidator.java
src/main/java/org/folio/circulation/support/BadRequestFailure.java
src/main/java/org/folio/circulation/support/FailedResult.java
src/main/java/org/folio/circulation/support/ValidationErrorFailure.java
src/test/java/api/loans/LoanAPITests.java
src/test/java/api/support/fakes/FakeOkapi.java
src/test/java/api/support/fakes/FakeStorageModule.java
src/test/java/api/support/fakes/FakeStorageModuleBuilder.java
src/test/java/api/support/fakes/StorageSchema.java
src/test/java/api/support/matchers/ResultMatchers.java
src/test/java/api/support/matchers/ValidationErrorMatchers.java
src/test/java/org/folio/circulation/infrastructure/serialization/JsonSchemaValidationTest.java
src/test/resources/storage-loan-6-1.json

We have had numerous bugs where requests to storage modules fail in hosted environments due to incorrectly mapped record representations.
In order to reduce common mapping issues between mod-circulation representations and storage interface representations, we could validate the storage representation schema during the API tests.
The most recent of which was [CIRC-422](https://issues.folio.org/browse/CIRC-422) and I confirmed that this would have caught that issue.
Starting with a single record type in order to keep this change as small as possible. Loans were chosen because that is the area where we have had the most 
* Copy the storage schema as a test resource (including copying the production schema as a main resource)
* Create JSON schema validator (based upon the work in …

CIRC-421 validate loan storage schema in api tests

---

src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/main/java/org/folio/circulation/resources/RegularCheckOutStrategy.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/support/matchers/CheckOutByBarcodeResponseMatchers.java

Add loan policy id and name to error response when cannot check-out item due to not loanable policy. 
Resolves: [CIRC-427](https://issues.folio.org/browse/CIRC-427)
Required for UI story: [UICHKOUT-534](https://issues.folio.org/browse/UICHKOUT-534)

[CIRC-427] Expand check-out endpoint error response with loan policy info

---

src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/UpdateLoan.java
src/main/java/org/folio/circulation/domain/representations/LoanProperties.java
src/test/java/api/requests/RequestsAPILoanHistoryTests.java

CIRC-289 - Two Entries in Loan Action History When Recall Requested - Only One That Changes Due Date Should Show [part 2 - update action and itemStatus as well]
Update Loan's ItemStatus and Action during recall request creation. 
Send Action/ItemStatus/dueDate updates in a single request.
Ideally all of the PRs involved in breaking changes would be …

CIRC-289: Update loan action/itemStatus for recall requests

---

Jenkinsfile

Enable kubedeploy step on buildMvn pipeline. This step deploys a container to the ci kubernetes environment when a release or snapshot artifact is built.

FOLIO-2256 deploy snapshot/release images to ci kubernetes

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/circulation/domain/notice/NoticeEventType.java
src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
src/test/java/api/requests/RequestsAPICreationTests.java
src/test/java/api/requests/scenarios/MoveRequestPolicyTests.java
src/test/java/api/support/builders/NoticeConfigurationBuilder.java

To rename "Item recalled" and "Hold Expiration" triggering event options since they have been renamed in mod-circulation-store
To update version of `patron-notice-policy-storage`
Resolves story: [CIRC-438](https://issues.folio.org/browse/CIRC-438)
- renamed "Hold Expiration" to "Hold expiration" and "Recall loanee" to "Item recalled"
- updated version of `patron-notice-policy-storage`
To be merged together with https://github.com/folio-org/mod-circulation-storage/pull/202

[CIRC-438] rename "Item recalled", "Hold Expiration" fields

---

src/test/java/api/loans/scenarios/CheckoutWithRequestScenarioTests.java
src/test/java/api/requests/RequestScheduledNoticesProcessingTests.java

Fix failing API tests
Resolves: [CIRC-492](https://issues.folio.org/browse/CIRC-492)
- `checkingOutWithHoldRequestAppliesAlternatePeriodAndScheduledForFixedPolicy` test fails due to the fact the **fixed due to date schedule** was hardcoded to September, but **loan date** was taken as now (just not specified in check-in request).
- `aUponAtRequestExpirationNoticeShouldBeSentAndDeletedWhenRequestExpirationDateHasPassed` fails because request was closed using `mod-circulation` API instead of  `mod-circulation-storage` API;

[CIRC-492] Fix failing tests

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionRepository.java
src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionService.java
src/main/java/org/folio/circulation/domain/notice/session/PatronActionType.java
src/main/java/org/folio/circulation/domain/notice/session/PatronSessionRecord.java
src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
src/main/java/org/folio/circulation/resources/LoanNoticeSender.java
src/main/java/org/folio/circulation/support/Clients.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/loans/scenarios/CheckoutWithRequestScenarioTests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/fakes/FakeOkapi.java
src/test/java/api/support/http/InterfaceUrls.java
src/test/java/api/support/http/ResourceClient.java

To save patron session record at the time of check-out
Resolves: [CIRC-431](https://issues.folio.org/browse/CIRC-431)
- remove sending patron notice at the time of check-out
- remove related test
- implement `PatronActionSessionService` and `PatronActionSessionRepository` to save session records
- use `PatronActionSessionService` in `CheckOutByBarcodeResource`

[CIRC-431] Add saving session record on check-out

---

src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/test/java/api/loans/scenarios/CheckoutWithRequestScenarioTests.java
src/test/java/api/requests/RequestsAPILoanRenewalTests.java
src/test/java/api/support/builders/LoanPolicyBuilder.java

CIRC-200: Get Alternate Renewal Period For Items With Pending Hold Request - 2nd iteration - [See comment](https://issues.folio.org/browse/CIRC-200?focusedCommentId=61428&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-61428)
* Implement period falling logic for rolling policies, so the period priority is following (for item with pending hold request in the queue):
1. Period from holds section;
1. Period from renewals section;
1. Period from loans section.
* Agreed do not use `Alternate loan period at renewal for items with an active, pending hold request` for fixed policies, so if renewal for items with requests is true, then we will chose FDDS from either:
1. From renewals section;
1. From loans section.
Before merging this PR, please go through the …

CIRC-200: Implement period falling logic for rolling renew

---

pom.xml
src/main/java/org/folio/circulation/domain/RequestQueueRepository.java
src/test/java/org/folio/circulation/domain/RequestQueueRepositoryTest.java

In order to ensure that we comply with DB constraints, we need to ensure we process the request updates in an order fashion, one after the other. The problem here is that we execute the updates asynchronously, without waiting for the result of the previous update. In this case, we can have requests being updated to positions that have not been vacated.
[CIRC-463](https://issues.folio.org/browse/CIRC-463)
To address this, we now wait to issue the next update until after the previous update has returned. This will prevent, or, at least, severely reduce the chance of a request being moved to an already taken position.
Also added a unit test that fails with the existing code and passes with this fix. In order to mock this, added a test dependency to Mockito and made the …

Fix for CIRC-463 - request position updates in the queue

---

src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/resources/CheckInProcessAdapter.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/support/builders/NoticeConfigurationBuilder.java

**Available** notice (or **awaiting pickup** notice) should be sent only the first time when the item becomes "awaiting for pickup".
Resolves: [CIRC-477](https://issues.folio.org/browse/CIRC-477)
- add test demonstrating the issue; 
- set `changed` flag for the `Item` only when it is actually changed;
- use `changed` flag to detect whether the item was changed before sending **available** notice.

[CIRC-477] Send available notice once at the check-in

---

doc/circulationrules.md

The current documentation about the criterium syntax is illegible, it hides the syntax,
and we cannot expect people to read the document but we must assume that they only
skim through it.
Therefore the explanation needs to be verbose by using complete examples that stands
out instead of the in-line examples.
A heading needs to be added for the "!" and "all" syntax to catch the eye.

Verbose doc of criterium syntax, complete example, heading for "!" and "all"

---

ramls/loan.json
src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/LoanAndRelatedRecords.java
src/main/java/org/folio/circulation/domain/representations/LoanProperties.java
src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/support/fakes/StorageSchema.java
src/test/java/api/support/fixtures/ItemsFixture.java
src/test/resources/storage-loan-6-2.json

The [pull request](https://github.com/folio-org/mod-circulation/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc) for [CIRC-553](https://issues.folio.org/browse/CIRC-553) introduced a change which causes all check outs to fail.
The resolution isn't as simple as I thought it would be, so the original change needs reverting to fix the hosted reference environments.

Revert CIRC-465 store item location at check out

---

src/test/java/api/loans/anonymization/AnonymizeLoansImmediatelyAPITests.java

This is just unit test coverage of automatic loan anonymization, the implementation was completed in CIRC-367

CIRC-364: Add tests for anonymize closed loans setting of "Immediately"

---

src/test/java/api/requests/scenarios/HoldShelfExpirationDateTests.java
src/test/java/api/support/matchers/TextDateTimeMatcher.java

I use JDK 13 locally when building mod-circulation. Whilst preparing a hot fix release for [CIRC-543](https://issues.folio.org/browse/CIRC-543) the hold shelf expiration tests failed.
This was caused by the `clock.now()` method generating a `ZonedDateTime` with a precision beyond milliseconds (nanoseconds?). 
When this was compared to the ISO formatted date time in the API response it did not match.
* Create a new text date time matcher that uses `ZonedDateTime`
* Use it within one of the failing hold shelf expiration tests
* Limit the precision of the both `ZonedDateTime`s within the matcher to milliseconds
* Use this matcher within all of the hold shelf expiration date tests.
* Run the tests using both `JDK 1.8.0_202-b08` and `OpenJDK 13.0.1`
Before merging this PR, please go through …

Use millisecond precision when checking zoned date time

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

CIRC-565 FOLIO-2358 manage container memory

---

src/test/java/api/requests/scenarios/MoveRequestTests.java
src/test/java/api/support/matchers/TextDateTimeMatcher.java

To improve the reliability of the move request API tests. 
Under some circumstances (e.g. using JVM 13) the time can be more precise than millseconds, which is the precision used in our APIs, this can result in false failures.
Use the hamcrest matchers that limit the precision of the expected date and time to milliseconds. A new matcher variant has been added to support `Instant` and the implementations consolidated.
- Are the …

CIRC-594 make move request due date tests use millisecond precision

---

src/main/java/org/folio/circulation/support/JsonArrayHelper.java
src/test/java/api/loans/CheckInByReplacingLoanTests.java
src/test/java/api/loans/LoanAPIPolicyTests.java
src/test/java/api/loans/LoanAPIProxyTests.java
src/test/java/api/loans/LoanAPITests.java
src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/JsonCollectionAssistant.java
src/test/java/api/support/MultipleJsonRecords.java
src/test/java/api/support/RestAssuredClient.java
src/test/java/api/support/fixtures/LoansFixture.java
src/test/java/api/support/http/CqlQuery.java
src/test/java/api/support/http/Limit.java
src/test/java/api/support/http/Offset.java
src/test/java/api/support/http/QueryStringParameter.java

In order to reduce the coupling and reuse between the API tests and the main code, we can start to replace the use of `OkapiHttpClient` with `RestAssured`.
This reduces the chances that tests are affected by unintentional changes in the production code. Hopefully it also reduces the amount of code and improves the readability of the tests.
This also reduces the dependency upon vert.x 3.x HttpClient (some of the methods used in mod-circulation are deprecated), which helps with the eventual migration to vert.x 4.0. Eventually, the remaining production usage will be replaced with the WebClient.
Rather than try to do this in a single pull request, this first pull request only replaces the use of `ResourceCollectionClient` in the `LoansApiTests` and the `LoansFixture`.
Hopefully this can …

CIRC-596 use rest assured for loans api tests

---

pom.xml
src/test/java/api/item/ItemLastCheckInTests.java
src/test/java/api/loans/DeclareLostAPITests.java
src/test/java/api/loans/anonymization/LoanAnonymizationTests.java
src/test/java/api/support/APITestContext.java
src/test/java/api/support/RestAssuredClient.java
src/test/java/api/support/fixtures/EndPatronSessionClient.java
src/test/java/api/support/fixtures/ExpiredSessionProcessingClient.java
src/test/java/api/support/fixtures/LoansFixture.java
src/test/java/api/support/fixtures/RequestsFixture.java
src/test/java/api/support/fixtures/ScheduledNoticeProcessingClient.java
src/test/java/api/support/http/OkapiHeaders.java
src/test/java/api/support/http/TimedTaskClient.java

In order to reduce the coupling and reuse between the API tests and the main code, we can start to replace the use of OkapiHttpClient with RestAssured.
This reduces the chances that tests are affected by unintentional changes in the production code. Hopefully it also reduces the amount of code and improves the readability of the tests.
This also reduces the dependency upon vert.x 3.x HttpClient (some of the methods used in mod-circulation are deprecated), which helps with the eventual migration to vert.x 4.0. Eventually, the remaining production usage will be replaced with the WebClient.
This is the second in a series of changes to use Rest Assured instead of a custom client in the API tests for mod-circulation.
The conversion to an instance means that the implicit coupling between the …

CIRC-596 Make rest assured client an instance

---

src/main/java/org/folio/circulation/domain/notice/schedule/RequestScheduledNoticeService.java
src/test/java/api/requests/RequestScheduledNoticesTests.java

Fix the logic of creation of scheduled request notices.
[CIRC-605](https://issues.folio.org/browse/CIRC-605)
Currently, when the request is created/changed, we iterate over the configurations set up in the applicable patron notice policy to see which notices we must schedule. When we encounter configuration with triggering event other than `REQUEST_EXPIRATION` or `HOLD_EXPIRATION`, we throw an exception, which causes the whole process of creating notices to halt. So, for example, if the applicable policy contains following notices:
1) Pickup reminder notice
2) Request expiration notice
3) Hold shelf expiration notice
the process of creating notices will break while trying to create the pickup reminder notice (1), and notices 2 and 3 will never be scheduled. The idea of this fix is to …

[CIRC-605] Patron notices: pickup reminder and holdshelf expiration notice not sent

---

src/test/java/api/CirculationRulesEngineAPITests.java
src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java
src/test/java/api/loans/DueDateScheduledNoticesProcessingTests.java
src/test/java/api/loans/OverrideRenewByBarcodeTests.java
src/test/java/api/loans/anonymization/LoanAnonymizationTests.java
src/test/java/api/requests/HoldShelfClearanceReportTests.java
src/test/java/api/requests/InstanceRequestsAPICreationTests.java
src/test/java/api/requests/ItemsInTransitReportTests.java
src/test/java/api/requests/PickSlipsTests.java
src/test/java/api/requests/RequestsAPIRetrievalTests.java
src/test/java/api/requests/scenarios/SingleOpenHoldShelfRequestTests.java
src/test/java/api/support/APITestContext.java
src/test/java/api/support/APITests.java
src/test/java/api/support/RestAssuredClient.java
src/test/java/api/support/fixtures/HoldingsFixture.java
src/test/java/api/support/fixtures/InstancesFixture.java
src/test/java/api/support/fixtures/ItemsFixture.java
src/test/java/api/support/fixtures/LoansFixture.java
src/test/java/api/support/fixtures/RequestsFixture.java
src/test/java/api/support/http/InterfaceUrls.java
src/test/java/api/support/http/ResourceClient.java

In order to reduce the coupling and reuse between the API tests and the main code, we can start to replace the use of OkapiHttpClient with RestAssured.
This reduces the chances that tests are affected by unintentional changes in the production code. Hopefully it also reduces the amount of code and improves the readability of the tests.
This also reduces the dependency upon vert.x 3.x HttpClient (some of the methods used in mod-circulation are deprecated), which helps with the eventual migration to vert.x 4.0. Eventually, the remaining production usage will be replaced with the WebClient.
This is the third in a series of pull requests. It replaces the use of the OkapiClient with Rest Assured in the `ResourceClient` used in tests
Before merging this PR, please go through the following list …

CIRC-596 Use rest assured in resource client

---

descriptors/ModuleDescriptor-template.json

The endpoint to move requests currently does not have enough permissions to complete it's work.
Permissions need to be added to allow the circulation rules to be applied to determine a loan policy.
* Introduces a new internal permission set for applying circulation rules. This is intended to try to reduce the duplication between endpoints and start to grant more role or activity based permissions. Hopefully this might make it less likely that a permission is missed when changes are made.
- What other modules will these …

CIRC-610 Grant move request endpoint permissions to apply circulation rules

---

src/main/java/org/folio/circulation/domain/RequestTypeItemStatusWhiteList.java
src/test/java/api/requests/RequestTypeItemStatusWhiteListTests.java
src/test/java/api/requests/RequestsAPICreationTests.java

Declared lost item: prevent all request types
Resolves: [CIRC-614](https://issues.folio.org/browse/CIRC-614)
- add validation if an item has `declared lost item` status;

CIRC-614 Declared lost item: prevent all request types

---

descriptors/ModuleDescriptor-template.json
ramls/examples/items-in-transit.json
ramls/inventory-reports.raml
ramls/items-in-transit.json
src/main/java/org/folio/circulation/domain/representations/ItemReportRepresentation.java
src/test/java/api/requests/ItemsInTransitReportTests.java

Add call number components and copy number to items in transit report.
Resolves [CIRC-556](https://issues.folio.org/browse/CIRC-556).

[CIRC-556] In transit report: remaining call number fields

---

src/main/java/org/folio/circulation/resources/RegularRenewalStrategy.java
src/main/java/org/folio/circulation/resources/RenewalValidator.java
src/test/java/api/loans/RenewalAPITests.java

Prevent users from renewing an item that is claim returned.
Resolves: [CIRC-638](https://issues.folio.org/browse/CIRC-638)
- add validation if an item is  claim returned;

CIRC-638 Claimed returned: prevent renewal

---

src/main/java/org/folio/circulation/domain/policy/OverdueFinePolicy.java
src/main/java/org/folio/circulation/support/JsonPropertyFetcher.java

Resolves [CIRC-653](https://issues.folio.org/browse/CIRC-653).
NullPointerException was being thrown for overdue fine policies without `overdueFine` property. This PR fixes this issue and other similar potential issues in OverdueFinePolicy by using safer methods for getting JSON properties.

CIRC-653 Use safe methods to get JSON properties

---

src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
src/main/java/org/folio/circulation/domain/policy/OverdueFinePolicy.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/support/fixtures/OverdueFinePoliciesFixture.java
src/test/java/org/folio/circulation/domain/policy/OverdueFinePolicyTest.java

[CIRC-664](https://issues.folio.org/browse/CIRC-664) POST requests to /circulation/check-in-by-barcode fail with 500, NPE
Integration tests are failing with NPE. The issue seems to not be reproducible from the UI, but it is possible to create "unknown" overdue fine policies internally that would cause such issue.
- Change UnknownOverdueFinePolicy class to set default values
- Add checks for null
- Add unit tests to ensure that reading policy fields is not causing issues in these cases:
- Policy was created from JSON with `id` field only
- Policy was created from JSON with `id` and `name` fields only
- Policy was created with `unknown()` factory method
- Does this PR meet or exceed the expected …

CIRC-664 Fix NPE for pre-configured policies

---

pom.xml

Fixes [CIRC-681](https://issues.folio.org/browse/CIRC-681)
Currently, com.fasterxml.jackson.core:jackson-databind vulnerabilities found in pom.xml
Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.10.3 or later

[CIRC-681] Fix security vulnerability reported in jackson-databind >=2.9.0, <= 2.9.10.2

---

src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
src/main/java/org/folio/circulation/domain/policy/OverdueFineCalculationParameters.java
src/main/java/org/folio/circulation/domain/policy/OverdueFinePolicy.java
src/main/java/org/folio/circulation/domain/policy/OverdueFinePolicyFineInfo.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/loans/RenewalAPITests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/matchers/OverdueFineMatcher.java
src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java
src/test/java/org/folio/circulation/domain/policy/OverdueFinePolicyTest.java

Fixes [CIRC-678](https://issues.folio.org/browse/CIRC-678)
Currently, when loan's due date is changed by a recall request, `Overdue fine` (`quantity` and `interval`) field of the Overdue fine policy is being used for overdue fine calculation. We should use `Overdue recall fine` value instead.
- Extend Overdue fine policy class to include "Overdue recall fine"
(quantity and interval).
- Use "Overdue recall fine" value for overdue fine calculation if
loan's due date was changed by a recall (instead of "Overdue fine"
value).
- Extend unit and API tests to cover a "recall" scenario.
If there are …

CIRC-678 Handle overdue recall correctly

---

pom.xml
src/main/java/org/folio/circulation/domain/UpdateLoan.java

https://issues.folio.org/browse/CIRC-340
`jacoco-maven-plugin` is no longer needed as described in above link and the `org.apache.commons.lang.StringUtils` import is not even used anymore.

CIRC-340: Unneeded/wrong dependencies in maven/code

---

src/main/java/org/folio/circulation/domain/ConfigurationService.java
src/test/java/org/folio/circulation/domain/ConfigurationServiceTest.java

Fixes [CIRC-684](https://issues.folio.org/browse/CIRC-684)
Currently, we have exception, when we retrieve from UI part value as String, but we expect integer. For avoiding this situation we can retrieve object and then parse to integer
To get value from json and then parse

[CIRC-684] No exception handling for notice-session-expiration-by-timeout

---

src/main/java/org/folio/circulation/domain/representations/AccountStorageRepresentation.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/loans/RenewalAPITests.java
src/test/java/api/support/matchers/OverdueFineMatcher.java
src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java

Resolves [CIRC-698](https://issues.folio.org/browse/CIRC-698)
Currently, when overdue fine is created, location ID is passed as `account.location` instead of location name.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

CIRC-698 Overdue fine location name instead of id

---

src/main/java/org/folio/circulation/resources/CirculationRulesResource.java
src/main/java/org/folio/circulation/rules/PolicyValidator.java
src/main/java/org/folio/circulation/rules/Text2Drools.java
src/test/java/api/CirculationRulesAPITests.java
src/test/java/api/CirculationRulesEngineAPITests.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/loans/CheckOutCalculateDueDateShortTermTests.java
src/test/java/api/loans/CheckOutCalculateDueDateTests.java
src/test/java/api/loans/LoanAPIPolicyTests.java
src/test/java/api/loans/OverrideRenewByBarcodeTests.java
src/test/java/api/loans/RenewalAPITests.java
src/test/java/api/requests/RequestsAPICreationTests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/builders/LostItemFeePolicyBuilder.java
src/test/java/api/support/builders/NoticePolicyBuilder.java
src/test/java/api/support/builders/OverdueFinePolicyBuilder.java
src/test/java/api/support/builders/RequestPolicyBuilder.java
src/test/java/api/support/fakes/FakeOkapi.java
src/test/java/api/support/fixtures/CirculationRulesFixture.java
src/test/java/api/support/fixtures/LoanPoliciesFixture.java
src/test/java/api/support/fixtures/LostItemFeePoliciesFixture.java
src/test/java/api/support/fixtures/NoticePoliciesFixture.java
src/test/java/api/support/fixtures/OverdueFinePoliciesFixture.java
src/test/java/api/support/fixtures/RequestPoliciesFixture.java
src/test/java/api/support/http/ResourceClient.java

Implement BE validation to prevent saving of non-existent policies
Resolves: [CIRC-658](https://issues.folio.org/browse/CIRC-658)
The validation logic gets all ids of existing policies from DB and checks ids of each policy during the rule saving. If policy is non-existing, it will return the validation error status "422" with the error: "The policy (policy type) does not exist", line and char position in the line with wrong policy.

Circ 658 b18.0

---

src/main/java/org/folio/circulation/domain/LoanRepository.java
src/test/java/api/requests/RequestsAPICreationTests.java
src/test/java/api/support/http/CqlQuery.java

https://issues.folio.org/browse/CIRC-699 - Bugfest: 500 Error when filtering Requests by Type = Page
Use `FindWithMultipleCqlIndexValues` to fetch open loans for items, when fetching multiple requests in order to omit `414 Uri too long` error.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

CIRC-699: Use partition to fetch loans for requests.

---

src/main/java/org/folio/circulation/resources/CirculationRulesResource.java
src/main/java/org/folio/circulation/support/CollectionResourceClient.java

Fix issue with validation error for existing policies.  Set custom limit to retrieve existing policies.
This issue (CIRC-705) is caused by not setting the limit in the calls that retrieve policies from other modules, so the default limit of 10 is applied. As a consequence, only first 10 policies of each type are recognized as existing.
The reason why it's important to deliver this fix to Bugfest ASAP is that in the attempt to reproduce CIRC-705 most of the rules were deleted. We can't revert it because there are more than 10 loan policies on Bugfest and some of them are used in the rules, so this bug prevents rules from being saved. With the current set of rules and 10 policy limit POs are likely won't be able to continue testing.
Resolves: CIRC-705

CIRC-705 fix limit issue for policies

---

descriptors/ModuleDescriptor-template.json

Resolves [CIRC-708](https://issues.folio.org/browse/CIRC-708)
This adds a missing sub permission (`circulation.rules.overdue-fine-policy.get`) to `modperms.circulation.override-check-out-by-barcode.post` allowing a user with Check Out: All permissions to conduct a post to override-check-out-by-barcode.post without encountering the current error.

CIRC-708 User with Check Out: All permissions cannot override

---

src/test/java/api/CirculationRulesAPITests.java
src/test/java/api/support/fixtures/CirculationRulesFixture.java
src/test/java/api/support/fixtures/RequestPoliciesFixture.java

Create test to cover logic that was implemented in scope of CIRC-705.
The issue (CIRC-705) is caused by not setting the limit in the calls that retrieve policies from other modules, so the default limit of 10 is applied. As a consequence, only first 10 policies of each type are recognized as existing.
Considering it's crucial to deliver this fix ASAP, the fix was merged. This PR was created to cover this functionality with tests.
Resolves: [CIRC-706](https://issues.folio.org/browse/CIRC-706)
https://issues.folio.org/browse/CIRC-706

CIRC-706 add tests to cover fix with default limit of existing policies

---

src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
src/main/java/org/folio/circulation/support/Result.java
src/main/java/org/folio/circulation/support/ResultBinding.java
src/test/java/api/support/fixtures/ServicePointExamples.java
src/test/java/org/folio/circulation/domain/RequestRepresentationTests.java
src/test/java/org/folio/circulation/support/results/ResultAfterWhenTests.java

Resolves multiple code smells (some longstanding) for evaluating a Boolean in a way that could cause a `NullPointerException`.
* Allow the `afterWhen` method for a `Result` to change the type of result
* Use `afterWhen` whilst deciding whether to charge an overdue fee
* Extract method to express making a future result from a value clearer
Ideally all of …

CIRC-717 use after when whilst deciding whether to charge an overdue fee

---

descriptors/ModuleDescriptor-template.json

Recently, mod-circulation has repeatedly run out of memory in the hosted reference environments.
It is possible that this is caused by recent changes to integrate with pub-sub, which likely requires a higher baseline memory due to additional libraries and heavy use when processing messages.
Given that it is close to the end of the quarter and it is hard to diagnose these kinds of issues, an initial workaround is to increase the memory allocated to the module.
* Doubled the memory allocation for Docker container in module descriptor

Double docker memory allocation CIRC-762

---

pom.xml
src/main/java/org/folio/circulation/services/PubSubPublishingService.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/fakes/FakePubSub.java
src/test/java/org/folio/circulation/services/PubSubPublishingServiceTest.java

Resolves [CIRC-761](https://issues.folio.org/browse/CIRC-761).
PubSub returns 400 Bad Request response when the event is published and there are no subscribers for its event type. CIRC-734 contained code aimed to ignore this response but it didn't handle the response correctly.
New method for publishing was created, because method from PubSubClientUtils doesn't include response body in the exception message.
There's also additional API test to ensure that 400 Bad Request with "no SUBSCRIBERS" message is ignored (only for check out, other actions call the same publishing service).
If there are …

CIRC-761 Ignore PubSub NO SUBSCRIBERS response

---

src/main/java/org/folio/circulation/resources/PickSlipsResource.java
src/test/java/api/requests/PickSlipsTests.java

When more than 10 locations are assigned to a single service point, picks slips for items located in some of those location may not be created.
Increase page limit for fetching locations during pick slips generation from default 10 to 1000.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

[CIRC-768] Increased page limit for fetching locations during pick slips generation

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/circulation.raml
ramls/examples/override-renewal-by-barcode-request.json
ramls/override-renewal-by-barcode-request.json
src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
src/main/java/org/folio/circulation/domain/notice/schedule/FeeFineScheduledNoticeService.java
src/main/java/org/folio/circulation/resources/context/RenewalContext.java
src/main/java/org/folio/circulation/resources/renewal/OverrideRenewalByBarcodeResource.java
src/main/java/org/folio/circulation/resources/renewal/OverrideRenewalFeeProcessingStrategy.java
src/main/java/org/folio/circulation/resources/renewal/RegularRenewalFeeProcessingStrategy.java
src/main/java/org/folio/circulation/resources/renewal/RenewByBarcodeResource.java
src/main/java/org/folio/circulation/resources/renewal/RenewByIdResource.java
src/main/java/org/folio/circulation/resources/renewal/RenewalFeeProcessingStrategy.java
src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
src/test/java/api/loans/scenarios/OverrideRenewDeclaredLostItemTest.java
src/test/java/api/loans/scenarios/RefundLostItemFeesBaseTest.java
src/test/java/api/loans/scenarios/RefundLostItemFeesTestBase.java
src/test/java/api/support/RestAssuredClient.java
src/test/java/api/support/RestAssuredConfiguration.java
src/test/java/api/support/dto/Item.java
src/test/java/api/support/dto/OverrideRenewal.java
src/test/java/api/support/dto/User.java
src/test/java/api/support/fixtures/OverrideRenewalFixture.java
src/test/java/api/support/http/InterfaceUrls.java
src/test/java/api/support/jackson/serializer/JsonObjectJacksonSerializer.java
src/test/java/api/support/spring/TestSpringConfiguration.java
src/test/java/api/support/spring/clients/ResourceClient.java

https://issues.folio.org/browse/CIRC-716 - BE - Declared lost: renewal (effect on lost item fees) - SET COST
Refund lost item fees when `Declared lost` item is renewed through override. 
The main business logic is the same as for check-in (https://issues.folio.org/browse/CIRC-717). The main changes is to integrate the refund logic with override renewal. For this, new  [`RenewalFeeProcessingStrategy`](https://github.com/folio-org/mod-circulation/pull/579/files#diff-f9787b2ed191b119232110fc10e35d2f) class has been introduced with two implementations:
* [`RegularRenewalFeeProcessingStrategy`](https://github.com/folio-org/mod-circulation/pull/579/files#diff-c03a04597161f4b24604313d8bab425a) - charges overdue fines only, if any. Applies to renewal by barcode/by id operations;
* …

CIRC-716: Refund lost item fees on override renewal.

---

src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java

https://issues.folio.org/browse/CIRC-801 - Recall of overdue item extends loan
Per Cate:
> Hi Bohdan Suprun, once an item is already overdue, a recall should not change the loan period at all since the due date is already in the past (the patron just needs to get the item returned.) It should still add a row to the Loan actions table indicating that the item was recalled.
>
> In terms of notices, which are out of scope for this bug fix, ideally there would be a special notice triggered to the patron saying "Your overdue item has now been recalled. Please get it to the library ASAP. Elevated fees will apply" or something along those lines. We don't have the ability to trigger a special notice for that case yet (it's part of UXPROD-2112) so I assume it will probably just trigger a standard …

CIRC-801: Do not change due date when overdue loan is recalled.

---

src/main/java/org/folio/circulation/resources/RenewalValidator.java
src/test/java/api/loans/OverrideRenewByBarcodeTests.java

It wasn't possible for a loan where the item is declared lost to be renewed, even with an override, if the new due date would be before or the same as the current one. This stopped the declared lost item from becoming checked out again once it has been renewed.
For more context, see [CIRC-809](https://issues.folio.org/browse/CIRC-809).
Apologies for the formatting changes, I should have likely deferred those to a later pull request too.
* Write a test that demonstrates the current behaviour
* Adapt the test to the new behaviour
* Make the change for the test to pass
There are some minor code cleanup changes that I came across during this work. I haven't included them in this pull request in order to keep it to a minimum needed in case it needs back porting.
* Distinguish between failures …

Allow overridden renewal when item is declared lost and new due date is the same or before current due date

---

src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/resources/DeclareLostResource.java
src/test/java/api/loans/DeclareLostAPITests.java

https://issues.folio.org/browse/CIRC-792 - Backend: Able to declare an item lost twice (and maybe more) from Loan Details
Add validation that refuses declaring item lost if it is already lost.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …

CIRC-792: Do not allow declaring item lost if it is already lost.

---

pom.xml

The SmtpAppender did not verify the host name matched the SSL/TLS certificate
of an SMTPS connection which could allow an attacker with
man-in-the-middle access to intercept log messages sent through SMTPS.
This affects log4j < 2.13.2. Fix: Upgrade to log4j >= 2.13.2.
References:
https://nvd.nist.gov/vuln/detail/CVE-2020-9488
https://issues.apache.org/jira/browse/LOG4J2-2819
Also upgrade RMB from 30.2.1 to latest 30.2.2.
mod-circulation is probably not affected by these issues but this upgrade will
silence automated security scanners like GitHub.

CIRC-827: RMB 30.2.2; update log4j to 2.13.3 fixing CVE-2020-9488

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
src/main/java/org/folio/circulation/domain/notice/schedule/JsonScheduledNoticeMapper.java
src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledNoticesRepository.java
src/test/java/api/loans/DueDateScheduledNoticesTests.java
src/test/java/api/support/fixtures/FeeFineOwnerFixture.java
src/test/java/api/support/fixtures/FeeFineTypeFixture.java
src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java

Resolves [CIRC-722](https://issues.folio.org/browse/CIRC-722).
Once overdue fine is charged, we're cancelling scheduled overdue notices for this loan (all **Upon/At due date** and **After due date** notices).
After overdue fine is charged we start sending overdue fine notices, so there's no sense in sending overdue notices on top of overdue fine notices - existence of overdue fine implies that an item is overdue.
Deletion of scheduled patron notices is added to the overdue fine creation chain (OverdueFineCalculatorService) at the very end - after Account and FeeFineAction creation.
If there are …

CIRC-722 Add new stop sending event for overdue notices

---

descriptors/ModuleDescriptor-template.json

Resolves [CIRC-820](https://issues.folio.org/browse/CIRC-820), [CIRC-802](https://issues.folio.org/browse/CIRC-802), [CIRC-804](https://issues.folio.org/browse/CIRC-804)
During override-renewal-by-barcode we're checking whether automated patron blocks for a patron exist. This call fails due to missing permission.
Additionally, permissions related to policies also added according to Zak's comment in CIRC-820.
Also, permissions mentioned in CIRC-802 and CIRC-804 have been added.
- …

CIRC-820 Can't renew through override

---

src/main/java/org/folio/circulation/resources/ItemsInTransitResource.java
src/test/java/api/requests/ItemsInTransitReportTests.java

- Use FindWithMultipleCqlIndexValues to fetch open loans for items to avoid 414 Uri too long error;
- Cover this scenario by test;
Resolves: [CIRC-813](https://issues.folio.org/browse/CIRC-813)

CIRC-813 fix issue with URI Too Large error

---

src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionProperties.java
src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionService.java
src/main/java/org/folio/circulation/domain/notice/session/PatronSessionRecord.java
src/main/java/org/folio/circulation/domain/representations/EndPatronSessionRequest.java
src/main/java/org/folio/circulation/infrastructure/storage/sessions/PatronActionSessionRepository.java
src/main/java/org/folio/circulation/infrastructure/storage/sessions/PatronExpiredSessionRepository.java
src/test/java/api/loans/EndExpiredPatronActionSessionTests.java
src/test/java/api/loans/PatronActionSessionTests.java
src/test/java/api/support/builders/EndSessionBuilder.java
src/test/java/api/support/fixtures/EndPatronSessionClient.java
src/test/java/org/folio/circulation/domain/notice/session/PatronSessionRecordTest.java

- Use FindWithMultipleCqlIndexValues to get expired for items to avoid 414 Uri too long error;
- Cover this scenario by test;
Resolves: [CIRC-865](https://issues.folio.org/browse/CIRC-865)

CIRC-865 fix issue with 414 status during ending expired sessions

---

src/main/java/org/folio/circulation/domain/anonymization/LoanAnonymizationService.java
src/main/java/org/folio/circulation/resources/ExpiredSessionProcessingResource.java
src/main/java/org/folio/circulation/resources/ScheduledAnonymizationProcessingResource.java
src/main/java/org/folio/circulation/resources/ScheduledNoticeProcessingResource.java
src/main/java/org/folio/circulation/support/results/AsynchronousResultBindings.java
src/test/java/org/folio/circulation/support/results/SafelyInitialiseAsynchronousResultTests.java

It was reported in [CIRC-850](https://issues.folio.org/browse/CIRC-850) that mod-circulation and Okapi were consuming a large number of HTTP connections even when idle, meaning that only timer initiated tasks were executed.
A hypothesis for the high number of open connections from Okapi -> mod-circulation was that mod-circulation was failing to respond (for an unknown reason) and that was keeping the connection open.
This pull request intends to reduce the possibility of that happening.
* Introduce a new method for initialising a future result in a safe manner (to avoid having to have a try-catch around every future chain)
* Safely initialise the initial future result in each timed task
* Check that each step in the chain used the appropriate result method for handling exceptions and …

Ensure timer tasks respond CIRC-850

---

src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java

Yesterday, a single notice sending test [started failing|https://jenkins-aws.indexdata.com/job/folio-org/job/mod-circulation/job/master/626/].
This was caused by 
@bohdan-suprun identified, during another pull request, that it was caused by a date being fixed rather than relative and resolved it.
This pull request cherry picks that change to the mainline.
* Use fixed dates with caution as they can cause fragility if any processing is relative to the current date.
- Do JIRAs …

Change notice processing test dependent upon fixed date to use relative date

---

Dockerfile
Jenkinsfile
pom.xml

All modules need to be updated to use JDK 11 during 2020 Q3 as this will soon be the earliest version of Java that Sonar supports
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

Use JDK 11 CIRC-883

---

Dockerfile
Jenkinsfile
pom.xml

Mod-circulation cannot use JDK 11 at this point because the pub-sub client depends upon a RAML Module Builder version that is not compatible with JDK 11, see [FOLIO-2734](https://issues.folio.org/browse/FOLIO-2734) for more details.
Thanks to @bohdan-suprun for identifying the issue.
Until there a JDK 11 compatible version of the pub-sub client, mod-circulation cannot use JDK 11
* This could not be caught by automated tests because the code that fails is not executed when running in a test context rather than as a jar
- What …

Revert JDK 11 upgrade CIRC-883

---

src/main/java/org/folio/circulation/domain/notes/NoteCreator.java
src/test/java/api/loans/DeclareClaimedReturnedItemAsMissingApiTests.java
src/test/java/api/loans/DeclareLostAPITests.java

The reference UI relies upon the domain of all notes for users being
`user` - https://github.com/folio-org/stripes-smart-components/blob/30de4ba6a4f7d71bb37210631b053a17b403bc6a/lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js#L36
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

Change domain of created note to users CIRC-742

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/circulation/domain/ItemStatus.java
src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/LoanCheckInService.java
src/main/java/org/folio/circulation/domain/LoanRepresentation.java
src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
src/main/java/org/folio/circulation/domain/representations/LoanProperties.java
src/main/java/org/folio/circulation/services/LostItemFeeRefundContext.java
src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
src/main/java/org/folio/circulation/services/agedtolost/MarkOverdueLoansAsAgedLostService.java
src/main/java/org/folio/circulation/support/JsonPropertyFetcher.java
src/main/java/org/folio/circulation/support/JsonPropertyWriter.java
src/test/java/api/loans/agetolost/ScheduledAgeToLostApiTest.java
src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
src/test/java/api/loans/scenarios/CheckInAgedToLostItemTest.java
src/test/java/api/support/fakes/StorageSchema.java
src/test/java/api/support/fixtures/AgeToLostFixture.java
src/test/java/org/folio/circulation/support/JsonPropertyFetcherTest.java
src/test/java/org/folio/circulation/support/JsonPropertyWriterTest.java
src/test/resources/storage-loan-7-1.json

https://issues.folio.org/browse/CIRC-845 - Aged to lost: Check in (effect on fees/fines) - SET COST
* Use `loan-storage v7.1` API
* Save date and time when item was aged to lost.
* Remove delayed billing information when an aged to lost loan is checked in.
* Refund lost item fees when aged to lost item is checked in by reusing existing service.
* Assign overdue fine when aged to lost item is overdue.
* Add `writeByPath` and `getPropertyByPath` methods to allow get/write nested properties.
- What other modules will these …

CIRC-845: Refund lost item fees when it checked in.

---

src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
src/main/java/org/folio/circulation/services/LostItemFeeChargingService.java
src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
src/test/java/api/handlers/CloseAgedToLostLoanWhenLostItemFeesAreClosedApiTests.java
src/test/java/api/handlers/CloseDeclaredLostLoanWhenLostItemFeesAreClosedApiTests.java
src/test/java/api/loans/DeclareLostAPITests.java
src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
src/test/java/api/loans/scenarios/CheckInAgedToLostItemTest.java
src/test/java/api/loans/scenarios/RefundLostItemFeesTestBase.java
src/test/java/api/support/builders/LostItemFeePolicyBuilder.java
src/test/java/api/support/fixtures/LostItemFeePoliciesFixture.java
src/test/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicyTest.java
src/test/java/org/folio/circulation/services/agedtolost/LoanToChargeFeesTest.java

https://issues.folio.org/browse/CIRC-852 - Age to lost: Assign lost fees for aged to lost loans - SET COST
If the Lost Item Fee Policy in effect for the loan has _Charge lost item processing fee if item aged to lost by system set to 'No'_, the Lost item processing fee should not be charged for the item.
Ideally all of the PRs involved in breaking changes …

CIRC-852: Do not charge aged to lost processing fee if disabled by policy.

---

pom.xml
src/main/java/org/folio/circulation/domain/OverdueFineCalculatorService.java
src/main/java/org/folio/circulation/infrastructure/storage/CirculationPolicyRepository.java
src/main/java/org/folio/circulation/resources/renewal/OverrideRenewalStrategy.java
src/main/java/org/folio/circulation/services/LostItemFeeRefundContext.java
src/test/java/api/loans/scenarios/CheckInAgedToLostItemTest.java
src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
src/test/java/api/loans/scenarios/OverrideRenewAgedToLostItemTest.java
src/test/java/api/loans/scenarios/OverrideRenewDeclaredLostItemTest.java
src/test/java/api/loans/scenarios/RefundAgedToLostFeesTestBase.java
src/test/java/api/loans/scenarios/RefundDeclaredLostFeesTestBase.java

https://issues.folio.org/browse/CIRC-844 - Aged to lost: Renewal (effect on lost item fees) - SET COST
We need to refund lost item fees, depending on policy configuration, when aged to lost item is renewed through override.
* Refactor `OverdueFineCalculatorService` and add lombok annotations.
* Remove loan billing information when it is renewed through override.
* Consolidate age to lost check in and renewal refunding tests into a single class and just override the testable API. …

CIRC-844: Refund lost item fees when aged to lost item is renewed.

---

src/main/java/org/folio/circulation/resources/DueDateNotRealTimeScheduledNoticeProcessingResource.java
src/main/java/org/folio/circulation/resources/DueDateScheduledNoticeProcessingResource.java
src/main/java/org/folio/circulation/resources/FeeFineScheduledNoticeProcessingResource.java
src/main/java/org/folio/circulation/resources/RequestScheduledNoticeProcessingResource.java
src/main/java/org/folio/circulation/resources/ScheduledNoticeProcessingResource.java
src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java

Resolves [CIRC-919](https://issues.folio.org/browse/CIRC-919) - overnight scheduled notices are delivered the next day for a tenant in CDT timezone.
Overnight (non-realtime) notices are supposed to be delivered at midnight, but in our current implementation we only deliver the notices that are scheduled for `before the last UTC midnight` instead of `before the last midnight in tenant's timezone`. At the same time, loans' due dates are set to 23:59:59 **tenant time**, which means that for all tenants west of UTC the notices will be sent at the next UTC midnight (e.g. 7PM of the next day for CDT timezone).
Fetch tenant's timezone configuration and use it to determine midnight in tenant's timezone - this point is time is used later for filtering of the scheduled notices we want to deliver. …

CIRC-919 Timing of overnight scheduled notices processing

---

src/main/java/org/folio/circulation/support/SingleRecordFetcher.java
src/main/java/org/folio/circulation/support/logging/LogMessageSanitizer.java

The example log sanitisation regular expression provided by Sonar used pipe characters as separators. However these are erroneously interpreted as extra characters in the character class. This pull request removes them.
It also removes a (hopefully) now redundant sanitisation of a parameter that was considered tainted because it was in the same class as a tainted value. Sonar has recently improved its analysis of this and so this workaround should no longer be necessary.
- Do …

Remove duplicate key in regular expression CIRC-381

---

src/main/java/org/folio/circulation/resources/RenewalValidator.java
src/test/java/org/folio/circulation/resources/RenewalValidatorTest.java

Partially revert #634 
As per Emma, they want to have a data picker to set new due date in case renewal does not change due date.
Agreed to have this data picker requirements into separate story.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …

CIRC-881: Revert allow renew for aged to lost items when due date is the same.

---

src/test/java/api/requests/RequestsAPIRetrievalTests.java
src/test/java/api/requests/scenarios/HoldShelfExpirationDateTests.java
src/test/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClientTests.java

Stop the compiler warnings caused by using deprecated Hamcrest matchers
While it's …

Stop using deprecated matchers CIRC-381

---

src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
src/main/java/org/folio/circulation/services/agedtolost/MarkOverdueLoansAsAgedLostService.java
src/test/java/api/loans/agetolost/ScheduledAgeToLostApiTest.java
src/test/java/api/support/fixtures/AgeToLostFixture.java
src/test/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicyTest.java

https://issues.folio.org/browse/CIRC-927 - Aged to lost billed date should be based on when item was aged to lost
Calculate `dateLostItemShouldBeBilled` as `agedToLostDate` + `patronBilledAfterAgedToLost`. 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …

CIRC-927: Use agedToLostDate as base for calculating billing date.

---

src/main/java/org/folio/circulation/services/LostItemFeeRefundService.java
src/test/java/api/loans/scenarios/CheckInAgedToLostItemTest.java
src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
src/test/java/org/folio/circulation/domain/LoanLostDateTest.java

https://issues.folio.org/browse/CIRC-934 - 'Lost and paid' aged to lost items that are returned or renewed must have lost item fees refunded as is done with declared lost items
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

CIRC-934: Allow refund for `Lost and paid` items that was `Aged to lost` before

---

src/main/java/org/folio/circulation/resources/AbstractCirculationRulesEngineResource.java
src/main/java/org/folio/circulation/resources/ChangeDueDateResource.java
src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
src/main/java/org/folio/circulation/resources/CirculationRulesProcessor.java
src/main/java/org/folio/circulation/resources/CirculationRulesResource.java
src/main/java/org/folio/circulation/resources/ClaimItemReturnedResource.java
src/main/java/org/folio/circulation/resources/DeclareClaimedReturnedItemAsMissingResource.java
src/main/java/org/folio/circulation/resources/DeclareLostResource.java
src/main/java/org/folio/circulation/resources/EndPatronActionSessionResource.java
src/main/java/org/folio/circulation/resources/ExpiredSessionProcessingResource.java
src/main/java/org/folio/circulation/resources/ItemsInTransitResource.java
src/main/java/org/folio/circulation/resources/LoanAnonymizationResource.java
src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
src/main/java/org/folio/circulation/resources/PickSlipsResource.java
src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
src/main/java/org/folio/circulation/resources/RequestHoldShelfClearanceResource.java
src/main/java/org/folio/circulation/resources/RequestQueueResource.java
src/main/java/org/folio/circulation/resources/ScheduledAnonymizationProcessingResource.java
src/main/java/org/folio/circulation/resources/ScheduledNoticeProcessingResource.java
src/main/java/org/folio/circulation/resources/agedtolost/ScheduledAgeToLostFeeChargingResource.java
src/main/java/org/folio/circulation/resources/agedtolost/ScheduledAgeToLostResource.java
src/main/java/org/folio/circulation/resources/handlers/LoanRelatedFeeFineClosedHandlerResource.java
src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
src/main/java/org/folio/circulation/support/Clients.java

Reinstates the previous dependencies for the Clients class to reduce the impact of changes on other classes
* Extract method to reduce duplication in circulation rules engine resource
* Extract overload of get drools that requires rules client and tenant ID
* Use that overload instead of the one relying on clients and a HTTP client
* Remove fields added to the clients class
* Reinstate previous dependencies for clients class
* Introduce the correct dependencies in the relevant repositories so they can access the drools processing directly
* Don't let large classes like Clients get so far down the chain of dependencies, it's a mess
- Does …

CIRC-239 Reduce changes to clients class during circulation rules changes

---

src/main/java/org/folio/circulation/domain/AutomatedPatronBlock.java
src/test/java/api/support/fixtures/AutomatedPatronBlocksFixture.java

- Fix typos in property names for AutomatedPatronBlock
Resolves: https://issues.folio.org/browse/CIRC-774

CIRC-774: Renew is not blocked when automated patron block exists

---

src/main/java/org/folio/circulation/domain/representations/logs/LoanLogContext.java
src/main/java/org/folio/circulation/services/EventPublisher.java
src/test/java/api/queue/RequestQueueResourceTest.java
src/test/java/api/requests/RequestsAPIUpdatingTests.java
src/test/java/api/requests/scenarios/MoveRequestTests.java

[CIRC-986](https://issues.folio.org/browse/CIRC-986) - User details are absent in aged to lost loan circ log record
User details should be present in aged to lost loan circ log record
This PR introduces minor improvements …

CIRC-986 - User details are absent in aged to lost loan circ log record

---

descriptors/ModuleDescriptor-template.json

Failed to decode:Unrecognized token 'Access': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
at [Source: (String)"Access requires permission: circulation-storage.circulation-rules.get"; line: 1, column: 7]
- Add permission for  /request-scheduled-notices-processing endpoint;
Resolves: https://issues.folio.org/browse/CIRC-993

CIRC-993 Notices triggered by hold shelf expiration not received as expected

---

src/main/java/org/folio/circulation/services/EventPublisher.java
src/test/java/api/loans/CheckInByBarcodeTests.java

[CIRC-1015](https://issues.folio.org/browse/CIRC-1015) - Not loaned checked in item was not recorded in the circulation log
Not loaned checked in item should appear in the circulation log
When check in event without loan passed to the EventPublisher, log record is created
Ideally all of the PRs involved in breaking changes would be merged in the same day …

CIRC-1015 - Not loaned checked in item was not recorded in the circulation log

---

descriptors/ModuleDescriptor-template.json

This error has been found during debug: 
org.folio.circulation.domain.notice.schedule.RequestScheduledNoticeHandler#sendNotice
Access requires permission: circulation.rules.notice-policy.get
Resolves: https://issues.folio.org/browse/CIRC-993

CIRC-993 add permissions for getting notice policies

---

src/main/java/org/folio/circulation/domain/policy/library/KeepCurrentDateStrategy.java
src/test/java/org/folio/circulation/domain/policy/library/KeepCurrentStrategyTest.java

https://issues.folio.org/browse/CIRC-1013 - Checked out an item with due date/time in the past.
Given:
* Fixed due date schedule:
* from: 2020-11-11T00:00:00+00:00 - (note that midnight is set by UI);
* to: 2020-11-16T00:00:00+00:00 - (note that midnight is set by UI);
* due: 2020-11-16T00:00:00+00:00 - (note that midnight is set by UI);
* Keep current due date closed library strategy is used and it always sets time to the end of the current day in the timezone that defined in settings.
When user checks out item, due date is calculated to 2020-11-16T00:00:00+00:00 as it is configured by fixed due date schedule, but then we convert the due date to GMT -5:00 time zone (to calculate EOD in the given time zone) but now due date becomes previous day, so EOD set for the previous day.
Always set …

CIRC-1013: Always use original date for KeepCurrentDate closed library strategy.

---

pom.xml

https://x-stream.github.io/CVE-2020-26217.html
XStream is a Drools dependency. Drools hasn't fixed the dependency yet.

Upgrade to XStream 1.4.14 fixing Remote Code Execution (CVE-2020-26217)

---

src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
src/test/java/api/requests/RequestsAPICreationTests.java

This PR follows up the previous https://github.com/folio-org/mod-circulation/pull/763. 
The checking of dueDateChanged for moved requests was removed as well.
- remove dueDateChanged checking for moved recall sending notice;
- fix NPE;
- create test;
Resolves: https://issues.folio.org/browse/CIRC-1031

CIRC-1031 Remove checking of dueDateChanged for moved requests

---

src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/main/java/org/folio/circulation/support/json/JsonPropertyWriter.java
src/test/java/api/loans/ClaimItemReturnedAPITests.java
src/test/java/api/loans/DeclareLostAPITests.java
src/test/java/api/support/matchers/DateTimeMatchers.java
src/test/java/api/support/matchers/EventMatchers.java
src/test/java/api/support/matchers/LoanMatchers.java
src/test/java/api/support/matchers/TextDateTimeMatcher.java

A recent [change](https://github.com/folio-org/mod-circulation/pull/741/files) caused mod-circulation to stop outputting some date time properties in UTC
A quick fix was put in place to resolve this by [weakening](https://github.com/folio-org/mod-circulation/pull/749) the checking in the tests.
* Reproduce the issue by reverting the obscuring change and executing the tests in a non-UTC timezone
* Change tests using string comparisons for date-time checks to more specific matchers
* Change the JSON property writer to enforce UTC offset when writing date time properties
* Change the matchers to explicitly check for UTC offset / zone
* Move use of string based matching of loan properties to type specific matching
Before merging this PR, please go through the following list and take …

Date-time properties should be represented in UTC CIRC-1019

---

src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/loans/CheckOutToExpiringPatronTests.java

A recent change, #718 started truncating the due date for new loans to when the borrowing patron expires.
This truncation always uses a move to previous day closed due date management approach, in order to avoid due dates that go beyond the expiration of the patron.
This approach requires a calendar to be defined for the patron, meaning a calendar is required for a check out to an expiring patron. 
Unfortunately, this process is applied after the item being checked out is updating, leading to an inconsistent state in the system.
* Recreate the issue in a new API test
* Move the tests for check out to expiring patron to a separate class
* Consolidate the logic used in those tests
* Reusing methods from other tests can sometimes add unnecessary complexity
Before merging this PR, please go …

Add test to recreate erroneous updating of item status when checking out to expiring patron CIRC-995

---

src/main/java/org/folio/circulation/StoreLoanAndItem.java
src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/LoanAndRelatedRecords.java
src/main/java/org/folio/circulation/domain/UpdateItem.java
src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
src/test/java/api/loans/CheckOutToExpiringPatronTests.java

An underlying contributing factor to CIRC-995 is that the logic for truncating the loan due date for expiring patrons happens *after* the item status change has been persisted to storage.
* Remove complexity from the item update code that was used in multiple places
* Move the persistence of the item till after the truncation of the due date for expiring patrons
* Change the item status explicitly in the domain
* Remove the old logic for deciding how to change the item during storage
* Split the business logic for updating the request queue and storage (CIRC-1025)
* With the process defined as it currently is, it is too easy to perform operations in an inappropriate order, the process needs to be split up to discourage that from happening in the future
Before merging this PR, please go …

Update item in storage after business logic CIRC-995

---

pom.xml
src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/domain/RequestQueue.java
src/test/java/org/folio/circulation/domain/RequestQueueRemoveRequestTests.java
src/test/java/org/folio/circulation/domain/RequestQueueTests.java
src/test/java/org/folio/circulation/matchers/requests/RequestMatchers.java
src/test/java/org/folio/circulation/matchers/requests/RequestQueueMatchers.java

The overall purpose of this work is to move the updating of records in storage to after the business logic during a check out.
In order to do that, it is necessary to restructure when the records are changed and when they are stored. Unfortunately, these two are quite coupled together at the moment. In order to reduce that, the request queue code needs to change.
In preparation for that (and adding more tests) it seemed a good idea to simplify the current tests and hopefully reduce duplication in future tests.
* Move the tests to JUnit 5 (mostly to start that migration and to use nesting)
* Introduce custom matchers to simplify the assertions (and reduce the need for descriptions)
* Reduce the duplication in the tests for queues with multiple requests (including by nesting them)
* Move …

CIRC-1025 simplify request queue unit tests

---

descriptors/ModuleDescriptor-template.json
src/test/java/api/support/fakes/StorageSchema.java
src/test/resources/link.json
src/test/resources/note-2-0.json

https://issues.folio.org/browse/FOLIO-2910 and https://issues.folio.org/browse/CIRC-1055 were brought to our attention that mod-circulation build is failing due to notes interface version mismatch. Fix the problem to alleviate the situation for tomorrow's system demo.
Change interface version from 1.0 to 2.0
From a high level, looks like no other changes are needed but look deeper in implementation and tests to see if any functionality should be changed. 
/note-links/domain/{domain}/type/{type}/id/{id}/ endpoint's query param has changed from 'title' to 'search' in this [PR](https://github.com/folio-org/mod-notes/pull/163/files?file-filters%5B%5D=.java&file-filters%5B%5D=.json&file-filters%5B%5D=.raml&file-filters%5B%5D=.sql)

CIRC-1055: Update notes dependency

---

src/test/java/api/requests/RequestsAPIDeletionTests.java

As preparation for the ongoing work on re-organising the business logic when changing requests (CIRC-1025) and introducing an asynchronous result class to simplify how business logic is described (CIRC-1066) the request deletion tests could do with being updated to reflect more recent changes in the code
* Move single request deletion test to top of class to emphasise most common scenario
* Check the requests in the request queue when deleting a single request
* Use requests fixture and private methods to simplify placing requests
* Use local variable type inference to reduce noise in the tests
* Use status code matcher to simplify API response checks
- Does this PR meet or exceed the expected …

Simplify delete request api tests CIRC-1025 

---

src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/loans/CheckOutByBarcodeTests.java

Some error messages were missing whitespace around their punctuation;this
drove some people crazy.Most people never noticed.
Refs [CIRC-1074](https://issues.folio.org/browse/CIRC-1074)

CIRC-1074 use correct whitespace after a colon

---

src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
src/main/java/org/folio/circulation/support/http/server/WebContext.java
src/main/java/org/folio/circulation/support/results/AsynchronousResult.java
src/test/java/org/folio/circulation/support/results/AsynchronousResultCreationTests.java
src/test/java/org/folio/circulation/support/results/AsynchronousResultExamples.java
src/test/java/org/folio/circulation/support/results/AsynchronousResultFlatMapFutureTests.java
src/test/java/org/folio/circulation/support/results/AsynchronousResultMapTests.java
src/test/java/org/folio/circulation/support/results/AsynchronousResultSideEffectTests.java
src/test/java/org/folio/circulation/support/results/AsynchronousResultTestHelper.java

Introduces a new `AsynchronousResult` class to represent an asynchronous result that could succeed or fail.
Intended to simplify the implementation of chains of asynchronous method calls. And improve the readability of the chains by reducing the noise when using CompletableFuture.
Uses more functional-esque language similar to vert.x and other libraries.
Should eventually make moving the code to different tools easier as less dependent upon CompletableFuture all over the code base.
* Uses JUnit 5 to reduce the noise in unit tests
* Demonstrates use of the new class by migration `RequestCollectionResource` to use it. This should get cleaner still as more code is moved to `AsynchronousResult` and the mapping between it and `CompletableFuture<Result>` can be reduced.
`flatMapFuture` is a …

Introduce async result CIRC-1066

---

pom.xml

XStream is vulnerable to an Arbitrary File Deletion on the local host
when unmarshalling as long as the executing process has sufficient rights.
All versions until and including version 1.4.14 are affected running in a
Java environment containing the JAX-WS runtime, if using the version out of
the box.
Details: https://x-stream.github.io/CVE-2020-26259.html
Fix:
Update the XStream version from 1.4.14 to 1.4.15.
Use a XStream version without security vulnerability.
Bump the XStream version.

CIRC-1086: XStream 1.4.15 Arbitrary File Deletion (CVE-2020-26259)

---

src/main/java/org/folio/circulation/resources/handlers/error/CirculationErrorType.java
src/main/java/org/folio/circulation/resources/renewal/OverrideRenewalByBarcodeResource.java
src/main/java/org/folio/circulation/resources/renewal/RenewByBarcodeResource.java
src/main/java/org/folio/circulation/resources/renewal/RenewByIdResource.java
src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/loans/RenewalAPITests.java
src/test/java/api/support/matchers/ValidationErrorMatchers.java
src/test/java/api/support/utl/BlockOverridesUtils.java

Resolves CIRC-1059.
Handle multiple validation errors during renewal instead of failing with the first one
Use CirculationErrorHandler to accumulate validation errors
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

CIRC-1059 - Return a full list of errors when renewal fails

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/age-to-lost-background-processes.raml

In order to allow FOLIO implementors to [define their own schedule](https://issues.folio.org/browse/CIRC-1084) for the age to lost processes, the processes must no longer be scheduled using Okapi's timer interface.
* Change the major version of the module (to indicate that changes need to be made to preserve the current behaviour)
* Define a new interface for age to lost process endpoints so they can be requested externally (using the same endpoints to minimise the changes)
* Change the module descriptor to provide the new interface
If there are breaking changes, please **STOP** and consider the …

Stop periodic execution of aged to lost processes CIRC-1084

---

descriptors/ModuleDescriptor-template.json

The pubsub.publish.post was missing from the modperms.circulation.requests.instances.item.post set so any instance-level request event is not published and subsequently does not show up in mod-circulation-log.  The JIRA stated 2 endpoints ( which equates to 2 permissions set not having this permission, but it turns out that this permission already existed in modperms.circulation.requests.item.post, which is used by item-level requests.
Add pubsub.publish.post to the modperms.circulation.requests.instances.item.post set.
Any new permissions added to modperms.circulation.requests.item.post for the /circulation/requests API must be added to modperms.circulation.requests.instances.item.post for the /circulation/requests/instances API as well
Before merging this PR, please go through the …

CIRC-1095: Missing module permissions for request endpoints

---

NEWS.md
pom.xml

In order to create space to release `20.1.0` from a branch based upon the bug fix branch for 20.0.x, the version on the mainline needs to change to `20.2.0` for the next mainline release.
This is due to a bug fix, [CIRC-1077](https://issues.folio.org/browse/CIRC-1077), containing an API change which means a minor release is needed.

Update minor version CIRC-1107

---

NEWS.md
pom.xml

Release version 20.1.0
Minor versions are not usually released from a branch. [CIRC-1077](https://issues.folio.org/browse/CIRC-1077) is considered a bug fix, however it changes the API for the client, which means that it should be included in a minor version release (it would need to be major if the API wasn't a pre-release)

Release 20.1.0 CIRC-1107

---

NEWS.md

As 20.1.0 was released from a long lived branch, the news wasn't automatically included in the mainline.

Include 20.1.0 release in news CIRC-1107

---

descriptors/ModuleDescriptor-template.json

Fixes [CIRC-1114 Not receiving change due date notice](https://issues.folio.org/browse/CIRC-1114)
Users are not receiving patron notice when due date is changed manually.
Iris Bugfest logs:
`2021-04-06T12:48:57.973Z 12:48:57 ERROR LogHelper            Failed to send patron notice request: PatronNotice{recipientId='dadff4c5-d0cf-47ac-8d77-e5c5628626ba', templateId='ec9c41b6-122e-4035-ba6f-295ed4993808'}. Cause: [403] Access requires permission: patron-notice.post`
Add `patron-notice.post` permission to `modperms.circulation.loans.change-due-date.post`
If there are breaking changes, please **STOP** …

CIRC-1114 Add patron notices permission to change due date endpoint

---

NEWS.md
pom.xml
src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java

The fix for this was very simple: I added a condition to the 
code that checks for actual cost items so that it does not trigger
if the item has both an actual cost set and a chargeable lost item
processing fee.  This causes actual cost items to get processed if
they have a lost item processing fee set.
I also wrote a test for this behavior.
refs: https://issues.folio.org/browse/CIRC-1115

CIRC-1115: Aged to lost process need to process ACTUAL COST items if there is a LOST ITEM PROCESSING FEE

---

NEWS.md
descriptors/ModuleDescriptor-template.json

The checkin-by-barcode endpoint does not have the permission
to access lost item fee policies, which is what was causing the error 
modal to show when checking in items with fees.  I added the 
permission to the checkin endpoint.

CIRC-1117: Permissions error when checking in items with fees

---

src/main/java/org/folio/circulation/domain/notice/PatronNoticeService.java
src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
src/main/java/org/folio/circulation/services/EventPublisher.java
src/test/java/api/queue/RequestQueueResourceTest.java
src/test/java/api/requests/RequestsAPIUpdatingTests.java
src/test/java/api/requests/scenarios/MoveRequestTests.java

[CIRC-1126](https://issues.folio.org/browse/CIRC-1126) - Errors when filtering on recall requested
Fixing loan log records duplication, invalid source name.
Removing unnecessary log record event publishing.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …

CIRC-1126 - Errors when filtering on recall requested

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Reverting permissions added as part of CIRC-1117.  It was determined that these 
were front-end permissions.

reverting permissions changes

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
doc/developer-guide.md
doc/operations-guide.md

Moves the age to lost processes back to the `_timer` interface.
During 2021 R1, the age to lost processes were moved to a separate interface so they could be scheduled by each organisation as needed.
We received feedback that this approach was too cumbersome for hosting providers / implementors.
In the mean time, additional features (cron scheduling and runtime configuration of schedules) were added to Okapi in version 4.8.0 which allows these to be moved back to to the `_timer` whilst preserving the level of configurability expected.
* Move the endpoints back to the `_timer` interface
* Remove the redundant separate interface documentation
* Briefly describe these endpoints in the (new) operations guide
Before merging this PR, please go through the following list and take appropriate …

Move age to lost processes back to timer CIRC-1144

---

src/main/java/org/folio/circulation/services/EventPublisher.java
src/test/java/api/loans/RenewalAPITests.java
src/test/java/api/support/matchers/EventActionMatchers.java
src/test/java/api/support/matchers/EventMatchers.java

[CIRC-1165](https://issues.folio.org/browse/CIRC-1165) - Circ log filter for renewed doesn't work
To show a row with the item just renewed in circulation logs.
Add option to publish event with Renewed action when context is renewal.

CIRC-1165 - Circ log filter for renewed doesn't work

---

src/main/java/org/folio/circulation/rules/CirculationRulesProcessor.java
src/test/java/api/CirculationRulesEngineAPITests.java
src/test/java/api/support/RestAssuredClient.java
src/test/java/api/support/fixtures/CirculationRulesFixture.java

It has been [requested](https://issues.folio.org/browse/CIRC-1170) that the circulation rules endpoints should respond with a validation error rather than a server error when a location that does not exist is used to evaluate them.
* Wrote a test to demonstrate the server error
* Change the test to expect a validation error
* Change the implementation to make the test pass
- Do PRs exist …

Respond with a validation error when evaluating rules and location does not exist CIRC-1170

---

NEWS.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/Environment.java
src/main/java/org/folio/circulation/domain/anonymization/service/LoansForTenantFinder.java
src/main/java/org/folio/circulation/resources/ScheduledAnonymizationProcessingResource.java

At the moment, only 5000 closed loans are checked each time scheduled anonymization runs.
For organisations that have many closed loans with outstanding fees / fines, this leads to some loans never being checked as they aren't in the 5000 chosen.
This is a temporary solution for Cornell until more significant changes can be made to how anonymization works.
* Increase the number of loans to check to 50 000 (and provide an environment variable for overriding)
* Increase the frequency of runs of scheduled anonymization to every 60 minutes (can be overridden in Okapi)
* Increase the default memory allocation to compensate for fetching more loans
- Does this PR meet or exceed the expected quality …

Check more loans for anonymization CIRC-1178

---

src/main/java/org/folio/circulation/domain/OpeningDay.java
src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
src/main/java/org/folio/circulation/domain/policy/FixedDueDateSchedules.java
src/main/java/org/folio/circulation/domain/policy/library/ClosedLibraryStrategyUtils.java
src/main/java/org/folio/circulation/domain/policy/library/EndOfCurrentHoursStrategy.java
src/main/java/org/folio/circulation/domain/policy/library/EndOfNextOpenDayStrategy.java
src/main/java/org/folio/circulation/domain/policy/library/EndOfPreviousDayStrategy.java
src/main/java/org/folio/circulation/domain/policy/library/EndOfPreviousDayTruncateStrategy.java
src/main/java/org/folio/circulation/domain/policy/library/KeepCurrentDateStrategy.java
src/main/java/org/folio/circulation/resources/DueDateNotRealTimeScheduledNoticeProcessingResource.java
src/main/java/org/folio/circulation/support/utils/DateTimeUtil.java
src/test/java/api/loans/CheckOutByBarcodeFixedDueDateScenariosTest.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/loans/CheckOutCalculateDueDateTests.java
src/test/java/api/loans/RenewalAPITests.java
src/test/java/api/requests/RequestScheduledNoticesProcessingTests.java
src/test/java/api/requests/RequestScheduledNoticesTests.java
src/test/java/api/requests/RequestsAPIRetrievalTests.java
src/test/java/api/requests/scenarios/HoldShelfExpirationDateTests.java
src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java
src/test/java/api/requests/scenarios/MoveRequestTests.java
src/test/java/api/support/OpeningPeriod.java
src/test/java/api/support/builders/FixedDueDateSchedule.java
src/test/java/org/folio/circulation/domain/policy/FixedLoanPolicyRenewalDueDateCalculationTests.java
src/test/java/org/folio/circulation/domain/policy/library/KeepCurrentStrategyTest.java
src/test/java/org/folio/circulation/support/utils/DateTimeUtilTests.java

A staged approach is being used to implement all of the necessary changes for resolving [CIRC-966](https://issues.folio.org/browse/CIRC-966).
This is Stage 4: For CU & DTU, start of day and end of day methods.
Update all operations where start of day and end of day are calculated to use the utility.
Operations such as start of year or end of month are also updated to use the utility.
There are some serious concerns with how start and end datetimes are calculated relative to the time zones.
For this reason, review this in full as there are likely controversial changes.
The start and end of day utility methods are implemented along with their respective tests and are in use.
I discovered that there are also start/end of year and start/end of month.
These utility methods have also been …

CIRC-966: Stage 4, For CU & DTU, start of day and end of day methods.

---

CODEOWNERS
PULL_REQUEST_TEMPLATE.md

Removes the code owners definition as it led to unnecessary notifications that folks started ignoring
Removes the check list from the pull request template as folks aren't using it
* Folks start to ignore notifications after a certain threshold of irrelevant notifications have been received
* Folks seem to ignore the check lists on pull requests

Remove code owners and checklist CIRC-1215

---

descriptors/ModuleDescriptor-template.json

`circulation-storage.patron-notice-policies.item.get` was missing from
`modperms.circulation.check-out-by-barcode.post`, preventing notices
from being sent to patrons because the staff-member did not have the
necessary permission, causing a silent failure.
Adding the missing permission.
If nobody notices they didn't receive a notice, does anybody notice? 
Refs [CIRC-1214](https://issues.folio.org/browse/CIRC-1214)

CIRC-1214 check-out should allow notice policy access

---

src/main/java/org/folio/circulation/domain/representations/StoredAccount.java
src/test/java/api/loans/DeclareLostAPITests.java
src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
src/test/java/org/folio/circulation/domain/OverdueFineCalculatorServiceTest.java

Resolves [CIRC-1174](https://issues.folio.org/browse/CIRC-1174)
Fee/fine (Account) schema was extended with `contributors` field on `mod-feesfines` side, now we need to add this field on `mod-circulation` side. This field needs to be populated when Overdue fines and Lost item / Lost item processing fees are created.
Change StoredAccount class, change tests for Overdue fines and Lost item / Lost item processing fees.

CIRC-1174 Add contributors fields to fee/fine records

---

pom.xml
src/main/java/org/folio/circulation/services/PubSubPublishingService.java
src/test/java/api/support/fixtures/TenantActivationFixture.java
src/test/java/api/support/matchers/PubSubRegistrationMatchers.java

Upgrade raml-module-builder (RMB) from 31.1.0 to 33.1.1.
Upgrade Vert.x from 4.1.1 to 4.2.1.
Upgrade mod-pubsub-client from 2.0.7 to 2.4.0.
The new mod-pubsub-client has renamed PubSubClientUtils.constructModuleName()
to PubSubClientUtils.getModuleId() resulting in code changes in mod-circulation.

CIRC-1326: RMB 33.1.1, Vert.x 4.2.1, PubSub 2.4.0

---

src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/requests/PickSlipsTests.java

Replace ZoneId.systemDefault() by UTC to make the test independent
of the build server time zone.

CIRC-1327: Tests fail if build server time zone is not UTC

---

src/main/java/org/folio/circulation/domain/RequestQueue.java
src/main/java/org/folio/circulation/resources/LoanCollectionResource.java
src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java
src/test/java/api/loans/scenarios/ChangeDueDateByReplacingLoanTests.java

Apply the same due date changed by recall flag resetting logic as renewal and explicit change due date operations when changing a loan via replacement (PUT)
* Uses the same logic as for the other places where the flag is reset
* There is some duplication between the three places where this flag is reset when a due date is changed

Circ 1112 reset due date changed flag during loan replacement

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/circulation/resources/ChangeDueDateResource.java
src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java

Consider title-level requests and TLR feature settings when performing the following validation during due date change
- Added logic to ChangeDueDateResource and unsetDueDateChangedByRecallIfNoOpenRecallsInQueue with purpose to get tlr settings and according to their values fulfill unsetting of dueDateChangedByRecall property;
- Added tests;
https://issues.folio.org/browse/CIRC-1362

CIRC-1362 Consider TLR when changing loan due date

---

src/test/java/api/loans/scenarios/ChangeDueDateAPITests.java

The changes in the previous pull request did not remove the possibility of erroneous failures in this test, caused by mismatches in accuracy in due date comparisons.
Rather than change the assertion to be more reliable, it has been removed as it was for details about an
intermediary step that is unimportant for this test.

Remove unnecessary assertions for intermediary step CIRC-1365

---

src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/LoanAction.java
src/main/java/org/folio/circulation/domain/representations/logs/LogContextActionResolver.java
src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java

[CIRC-1373](https://issues.folio.org/browse/CIRC-1373) - Add new Action when an automated fee/fine is charged if item is aged to lost
Add new Action after starting aged to lost items charging process if item aged to lost, and if there is Lost item fee policy with Items aged to lost after overdue setting, and if there is fee/fine owner for service point.

CIRC-1373 - Add new Action when an automated fee/fine is charged if item is aged to lost

---

src/main/java/org/folio/circulation/domain/Contributor.java
src/main/java/org/folio/circulation/domain/Identifier.java
src/main/java/org/folio/circulation/domain/Instance.java
src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/RequestRepresentation.java
src/main/java/org/folio/circulation/domain/StoredRequestRepresentation.java
src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/main/java/org/folio/circulation/domain/representations/ContributorsToNamesMapper.java
src/main/java/org/folio/circulation/domain/representations/InstanceProperties.java
src/main/java/org/folio/circulation/domain/representations/ItemProperties.java
src/main/java/org/folio/circulation/domain/representations/ItemReportRepresentation.java
src/main/java/org/folio/circulation/domain/representations/ItemSummaryRepresentation.java
src/main/java/org/folio/circulation/domain/representations/StoredAccount.java
src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
src/main/java/org/folio/circulation/storage/mappers/ContributorMapper.java
src/main/java/org/folio/circulation/storage/mappers/IdentifierMapper.java
src/main/java/org/folio/circulation/storage/mappers/InstanceMapper.java
src/main/java/org/folio/circulation/support/json/JsonPropertyWriter.java
src/test/java/api/requests/PickSlipsTests.java
src/test/java/org/folio/circulation/domain/InstanceTests.java
src/test/java/org/folio/circulation/domain/ItemTests.java
src/test/java/org/folio/circulation/domain/OverdueFineServiceTest.java
src/test/java/org/folio/circulation/support/JsonPropertyWriterTest.java

In order to reduce the coupling on the storage representations within the domain model e.g. to allow for instantiating it from other sources / representations, the use of a JSON object for the instance related to an item should be removed
* Introduce basic domain model for contributors
* Introduce basic domain model for identifiers
* Introduce basic domain model for instances
* Move information about contributors and identifiers to instance domain class
* Remove JSON representations

Remove json from instance in domain CIRC-1366

---

src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/MaterialType.java
src/main/java/org/folio/circulation/domain/representations/ItemSummaryRepresentation.java
src/main/java/org/folio/circulation/domain/representations/logs/RequestUpdateLogEventMapper.java
src/main/java/org/folio/circulation/domain/validation/ItemLimitValidator.java
src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
src/main/java/org/folio/circulation/infrastructure/storage/inventory/MaterialTypeRepository.java
src/main/java/org/folio/circulation/storage/mappers/MaterialTypeMapper.java
src/test/java/org/folio/circulation/domain/ItemTests.java
src/test/java/org/folio/circulation/domain/OverdueFineServiceTest.java

In order to reduce the coupling on the storage representations within the domain model e.g. to allow for instantiating it from other sources / representations, the use of a JSON object for the material type related to an item should be removed
* Introduce basic domain model for material type
* Move mapping from JSON to domain model out of the domain
* Remove JSON representations

Remove json from material type in domain CIRC-1367

---

src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/LoanType.java
src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
src/main/java/org/folio/circulation/storage/mappers/LoanTypeMapper.java
src/test/java/org/folio/circulation/domain/ItemTests.java

In order to reduce the coupling on the storage representations within the domain model e.g. to allow for instantiating it from other sources / representations, the use of a JSON object for the loan type related to an item should be removed
* Introduce basic domain model for loan type
* Move mapping from JSON to domain model out of the domain
* Remove JSON representations
* Disallow null loan type (in order to avoid null checks on every usage)

Remove json from loan type in domain CIRC-1368

---

src/main/java/org/folio/circulation/domain/ServicePoint.java
src/main/java/org/folio/circulation/domain/TimePeriod.java
src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
src/main/java/org/folio/circulation/storage/mappers/ServicePointMapper.java
src/main/java/org/folio/circulation/storage/mappers/TimePeriodMapper.java
src/test/java/org/folio/circulation/domain/OverdueFineServiceTest.java
src/test/java/org/folio/circulation/domain/RequestRepresentationTests.java

In order to reduce the coupling on the storage representations within the domain model e.g. to allow for instantiating it from other sources / representations, the use of a JSON object for the service point related to an item should be removed
* Remove JSON representations from service point domain class
* Remove JSON representations from time period domain class
* Move mapping from JSON to domain model out of the domain

Remove json from service point in domain CIRC-1369

---

pom.xml

[CIRC-1387](https://issues.folio.org/browse/CIRC-1387)
Update Log4j to a newer version with CVE-2021-44228 vulnerability fixed.
Update version in pom

CIRC-1387 Upgrade Log4j to v2.16.0

---

src/main/java/org/folio/circulation/domain/validation/RequestQueueValidation.java
src/test/java/api/queue/RequestQueueResourceTest.java

Change requests queue behavior to place the page requests at the queue top 
Moved condition which allowed to place the page requests at the queue top.
https://issues.folio.org/browse/CIRC-1397

CIRC-1397 Disable request queue validation for page requests always being at the top

---

src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
src/main/java/org/folio/circulation/services/agedtolost/LoanToChargeFees.java
src/test/java/api/handlers/CloseAgedToLostLoanWhenLostItemFeesAreClosedApiTests.java

Fix NPE for the loans which have nonexistent an item and handle a situation when it happens;
NPE happens during owners fetching. The loans with nonexistent items should be excluded from age-to-lost charging processing;
Resolves: [CIRC-1386](https://issues.folio.org/browse/CIRC-1386)

CIRC-1386 fix NPE for age-to-lost charging

---

src/main/java/org/folio/circulation/domain/RequestQueue.java
src/test/java/api/requests/RequestsAPICreationTests.java
src/test/java/api/support/http/CqlQuery.java

Scenario:
One instance with two items (item1 and item2), both "Available" or "In transit".
Two TLR page requests created (request1 for item1 and request2 for item2), both of them are linked to items, which means that items become "Paged" and requests now have itemIds and status "Open - not yet filled".
Now, when item2 is checked in, request2 should become either "Open - awaiting pickup" or "Open - in transit" depending on the item's status, but request1 shouldn't be updated because it's linked to another item.
- update filtering of existing request fulfillment with item;
- create tests;
Resolves: [CIRC-1403](https://issues.folio.org/browse/CIRC-1403)

CIRC-1403 add filtering by itemId, create test

---

descriptors/ModuleDescriptor-template.json

This should have been part of #1022 but was missed.
In fact, it appears there were no changes to the `request-storage` API from `3.4` to `4.0` so it is not clear to me why the interface version changed. Maybe, since the shape of a `request` is changing to handle TLR fields, that transitive change bubbles up to the interface version? Anyway, just bumping the interface feels a bit naive, but it isn't clear to me what else I should investigate to make sure this change is sufficient 😬. 
Refs [CIRC-1407](https://issues.folio.org/browse/CIRC-1407), [FOLIO-3376](https://issues.folio.org/browse/CIRC-1407)

CIRC-1407 require request-storage 4.0

---

src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestRepository.java
src/test/java/api/queue/RequestQueueResourceTest.java
src/test/java/api/support/fixtures/ItemExamples.java
src/test/java/api/support/fixtures/ItemsFixture.java

[CIRC-1402](https://issues.folio.org/browse/CIRC-1402)
_Extend requests returned by queue API with additional fields_

CIRC-1402: Extend requests returned by queue API with additional fields

---

src/test/java/api/requests/scenarios/LoanDueDatesAfterRecallTests.java

Use isEquivalentTo matcher to fix this error:
LoanDueDatesAfterRecallTests.shouldNotExtendLoanDueDateIfOverdueLoanIsRecalled:814
Expected: Json path ["dueDate"] is "2022-01-13T10:12:02Z"
but: Expected json path ["dueDate"] evaluated to is "2022-01-13T10:12:02Z" but actual ["2022-01-13T10:12:02.000Z"]

CIRC-1417: Fix dueDate comparison in LoanDueDatesAfterRecallTests

---

pom.xml
src/main/java/org/folio/circulation/domain/notice/PatronNoticeService.java
src/main/java/org/folio/circulation/infrastructure/storage/notices/ScheduledNoticesRepository.java
src/main/java/org/folio/circulation/support/http/ContentType.java
src/main/java/org/folio/circulation/support/http/client/Response.java
src/main/java/org/folio/circulation/support/http/client/VertxWebClientOkapiHttpClient.java
src/main/java/org/folio/circulation/support/http/server/ClientErrorResponse.java
src/main/java/org/folio/circulation/support/http/server/ServerErrorResponse.java
src/test/java/org/folio/circulation/support/http/ContentTypeTest.java
src/test/java/org/folio/circulation/support/http/client/ResponseInterpretationTests.java

pom.xml adds org.apache.httpcomponents:httpclient-osgi and org.apache.httpcomponents:httpclient-cache as runtime dependencies.
They result in 1.2 MB of code in the final mod-circulation.jar because of indirect dependencies:
* org.apache.httpcomponents:fluent-hc:jar:4.5.8
* org.apache.httpcomponents:httpclient-cache:jar:4.5.8
* org.apache.httpcomponents:httpclient-osgi:jar:4.5.8
* org.apache.httpcomponents:httpclient:jar:4.5.8
* org.apache.httpcomponents:httpcore:jar:4.4.11
* org.apache.httpcomponents:httpmime:jar:4.5.8
These libraries are deprecated: "Users of HttpCore 4.x are strongly encouraged to migrate to HttpCore 5.x" https://hc.apache.org/status.html
The libraries are needed for 6 String constants only.
To avoid bloating the final jar these 6 String contstants are taken from other …

CIRC-1414: Remove org.apache.httpcomponents:httpclient-*

---

Jenkinsfile
README.md

Adds the `doApiDoc` configuration to Jenkinsfile, which enables the [api-doc](https://dev.folio.org/guides/api-doc/) CI facility. This generates and publishes the API documentation during a merge to mainline and on release.
The `doApiLint` ([api-lint](https://dev.folio.org/guides/api-lint/)) was already configured.
The https://dev.folio.org/reference/api/#mod-circulation section of API documentation will be automatically reconfigured tomorrow:
https://dev.folio.org/reference/api/#explain-gather-config

FOLIO-3231 Use api-doc CI facility

---

src/main/java/org/folio/circulation/domain/RequestQueue.java
src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/requests/scenarios/HoldShelfFulfillmentTests.java
src/test/java/api/support/fixtures/RequestsFixture.java
src/test/java/org/folio/circulation/domain/RequestQueueTests.java

https://issues.folio.org/browse/CIRC-1412
When an item is checked in and it fulfils a request, this request's position needs to be changed to 1 and the whole request queue should be updated accordingly. This logic was already implemented for item-level requests, it now needs to be supported by the unified queue.

CIRC-1412 - Requests should change position when they go in fulfilment on check-in

---

src/test/java/api/requests/InstanceRequestsAPICreationTests.java

When creating a request using the basic TLR implementation, more then ten items associated with an instance should be checked for availability. And if such items are available, page request should be created via  /patron/account/<userId>/instance/<instanceId>/hold
- Test refactoring (Inline higher limit variable)
https://issues.folio.org/browse/CIRC-1413

CIRC-1413 Inline higher limit variable

---

src/main/java/org/folio/circulation/domain/CheckInContext.java
src/main/java/org/folio/circulation/domain/RequestQueue.java
src/main/java/org/folio/circulation/domain/UpdateItem.java
src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
src/test/java/api/loans/CheckInByBarcodeTests.java

https://issues.folio.org/browse/CIRC-1421
NPE thrown when an item is checked in and there are fulfillable requests in the unified queue (TLR is enabled), but they are not fulfillable by the item that is checked in. The reason is that item-specific method updateOutstandingRequestOnCheckIn() is called when requestQueue.hasOutstandingFulfillableRequests() (that checks for fulfillable items, not necessarily fulfillable by the same item) returns true.
Another item-specific method hasOutstandingFulfillableByItemRequests() needs to be added.

CIRC-1421 - During check-in only update fulfillable request if it's for the same item

---

src/main/java/org/folio/circulation/domain/notice/schedule/LoanScheduledNoticeService.java
src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
src/main/java/org/folio/circulation/resources/handlers/error/CirculationErrorType.java
src/test/java/api/loans/CheckOutByBarcodeTests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/fakes/FakeStorageModule.java

Check out should respond with 200 in case of partially successful checkout. For full successful checkout, the status code should not be changed.
Implement error handling for all actions that follow after creating a loan in the storage. After creating it, an item status should be "checked out" and these not critical issues should be handled with 200 status.
Resolves: [CIRC-1046](https://issues.folio.org/browse/CIRC-1046)

CIRC-1046 add handling for not critical errors for check-out

---

descriptors/ModuleDescriptor-template.json

[CIRC-1433](https://issues.folio.org/browse/CIRC-1433)
_Missed permission for /circulation/check-in-by-barcode endpoint_

CIRC-1433: Missed permission for /circulation/check-in-by-barcode endpoint

---

src/main/java/org/folio/circulation/domain/notice/schedule/LoanScheduledNoticeHandler.java
src/test/java/api/loans/DueDateScheduledNoticesProcessingTests.java

- Scheduled notices with the time triggers: before once, before recurring, after once should be included in the removing list as not relevant;
Resolves: [CIRC-1427](https://issues.folio.org/browse/CIRC-1427)
- update LoanScheduledNoticeHandler;
- add test;
- fix broken tests;

CIRC-1427 update removing scheduled notices logic

---

src/main/antlr4/org/folio/circulation/rules/CirculationRules.g4
src/main/java/org/folio/circulation/rules/Text2Drools.java
src/test/java/org/folio/circulation/rules/Text2DroolsTest.java

The goal is to fix saving rules when they have unfinished criteria ( without ':' and without policies )
[CIRC-1331](https://issues.folio.org/browse/CIRC-1331)
Add rule for fallback-policy and add handler for checking stetements

CIRC-1331 Add rule for checking ':' before policy

---

src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/MultipleRecords.java
src/main/java/org/folio/circulation/infrastructure/storage/IdentityMap.java
src/main/java/org/folio/circulation/infrastructure/storage/feesandfines/FeeFineOwnerRepository.java
src/main/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepository.java
src/main/java/org/folio/circulation/infrastructure/storage/loans/LoanRepository.java
src/main/java/org/folio/circulation/storage/mappers/ItemMapper.java
src/main/java/org/folio/circulation/support/utils/CollectionUtil.java
src/test/java/org/folio/circulation/infrastructure/storage/IdentityMapTests.java
src/test/java/org/folio/circulation/infrastructure/storage/inventory/ItemRepositoryTests.java

In order to make it easier to change the way circulation interacts with inventory records, the representation in the domain could be separated more from the underlying representation of the records in inventory storage.
Using PUT requests to make changes to an item record means that the full storage representation needs to be available when changes are made.
Currently, the module keeps that representation within the domain.
A step in removing that representation from the domain is to move the copy of the representation in the item repository instead of the domain class.
For more information, refer to [CIRC-1454](https://issues.folio.org/browse/CIRC-1454)
* Introduce the identity map into the repository
* Remove public access to the item representation in the item domain class
* Improve …

CIRC-1454 Use Identity Map to Cache Item Representation

---

src/main/java/org/folio/circulation/infrastructure/storage/loans/LoanRepository.java
src/test/java/api/requests/RequestsAPICreationTests.java

Fix automated patron blocks feature based on placed recall requests with enabled tlr feature
- Adjusted LoanRepository, RequestFromRepresentationService
- Test added
https://issues.folio.org/browse/CIRC-1471

CIRC-1471 Two recall-related automated patron blocks are not being enforced

---

src/test/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicyTest.java

The mainline [build](https://jenkins-aws.indexdata.com/job/folio-org/job/mod-circulation/job/master/971) of mod-circulation currently fails.
This test failure is caused by using the current date / time as the basis for other relative date / times.
One of those scenarios is for moving the current date / time back by 6 months. Unfortunately, that leads to the date being the 30th instead of the 31st because September has 30 days rather than 31.
This can be resolved by using a fixed started point rather than relying on the current system date / time

Use fixed date time during refund processing tests CIRC-1494

---

src/main/java/org/folio/circulation/domain/UpdateLoan.java
src/main/java/org/folio/circulation/domain/policy/library/ClosedLibraryStrategyService.java
src/test/java/api/requests/scenarios/RecallItemsTests.java

Resolves: https://issues.folio.org/browse/CIRC-1497
When recalling loans with fixed due date loan policies that have been renewed in a new loan period or had their due dates changed to a date after the original due date, the loan's due date is being set to the due date specified for the original fixed due date period for the loan's loanDate.
When fetching fixed period for deciding on the due date, get a schedule in which a loan due date falls into.

CIRC-1497 Get fixed period for loan due date during recall

---

src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
src/test/java/api/requests/InstanceRequestsAPICreationTests.java
src/test/java/api/support/builders/RequestByInstanceIdRequestBuilder.java

Resolves: https://issues.folio.org/browse/CIRC-1507
When creating the instance level request via mod-patron, the user receives the error. This happens because on mod-circulation side we are still looking for the request level field in the json from the mod-patron, which does not pass tit any more.
Pass requestLevel -> Item when creating item level requests

CIRC-1507 When TLR feature is disabled, assign ILR during instance level requests creation

---

src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/main/java/org/folio/circulation/domain/notice/schedule/GroupedLoanScheduledNoticeHandler.java
src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledNoticeHandler.java
src/test/java/api/loans/DueDateNotRealTimeScheduledNoticesProcessingTests.java

Failure to build the template context for one individual overnight notice causes the processing of the whole group of overnight notices to fail. We should build context individually for each notice and remove the broken notice from the group before we attempt to send it.
Resolves [CIRC-1515](https://issues.folio.org/browse/CIRC-1515).

[CIRC-1515] Delete overnight notice when failed to build template context for it

---

src/main/java/org/folio/circulation/services/feefine/CancelAccountRequest.java
src/test/resources/fee-fine-cancel-operation-16-1.json

Resolves: https://issues.folio.org/browse/CIRC-1532
When creating Cancel Action Request, mod-circulation should not fill the comments field with a dash.

CIRC-1532 Don't pass dash comment with lost item fees

---

pom.xml

https://issues.folio.org/browse/CIRC-1539
Upgrade dependencies fixing security vulnerabilities.
Upgrade Vert.x from 4.2.1 to 4.2.7. This indirectly upgrades jackson-databind from 2.11.4 to 2.13.2.1 fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2020-36518
Upgrade Spring from 5.2.7 to 5.2.22 fixing Spring4Shell vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-22965
Upgrade mod-pubsub-client from 2.4.0 to 2.4.3 fixing Socket Leaks.
Upgrade xstream from 1.4.16 to 1.4.19 fixing Arbitrary Code Execution: many CVEs, see complete list at https://x-stream.github.io/security.html#CVEs , for example https://nvd.nist.gov/vuln/detail/CVE-2021-39139

CIRC-1539: Upgrade vulnerable dependencies (Vert.x, Spring, xstream)

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/circulation/domain/OverdueFineService.java
src/main/java/org/folio/circulation/domain/representations/StoredAccount.java
src/main/java/org/folio/circulation/services/LostItemFeeChargingService.java
src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
src/main/java/org/folio/circulation/services/support/CreateAccountCommand.java
src/test/java/api/loans/DeclareLostAPITests.java
src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
src/test/java/api/support/matchers/OverdueFineMatcher.java

- save policy ids in an account, to avoid cleaning up after anonymization;
- create tests;
Resolves: [CIRC-1526](https://issues.folio.org/browse/CIRC-1526)

CIRC-1526 Add policy IDs to the Account record

---

src/main/java/org/folio/circulation/services/EventPublisher.java
src/test/java/api/requests/RequestsAPIUpdatingTests.java

[CIRC-1565](CIRC-1565 - request record is not correctly stored in the log.) - request record is not correctly stored in the log.
The source of an edit to a request record is not correctly stored in the log.
This is a problem when attempting to determine why a request was edited.
* Fixed event publisher logic

CIRC-1565 - request record is not correctly stored in the log.

---

pom.xml
src/main/java/org/folio/circulation/domain/policy/lostitem/LostItemPolicy.java
src/main/java/org/folio/circulation/services/agedtolost/ChargeLostFeesWhenAgedToLostService.java
src/main/java/org/folio/circulation/services/agedtolost/LoanToChargeFees.java
src/main/java/org/folio/circulation/support/results/Result.java
src/test/java/api/handlers/CloseAgedToLostLoanWhenLostItemFeesAreClosedApiTests.java
src/test/java/api/loans/agetolost/ScheduledAgeToLostFeeChargingApiTest.java
src/test/java/api/loans/scenarios/OverrideRenewAgedToLostItemTest.java

Resolves : [https://issues.folio.org/browse/CIRC-1432](https://issues.folio.org/browse/CIRC-1432)
The processing of aged to lost actual cost items should be skipped when 'Charge lost item processing fee if item aged to lost by system?' is set to `No` in the Lost item policy (except `lostItemHasBeenBilled` should be changed to `True`).
Additional step is added to `ChargeLostFeesWhenAgedToLostService` service that excludes such loans from the list of loans that fees/fines or actual cost records will be created for.

CIRC-1432 Actual cost - close aged to lost loan as paid when no processing fee should be charged

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/CIRC-1596
mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
mod-circulation is not affected because the incompatible change is in the DELETE all APIs only that is not used by mod-circulation.
Only the okapiInterfaces need to be bumped in "requires" section of ModuleDescriptor-template.json

CIRC-1596: instance-storage 9.0, holdings-storage 6.0, item-storage 10.0

---

src/main/java/org/folio/circulation/domain/validation/CheckOutValidators.java
src/main/java/org/folio/circulation/domain/validation/ItemLimitValidationErrorCause.java
src/main/java/org/folio/circulation/domain/validation/ItemLimitValidator.java
src/test/java/api/loans/CheckOutByBarcodeTests.java

- UI needs to receive itemLimit as a parameter to be able to translate error message properly. itemLimit parameter object should be added to the parameters array of the error when patron reaches item limit during check-out
Resolves: [CIRC-1574](https://issues.folio.org/browse/CIRC-1574)

CIRC-1574 Add itemLimit parameter to the item limit error

---

src/main/java/org/folio/circulation/domain/representations/logs/CirculationCheckInCheckOutLogEventMapper.java
src/main/java/org/folio/circulation/resources/CheckInByBarcodeResource.java
src/main/java/org/folio/circulation/services/EventPublisher.java
src/test/java/api/requests/RequestsAPICreationTests.java

[CIRC-1604](https://issues.folio.org/browse/CIRC-1604) - Circ log: user barcodes missing in request actions
When filtering on an item barcode in the circulation log, actions associated with a request do not show the user barcode
Retrieve user barcode from the last loan for item.

CIRC-1604 - Circ log: user barcodes missing in request actions

---

src/main/java/org/folio/circulation/domain/UpdateItem.java
src/main/java/org/folio/circulation/resources/RequestCollectionResource.java
src/test/java/api/requests/RequestsAPIDeletionTests.java

Resolves CIRC-1569
When page request is created, item status changes to `Paged`. After that, when such request is deleted, item status stays `Paged` which is incorrect because there are no page request associated with this item.
Change item status back to `Available` when page request is deleted

CIRC-1569 Change item status on request deletion

---

pom.xml
src/main/java/org/folio/circulation/services/PubSubPublishingService.java

Upgrade jackson-databind from 2.13.2.1 to 2.13.4.2 fixing Denial of Service (DoS https://nvd.nist.gov/vuln/detail/CVE-2022-42003
https://nvd.nist.gov/vuln/detail/CVE-2022-42004
Upgrade commons-codec from 1.11 to 1.15 fixing Information Exposure: https://app.snyk.io/vuln/SNYK-JAVA-COMMONSCODEC-561518
Upgrade mod-pubsub-client from 2.4.3 to 2.7.0.
Upgrading mod-pubsub-client indirectly upgrades plexus-utils from 3.0.22 to 3.3.1 fixing Directory Traversal https://app.snyk.io/vuln/SNYK-JAVA-ORGCODEHAUSPLEXUS-31521
Upgrading mod-pubsub-client indirectly upgrades spring-beans from 5.2.8.RELEASE to 5.2.22.RELEASE fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2022-22970
Upgrading mod-pubsub-client removes the unused spring-beans dependency that was version 5.2.8.RELEASE and …

CIRC-1639: Upgrade vulnerable dependencies

---

pom.xml

Upgrade org.apache.commons:commons-text from 1.9 to 1.10.0.
mod-circulation uses only StringEscapeUtils.escapeJava: https://github.com/folio-org/mod-circulation/blob/v23.1.5/src/main/java/org/folio/circulation/rules/Text2Drools.java#L4
This is not affected by this Remote Execution vulnerability in commons-text before 1.10.0: https://nvd.nist.gov/vuln/detail/CVE-2022-42889
However, to avoid false positive reports by security scanners like Snyk we bump the version.

CIRC-1637: commons-text 1.10.0

---

src/main/java/org/folio/circulation/domain/RequestQueue.java
src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java
src/test/java/api/requests/RequestsAPICreationTests.java
src/test/java/api/support/fixtures/ItemsFixture.java
src/test/java/org/folio/circulation/domain/RequestQueueTests.java

Resolves [CIRC-1655](https://issues.folio.org/browse/CIRC-1655)
mod-circulation fails to send an "Awaiting pickup" patron notice in this scenario:
- Create an instance and a holdings record with no items
- Create a hold TLR for this instance
- Create an item
- Check-in the item
When new instance of a request is created with one of the "with" methods, the request queue still holds the old instance of the request which is not updated. Now we replace the old instance with the new.

CIRC-1655 Send TLR awaiting pickup notice on check in

---

src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
src/test/java/api/requests/RequestsAPICreationTests.java

Resolves [CIRC-1684](https://issues.folio.org/browse/CIRC-1684)
TLR recalls were only allowed for "Awaiting pickup", "Paged", "Awaiting delivery" items only. They should be also allowed for "In transit", "In process", "On order" item statuses.
Use the same white list of item statuses that ILR recalls use

CIRC-1684 Allow TLR recalls for In transit, In process, On order items

---

src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
src/test/java/api/requests/RequestsAPICreationTests.java
src/test/java/api/support/fixtures/AgeToLostFixture.java

Unable to recall items with status In process, In transit, On order when TLR is enabled
Resolves: [CIRC-1683](https://issues.folio.org/browse/CIRC-1683)
- add logic for ignoring items with the statuses above;
- add tests;

[CIRC-1683] Add unable for recall item statuses

---

src/main/java/org/folio/circulation/domain/RequestQueue.java
src/test/java/api/requests/RequestsAPICreationTests.java

- Fix issue with searching the least recalled loans;
Resolves: [CIRC-1696](https://issues.folio.org/browse/CIRC-1696)
- Ignore loans with not recallable items;
- Add test;

CIRC-1696 Fix issue with searching the least recalled loans

---

src/main/java/org/folio/circulation/domain/User.java
src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/support/builders/UserBuilder.java
src/test/java/api/support/fixtures/TemplateContextMatchers.java
src/test/java/api/support/fixtures/UserExamples.java

https://issues.folio.org/browse/CIRC-1587
Please add the field "requester.preferredFirstName" to the Requester Object in the Staff Slip context, for hold, request delivery and transit slips generated in the Check in app.
Scenario:
Given: I have printed out the staff slip, the template of which contains the token “requester.preferredFirstName” + the user's Prefered first name is populated,
When: I look at the text of that token on the piece of paper,
Then: I see the plain text name of the Prefered first name, as can be seen in the UI of Users.
Example: On the piece of paper, I see “Jules”, and NOT "Julie".
Scenario:
Given:  I have printed out the staff slip, the template of which contains the token “requester.preferredFirstName” + the user's Prefered first name is not populated,
When: I …

CIRC1587 ( Add the field "requester.preferredFirstName" )

---

ramls/loan-anonymization.raml
src/main/java/org/folio/circulation/domain/representations/anonymization/AnonymizeLoansRepresentation.java
src/test/java/org/folio/circulation/domain/representations/anonymization/AnonymizeLoansRepresentationTest.java

Front-end parses loanIds as serialized JSON array:
```
[
{ "key": "loadnIds", "value": "[\"f14e4831-ca99-4f8e-bc2e-6c5e72e071d8\",\"a8e964ff-81b3-489e-aa81-6d97aa1bc601\"] }
]
```
Wrap loan ids into a JSON array and then serialized it to conform to the error.schema/parameters.schema RAML spec.
Document this hack in RAML and source code and add unit test.
The parameters.schema RAML spec is already an array that allows any number of parameters:
```
[
{ "key": "loadnId", "value": "f14e4831-ca99-4f8e-bc2e-6c5e72e071d8" },
{ "key": "loadnId", "value": "a8e964ff-81b3-489e-aa81-6d97aa1bc601" }
]
```
There has never been a need for a hack like this where a JSON array is forced into a single JSON String by serializing the array.

CIRC-1731: haveAssociatedFeesAndFines serialized JSON array

---

src/main/java/org/folio/circulation/domain/CreateRequestService.java
src/main/java/org/folio/circulation/domain/validation/RequestLoanValidator.java
src/main/java/org/folio/circulation/resources/RequestByInstanceIdResource.java
src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
src/main/java/org/folio/circulation/storage/ItemByInstanceIdFinder.java
src/test/java/api/requests/RequestsAPICreationTests.java

Resolves [CIRC-1677](https://issues.folio.org/browse/CIRC-1677)
Hold TLRs for titles with no holdings records should be allowed
Remove validation failure when no holdings record could be found for a particular instance ID.
Error message may change when instance doesn't exist

CIRC-1677 Allow hold TLR for a title with no HRs

---

descriptors/ModuleDescriptor-template.json

Add missed permissions for fee-fine-scheduled-notices-processing
Resolves: [CIRC-1571](https://issues.folio.org/browse/CIRC-1571)

CIRC-1571 Add missed permissions for fee-fine-scheduled-notices

---

src/main/java/org/folio/circulation/domain/validation/CheckOutValidators.java
src/test/java/api/loans/CheckOutByBarcodeTests.java

Modal window with the error message: "Item not checked out User does not have a barcode. A user barcode is required to check out an item." should be displayed if a requested item is checked out for a user without a barcode;
Resolves: [CIRC-1550](https://issues.folio.org/browse/CIRC-1550)
- Fix NPE;
- Create a test to cover the scenario;

[CIRC-1550] Fix NPE when user without barcode try to checkout already requested item

---

descriptors/ModuleDescriptor-template.json

Resolves: [CIRC-1738](https://issues.folio.org/browse/CIRC-1738): Permission should allow for renewal of Aged to Lost items, but generates error message

CIRC-1738: Add required 'accounts.cancel.post' permission to 'circulation.renew-loan' permission set

---

src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/domain/RequestQueue.java
src/test/java/api/requests/RequestsAPICreationTests.java
src/test/java/api/support/fixtures/UsersFixture.java

Resolves [CIRC-1759](https://issues.folio.org/browse/CIRC-1759) 
Recall TLRs fail when we're looking for the loan with the least number of recalls (which we only do when we couldn't find the closest-due-date not-yet recalled loan) but there is also a request in the queue that is not associated with a loan.
Filter requests in the queue before grouping them by loan.

CIRC-1759 TLR Recall returns 500 error in some scenarios

---

src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
src/test/java/api/requests/RequestsAPIUpdatingTests.java
src/test/java/api/support/fixtures/UserExamples.java
src/test/java/api/support/fixtures/UsersFixture.java

Resolves [CIRC-1760](https://issues.folio.org/browse/CIRC-1760)
The strategy for fetching item and loan was the same for TLR recall creation and replacement.
Use default strategy for TLR recall replacement (which fixes the bug) but keep the same behavior for TLR recall creation (closest-due-date, least-recalled etc.)

CIRC-1760 Editing a recall TLR changes recalled item

---

descriptors/ModuleDescriptor-template.json

Resolves: [CIRC-1738](https://issues.folio.org/browse/CIRC-1738) Permission should allow for renewal of Aged to Lost items, but generates error message

CIRC-1738: Add required 'feefineactions.collection.get' permission to 'circulation.renew-loan' permission set

---

src/main/java/org/folio/circulation/domain/Account.java
src/main/java/org/folio/circulation/domain/FeeFineAction.java
src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/main/java/org/folio/circulation/domain/notice/schedule/FeeFineScheduledNoticeHandler.java
src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledNoticeContext.java
src/main/java/org/folio/circulation/infrastructure/storage/feesandfines/FeeFineActionRepository.java
src/main/java/org/folio/circulation/support/utils/FeeFineActionHelper.java
src/test/java/api/handlers/CloseLostLoanWhenLostItemFeesAreClosed.java
src/test/java/api/loans/anonymization/LoanAnonymizationTests.java
src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
src/test/java/api/loans/scenarios/OverrideRenewAgedToLostItemTest.java
src/test/java/api/loans/scenarios/RefundDeclaredLostFeesTestBase.java
src/test/java/api/support/builders/FeefineActionsBuilder.java
src/test/java/api/support/fixtures/FeeFineAccountFixture.java
src/test/java/api/support/fixtures/TemplateContextMatchers.java

Resolves [CIRC-1767](https://issues.folio.org/browse/CIRC-1767)
Users need to be able to include the "Additional information for patron" into their fee/fine related patron notice templates as feeCharge.additionalInformation
Extend existing implementation

CIRC-1767 Add additionalInfo token to the fee/fine notice context

---

src/test/java/api/loans/scenarios/CheckInDeclaredLostItemTest.java
src/test/java/api/loans/scenarios/RefundDeclaredLostFeesTestBase.java
src/test/java/api/support/fixtures/TemplateContextMatchers.java

Add the field "feeCharge.additionalInfo" to the Fee/Fine Charge object in the Notice context.
This mentioned scenario has already been addressed by [CIRC-1767](https://issues.folio.org/browse/CIRC-1767).
So added the test cases required for that scenario

CIRC-1766 Add the field "feeCharge.additionalInfo" to the Fee/Fine Charge object in the Notice context

---

src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/requests/PickSlipsTests.java

CIRC 1581 ( https://issues.folio.org/browse/CIRC-1581 )
CIRC 1582 ( https://issues.folio.org/browse/CIRC-1582 )
1. Add the field "currentDateTime" to the Staff Slip Object in the Staff Slip context, for pick slips generated in the Requests app
2. Add the field "currentDateTime" to the Staff Slip Object in the Staff Slip context, for hold, request delivery and transit slips generated in the Check in app
1. currentDateTime for respective objects
2. Modified test cases 
Response : 
1. Request Page : 
2. Checkin page :

CIRC 1581 - CIRC 1582

---

src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/test/java/api/requests/PickSlipsTests.java

https://issues.folio.org/browse/CIRC-1784
Add "request date" as staff slip token
Purpose
Purpose of this PR is to add "request" as staff slip token. The changes would reflect in staff slip produced in the Requests app (pick slip) and staff slip produced in the Check in app (hold, delivery request and transfer slips).
The requestDate data is already available. We just add it to returned object. This is done for pick slip resource.

Circ 1784  Add Request Date as staff slip token for checkin and request app

---

src/main/java/org/folio/circulation/infrastructure/storage/loans/LoanRepository.java

After investigating the issue ([CIRC-1777](https://issues.folio.org/browse/CIRC-1777)), it appears that the problem is related to the synchronization between the write and read database replicas, specifically with the DB_HOST_READER feature enabled. The issue occurs because the loan update logic used during checkout relies on refreshing, where an updated loan is first updated using the put method, and then the loan is refreshed by retrieving it with a GET request from the database and replacing it in the representation.
However, this causes a bug described in [CIRC-1666](https://issues.folio.org/browse/CIRC-1666) because at the moment it is read from the database, the "read" database replica is still not synchronized with the "write" one.
After analyzing the code, it was found that the …

CIRC-1788 Remove refreshing for loan update

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
ramls/circulation.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 CIRC-1804 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
src/test/java/api/requests/RequestsAPICreationTests.java

Resolves: https://issues.folio.org/browse/CIRC-1832
The purpose of this PR is to get the awaiting pickup notices when paged items checked in by multiple users.
When we create a new TLR page request with service point X for User1, "ItemA" is paged. 
When "ItemA" is checked in at service point X, the User1 will get pickup notice email.
But when we create a new TLR page request with service point X for User1, "ItemB" is paged. 
When "ItemB" is checked in service point X, the User2 is not receiving any pickup notice email.
To address this issue, we have removed a filter called "hasTopPriority" in the "sendRequestAwaitingPickupNotice" method. 
This filter was previously preventing the pickup notices from being sent to other users who were in the queue waiting. 
By removing this filter, the …

CIRC-1832 Pickup notices not sent when another item is Awaiting pickup

---

src/main/java/org/folio/circulation/services/AllowedServicePointsService.java
src/test/java/api/requests/AllowedServicePointsAPITests.java

Fix issue with empty array in allowed service points when the service point does not exist
Resolves: [CIRC-1826](https://issues.folio.org/browse/CIRC-1826)

[CIRC-1826] Fix issue with empty array in allowed service points when the service point does not exist

---

descriptors/ModuleDescriptor-template.json

Resolves [CIRC-1866](https://issues.folio.org/browse/CIRC-1866)
Purpose of this pull request is to solve issue with actual cost records being closed, but loans are not being closed automatically even when the appropriate option is selected in the loan policy.
Added missed required module permission

CIRC-1866 Added required module permission

---

descriptors/ModuleDescriptor-template.json

- set default schedule for digital reminder fee processing to once a day, one minute after midnight, Central European time
Purpose: 
Reminder fee processing is a timed back-ground process, and the immediate adopter and funding organisation (Hebis) would like it to happen once a day after midnight, Central European time. The scheduling can be changed (or disabled) any time for any given tenant, using the timer API.

Schedule reminder fee processing to run daily (CIRC-1528)

---

src/main/java/org/folio/circulation/domain/User.java

CIRC-1905 Fix NPE in User.getPersonal() method
When user is created with API it is not asking for mandatory fields like email. So User can be created without personal object which leads to NPE when getting address. This is fix for that

CIRC-1905 Fix NPE when getting address

---

src/main/java/org/folio/circulation/storage/mappers/ActualCostRecordMapper.java
src/test/java/api/loans/ExpiredActualCostRecordsProcessingTests.java
src/test/java/org/folio/circulation/storage/mappers/ActualCostRecordMapperTest.java

[CIRC-1769](https://issues.folio.org/browse/CIRC-1769)
Method that converts ActualCostRecord from POJO to JSON ignores several properties:
- id
- user.patronGroup
- user.patronGroupId
- item.volume
- item.enumeration
- item.chronology
- item.copyNumber
This PR adds support for all these properties so that whenever mod-circulation updates an actual cost record (e.g. due to its expiration) these properties are not lost.

CIRC-1769: Add support for Actual Cost Records properties lost in deserialization

---

descriptors/ModuleDescriptor-template.json

[CIRC-1953](https://issues.folio.org/browse/CIRC-1953)

CIRC-1953: Add missing permission set for allowed service points endpoint

---

src/main/java/org/folio/circulation/resources/CheckOutByBarcodeResource.java
src/main/java/org/folio/circulation/services/EventPublisher.java
src/test/java/api/loans/CheckOutByBarcodeTests.java

Investigated the reported performance issue and discovered that a significant portion of the processing time is consumed during the publication of check-out events through pub-sub. I conducted measurements on a check-out operation, revealing a total duration of 9 seconds, with 7.64 seconds attributed specifically to the pub-sub publishing process
`10.30.11.227, 10.30.15.46, 10.30.11.12, 10.30.11.12 - 10.30.15.136 - - [10/Nov/2023:10:29:27 +0000] "POST /mod-pubsub/pubsub/publish? HTTP/1.1" 204 0 rt=7.631 uct="0.000" uht="7.640" urt="7.640" "Vert.x-WebClient/4.3.5" "fs09000000" "9eb67301-6f6e-468f-9b1a-6134dc39a684" "612289/pubsub"`
Resolves: [CIRC-1950](https://issues.folio.org/browse/CIRC-1950)
Publish check-out event asynchronously

CIRC-1950 publish check-out event asynchronously

---

src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledDigitalReminderHandler.java
src/main/java/org/folio/circulation/domain/policy/OverdueFinePolicyRemindersPolicy.java
src/test/java/api/loans/ReminderFeeTests.java
src/test/java/api/support/fixtures/OverdueFinePoliciesFixture.java

Bug fix: Some reminders have a fee of 0. However, creating an account and an action for a zero fee causes problems downstream, for example when attempting to clear outstanding fees by paying them. With this change the 0 fee reminder is sent but not charged.
See CIRC-1970 for details on how the issues appear in the UI.  
Make the creation of accounts and actions conditional on the fee amount in the reminder fees process handler. 
Reminder fee unit tests are extended to test that accounts are not created for 0 fees. 
This change only touches reminder fees processing classes with no potential impact on other functions in circulation.

CIRC-1970 don't create reminder charges of 0

---

src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/support/builders/CirculationItemsBuilder.java
src/test/java/api/support/fixtures/CirculationItemsFixture.java

Covers: [CIRC-1981](https://issues.folio.org/browse/CIRC-1981)
Purpose
The purpose of the story is to display 5-digit agency name in DCB Virtual Item's check-in Print Slips as items.effectiveLocationInstitution field.{}
For more information, please refer to Edit Issue : [MODDCB-59](https://issues.folio.org/browse/MODDCB-59) - FOLIO Issue Tracker

CIRC-1981 Print AgencyCode in DCB CheckIn Print Slips

---

src/main/java/org/folio/circulation/services/EventPublisher.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/support/matchers/EventMatchers.java

The purpose of this PR is to fix the issue reported in CIRC-1985 in which its expected that user barcode be displayed as empty when an in-house checkin is performed.
The approach taken is to check the checkin is for an inHouse case then the previous loan user barcode will be displayed empty (hyphen on the UI).

[CIRC-1985] - Incorrect information in the Circulation log for the user barcode for In-house check-in action.

---

src/main/java/org/folio/circulation/services/EventPublisher.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/requests/RequestsAPICreationTests.java
src/test/java/api/support/matchers/EventMatchers.java

The purpose of this PR is to fix the issue in CIRC-2045 where in patron information should not be displayed in circulation logs for particular cases.
Libaries do Check ins for routing/transportation/status check purposes that are not tied to an open loan or request. When the item has been on loan before and the loan hasn't been anonomyized (yet), the last borrower's barcode will be displayed in circulation log for the Check in action. Future anonymization does not remove the patron barcode from this entry.
This is a circ log issue, not an anonymization issue. But it affects anonomyization in so far as there are traces left about what a patron had on loan.
More checks added along with inhouse checkin, like, item has no open loans and no requests in the queue, to determine the patron …

[CIRC-2045] - Patron information is stored in circulation log for check-ins that are not tied to a loan or request

---

ramls/loan.json
src/main/java/org/folio/circulation/domain/ActualCostRecord.java
src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/ItemDescription.java
src/main/java/org/folio/circulation/domain/RequestRepresentation.java
src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/main/java/org/folio/circulation/domain/representations/ItemSummaryRepresentation.java
src/main/java/org/folio/circulation/domain/representations/ItemsInTransitReport.java
src/main/java/org/folio/circulation/services/actualcostrecord/ActualCostRecordService.java
src/main/java/org/folio/circulation/storage/mappers/ActualCostRecordMapper.java
src/main/java/org/folio/circulation/storage/mappers/ItemMapper.java
src/test/java/api/loans/CheckInByBarcodeTests.java
src/test/java/api/requests/StaffSlipsTests.java
src/test/java/api/support/builders/ItemBuilder.java

Resolves: [CIRC-2036](https://folio-org.atlassian.net/browse/CIRC-2036)

[CIRC-2036] Add new 'displaySummarry' field to the Item schema

---

src/main/java/org/folio/circulation/domain/notice/schedule/LoanScheduledNoticeHandler.java
src/test/java/api/loans/AgedToLostScheduledNoticesProcessingTests.java

Resolves [CIRC-1965](https://folio-org.atlassian.net/browse/CIRC-1965)

CIRC-1965: Do not send "Aged to lost" notice for closed loan

---

src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/UpdateLoan.java
src/main/java/org/folio/circulation/domain/notice/schedule/ReminderFeeScheduledNoticeService.java
src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/test/java/api/loans/ReminderFeeTests.java

When an item is recalled, and the due date thus changes, then the reminders must be rescheduled, similar to other patron notices related to the due date. In the case of reminder notices, this involves removing the existing next reminder notice and creating a new notice as with other patron notices, but then also resetting the reminder counter on the loan. 
See https://folio-org.atlassian.net/browse/CIRC-2030
The rescheduling of reminders is inserted in the recall API flow of logic, alongside rescheduling of other patron notices. It requires an additional lookup of the loan's overdue fine policy to retrieve the reminder fees policy if any. 
This is all very similar to a previous pull request regarding rescheduling of reminders upon renewal (CIRC-1968), and this PR thus reuses some of the …

CIRC-2030  Reschedule reminder notices on recall.

---

src/main/java/org/folio/circulation/domain/policy/LoanPolicy.java
src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
src/test/java/api/loans/scenarios/CheckoutWithRequestScenarioTests.java
src/test/java/api/support/builders/CheckOutByBarcodeRequestBuilder.java
src/test/java/api/support/fixtures/RequestPoliciesFixture.java

Steps to Reproduce:
Log into some FOLIO environment
Title level requests must be allowed.
Set a request policy to allow page and hold.
Create a loan policy with Alternate loan period at checkout for items with an active, pending hold request set to a value that differs from the Loan period.
Create three title level requests on an instance with two items. Make two requests have the status fulfillment in progress and have one Open – Not yet filled hold request.
Check out one of the items with request status fulfillment in progress.  
Expected Results:
Since there are Open – Not yet filled requests the alternate loan period should be granted.
Actual Results:
Standard loan period is granted.
Resolves: [CIRC-2026](https://folio-org.atlassian.net/browse/CIRC-2026)

[CIRC-2026] Alternate loan period applied when multiple requests in fulfillment in progress

---

src/main/java/org/folio/circulation/domain/notice/schedule/ScheduledDigitalReminderHandler.java

Ensure that template token feeCharge.chargeDate is populated in reminder notices. 
The chargeDate is really account's  metadata.createdDate, so unlike other properties of the account object that are know up-front, the charge date is not known until after the record is persisted. Thus, take the response of the account POST so the createdDate can be picked from that.

CIRC-2077 fix empty token in notice

---

src/main/java/org/folio/circulation/domain/Loan.java
src/main/java/org/folio/circulation/domain/LoanRepresentation.java
src/main/java/org/folio/circulation/domain/validation/RenewalOfItemsWithReminderFeesValidator.java
src/main/java/org/folio/circulation/resources/RenewalValidator.java
src/main/java/org/folio/circulation/resources/renewal/RenewalResource.java
src/test/java/api/loans/OverrideRenewByBarcodeTests.java
src/test/java/api/loans/ReminderFeeTests.java
src/test/java/api/requests/RequestsAPILoanRenewalTests.java

The purpose is to allow the user to override a block on renewal if the block is due to outstanding reminders, and if the overdue fine policy is blocking renewals in that case. 
In RenewalValidator there will be a new reason to override a renewal block:  "loan has reminder fees". 
RenewalOfItemsWithReminderFeesValidator will process the override renewal request accordingly.  
This renewal block is an item level block, as opposed to manual and automated blocks, which are on the patron level. Thus, for the UI to know if it should present the override modal for renewal of loans with reminders, there is a new flag in the loan's "reminders" section -- "renewalBlocked".   
The direct unit test of the feature is ReminderFeeTests.willRenewWithOverride(). The feature is user tested by Hebis in …

CIRC-2019 Support renewal by overriding reminders block

---

src/main/java/org/folio/circulation/EventConsumerVerticle.java
src/main/java/org/folio/circulation/services/events/UniqueKafkaModuleIdProvider.java

https://folio-org.atlassian.net/browse/CIRC-2037
KafkaAdminClient failed to connect to Kafka TLS endpoints because it's config didn't include security properties.
The same approach that FolioKafkaWrapper is using - getProducerProps() method adds all required properties.

CIRC-2037 Fix KafkaAdminClient config

---

src/main/java/org/folio/circulation/infrastructure/storage/ServicePointRepository.java
src/main/java/org/folio/circulation/services/AllowedServicePointsService.java
src/main/java/org/folio/circulation/support/Clients.java
src/main/java/org/folio/circulation/support/CollectionResourceClient.java
src/main/java/org/folio/circulation/support/CustomParamCollectionResourceClient.java
src/main/java/org/folio/circulation/support/http/client/IncludeRoutingServicePoints.java
src/test/java/api/support/fakes/FakeCQLToJSONInterpreter.java
src/test/java/api/support/fakes/FakeOkapi.java
src/test/java/api/support/fakes/FakeStorageModule.java
src/test/java/api/support/fakes/FakeStorageModuleBuilder.java

[CIRC-2109](https://folio-org.atlassian.net/browse/CIRC-2109)
After [MODINVSTOR-1219](https://folio-org.atlassian.net/browse/MODINVSTOR-1219) was implemented, we need to pass `includeRoutingServicePoints=true` parameter to `/service-points` endpoint if we don't want routing service points to be ignored.
A new class `CustomParamCollectionResourceClient` is allowing to add custom query parameters to the regular "collection resource" calls.

CIRC-2109 Pass additional includeRoutingServicePoints parameter when needed

---

src/main/java/org/folio/circulation/infrastructure/storage/SearchRepository.java
src/test/java/api/ItemsByInstanceResourceTest.java

Return empty result when search doesn't find anything
[CIRC-2117](https://folio-org.atlassian.net/browse/CIRC-2117)

CIRC-2117 Return empty result when search doesn't find anything

---

src/main/java/org/folio/circulation/services/AllowedServicePointsService.java
src/test/java/api/requests/AllowedServicePointsAPITests.java

Currently, mod-circulation returns no allowed service points for operation `replace` when requested instance has no items in local tenant. This needs to be changed in order to support changes made in https://github.com/folio-org/mod-tlr/pull/57.
Resolves [CIRC-2137](https://folio-org.atlassian.net/browse/CIRC-2137).

CIRC-2137: Allowed SPs: allow `replace` operation when requested instance has no items

---

src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
src/test/java/api/requests/RequestsAPICreationTests.java

The purpose of the jira is to fix [CIRC-2168](https://folio-org.atlassian.net/browse/CIRC-2168)
In the current implementation, the request queue is checked, and a notice is triggered only if the number of openNotYetFilled recall requests is less than or equal to 1. However, this logic fails to trigger notices when multiple openNotYetFilled recall requests exist for different items because the request queue retrieves all requests associated with the instanceId when TLR is enabled.
To address this issue, the filtering process is updated to consider the itemId along with existing logic. This ensures that for a given itemId in the request queue, if there is exactly one openNotYetFilled recall request, the notice will be triggered as expected.
For the reported error scenario, test case was not …

CIRC-2168 Patron notices for the trigger “Item recalled” not sent if the item is not 1st in the title request queue

---

src/main/java/org/folio/circulation/infrastructure/storage/requests/RequestPolicyRepository.java
src/main/java/org/folio/circulation/rules/ExecutableRules.java
src/main/java/org/folio/circulation/rules/RulesExecutionParameters.java
src/test/java/org/folio/circulation/infrastructure/storage/requests/RequestPolicyRepositoryTest.java

Remove self invocations to avoid 401 error in sidecar module 
https://folio-org.atlassian.net/browse/CIRC-2199
Change endpoint self invocation to use service directly

[CIRC-2199] Avoid self-invocation for request rules while moving requests

---

ramls/request.json
src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/domain/StoredRequestRepresentation.java
src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
src/test/java/org/folio/circulation/resources/RequestNoticeSenderTest.java

Implement the code for the feature UXPROD-5001
[CIRC-2198](https://folio-org.atlassian.net/browse/CIRC-2198)

CIRC-2198 Implement the code for the feature UXPROD-5001

---

NEWS.md
pom.xml
ramls/request.json
src/main/java/org/folio/circulation/domain/Request.java
src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
src/test/java/org/folio/circulation/resources/RequestNoticeSenderTest.java

Tmp release 24.3.9

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/circulation/domain/configuration/PrintHoldRequestsConfiguration.java
src/main/java/org/folio/circulation/infrastructure/storage/ConfigurationRepository.java
src/main/java/org/folio/circulation/resources/SlipsResource.java
src/test/java/api/requests/SearchSlipsTests.java
src/test/java/api/requests/StaffSlipsTests.java
src/test/java/api/support/APITests.java
src/test/java/api/support/builders/PrintHoldRequestConfigurationBuilder.java
src/test/java/api/support/fixtures/ConfigurationExample.java
src/test/java/api/support/fixtures/ConfigurationsFixture.java

Resolves: [CIRC-2223](https://folio-org.atlassian.net/browse/CIRC-2223)

CIRC-2223 Release 24.3.10

---

descriptors/ModuleDescriptor-template.json

CIRC-2225
Add missing required interfaces.
Some required interfaces are not specified in Module Descriptor. This leads to excessive egress request routing though Kong, instead of direct calls to other module sidecars.

CIRC-2225 Add missing required interfaces

---

src/main/java/org/folio/circulation/domain/Instance.java
src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/ItemDescription.java
src/main/java/org/folio/circulation/domain/notice/TemplateContextUtil.java
src/main/java/org/folio/circulation/storage/mappers/InstanceMapper.java
src/main/java/org/folio/circulation/storage/mappers/ItemMapper.java
src/test/java/org/folio/circulation/domain/InstanceTests.java
src/test/java/org/folio/circulation/domain/OverdueFineServiceTest.java
src/test/java/org/folio/circulation/domain/RequestRepresentationTests.java

The working group for reading room circulation has identified a number of instance and item properties that some FOLIO installations using reading room features require for patron notices and slips. This PR handles six of the requested new tokens (with a few more to come in subsequent developments).  
The tokens are added to the item context, and the main work is thus being done in TemplateContextUtil. Due to the change to the structure of Instance and Item objects in Circulation, the addition of properties has cascading effects in  classes involved in instantiation of Instance or Item objects.

CIRC-2209 additional template tokens

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/circulation/domain/Item.java
src/main/java/org/folio/circulation/domain/representations/ItemSummaryRepresentation.java
src/test/java/api/loans/LoanAPITests.java

A number of instance and item properties should be available in staff slips, patron notices and due date receipts in support of a new reading room loans feature. 
A previous pull request have added the tokens in the internal, so called Item context to make them available in staff slips and notices.  This pull request is about adding them to the loan representation (displayed in circulation/loans) as well to make them available for due date receipts.
Add the properties to the internal ItemSummaryRepresentation, which is part of the loan representation, which is returned in the response of /circulation/loans, which is used for populating due date receipts. 
Since this adds to the API response, the API version is increased a minor.

CIRC-2273 tokens for due date receipt

---

src/main/java/org/folio/circulation/support/http/server/WebContext.java
src/test/java/org/folio/circulation/support/http/server/AnonymousWebContextTest.java

[CIRC-2282](https://folio-org.atlassian.net/browse/CIRC-2282)

CIRC-2282: Handle duplicate header keys

---

descriptors/ModuleDescriptor-template.json
ramls/allowed-service-points.json
src/main/java/org/folio/circulation/domain/AllowedServicePoint.java
src/test/java/api/requests/AllowedServicePointsAPITests.java

https://folio-org.atlassian.net/browse/CIRC-2350

CIRC-2350: Added discoveryDisplayName in AllowedServicePointsResource response

---

NEWS.md
pom.xml
src/main/java/org/folio/circulation/domain/policy/FixedScheduleCheckOutDueDateStrategy.java
src/main/java/org/folio/circulation/domain/policy/FixedScheduleRenewalDueDateStrategy.java
src/main/java/org/folio/circulation/support/results/CommonFailures.java
src/test/java/org/folio/circulation/domain/policy/FixedScheduleCheckOutDueDateStrategyTest.java
src/test/java/org/folio/circulation/domain/policy/FixedScheduleRenewalDueDateStrategyTest.java

https://folio-org.atlassian.net/browse/CIRC-2363

Sunflower Bugfix R1 release 24.4.5

---

NEWS.md
src/main/java/org/folio/circulation/domain/ProxyRelationship.java
src/main/java/org/folio/circulation/domain/notice/ImmediatePatronNoticeService.java
src/main/java/org/folio/circulation/domain/notice/PatronNoticeEvent.java
src/main/java/org/folio/circulation/domain/notice/PatronNoticeEventBuilder.java
src/main/java/org/folio/circulation/domain/notice/session/PatronActionSessionService.java
src/main/java/org/folio/circulation/domain/representations/logs/NoticeLogContext.java
src/main/java/org/folio/circulation/domain/validation/ProxyRelationshipValidator.java
src/main/java/org/folio/circulation/infrastructure/storage/loans/LoanPolicyRepository.java
src/main/java/org/folio/circulation/infrastructure/storage/sessions/PatronActionSessionRepository.java
src/main/java/org/folio/circulation/resources/LoanNoticeSender.java
src/main/java/org/folio/circulation/resources/RequestNoticeSender.java
src/test/java/api/support/builders/ProxyRelationshipBuilder.java
src/test/java/org/folio/circulation/domain/ProxyRelationshipTests.java
src/test/java/org/folio/circulation/resources/RequestNoticeSenderTest.java

When proxy is acting on behalf of another user and it is specified that notifications should be sent to the proxy, the notifications are always sent to the user.
- check the proxy user by `GET /proxiesfor` API and decide if it should be sent to the user or proxy where `notificationsTo` field specifies this info
[CIRC-2385](https://folio-org.atlassian.net/browse/CIRC-2385)

CIRC-2385: Fix sending notifications to proxy user

---

src/main/java/org/folio/circulation/resources/RequestFromRepresentationService.java
src/test/java/api/requests/RequestsAPICreationTests.java

https://folio-org.atlassian.net/browse/CIRC-2398
Fixes missing retrieval service point name for created page request
- Fetch the primary location for the item by `primaryServicePointId` from item during page request creation

CIRC-2398: Add missing retrieval service point name for created page request

---

src/main/java/org/folio/circulation/infrastructure/storage/inventory/HoldingsRepository.java
src/test/java/org/folio/circulation/infrastructure/storage/inventory/HoldingsRepositoryTest.java

https://folio-org.atlassian.net/browse/CIRC-2413

CIRC-2413: Fetch holdings in batches for staff slips

---

src/main/java/org/folio/circulation/resources/SlipsResource.java
src/test/java/api/printEvents/PrintEventsTests.java
src/test/java/api/requests/StaffSlipsTests.java
src/test/java/api/support/fixtures/CirculationSettingFixture.java
src/test/java/api/support/utl/BooleanArgumentProvider.java

[CIRC-2448](https://folio-org.atlassian.net/browse/CIRC-2448)
Some UI modules store boolean value for circulation setting `enablePrintLog `as strings in JSON - "true" and "false". mod-circulation needs to support both options.

CIRC-2448 Support boolean and string enablePrintLog
